### ISSUE TITLE
CSTK Token Registry in use on xDAI

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#10]
## 📋   Description
We need to actually start assigning token holders their caps! 

## 🎉   Definition of done

- [x] Registry Smart contracts written
- [x] Final decision on which chain to host the CSTK Token
- [x] CSTK Token Caps converted to % 
- [x] Close this issue: https://github.com/commons-stack/tech-token/issues/38
- [x] Registry Smart contracts deployed
- [x] Test DAO deployed and connected to Registry
- [x] Registry Smart contracts user testing with griff
- [x] Registry Smart contracts integrate changes and redeployed if needed
- [x] CSTK Token Caps put on chain

## 🤼‍♂️   Reviewer
@lorelei1

**Comment by lorelei1** [comment]
Tech-token repo is managing the progress of the Registry

**Comment by tamarandom** [comment]
Note to self : Tamara, split this into multiple issues/epic

**Comment by tamarandom** [comment]
> Note to self : Tamara, help with splitting this into multiple issues/epic

**Comment by tamarandom** [comment]
Hey @knobsdao How can we make this more clear? What are the next steps & can I help?

**Comment by knobsdao** [comment]
Hi Tam. Updated the repeating issue here #644. Is under control on my side, but let me know if anything.

**Comment by tamarandom** [comment]
Hey @knobsdao That looks beautiful. Nice and clear and easy to understand. ;)
