### ISSUE TITLE
CS Research - Review Livia's decision making guide on TEC forum

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1007]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@liviade1 

## 🔗   Work doc - inspirational links
https://forum.tecommons.org/t/decision-making-guide/609

**Comment by tamarandom** [comment]
@jessicazartler, while @liviade1 and I were chatting this through I sketched a simple decision tree. I was thinking the visual format would be easier for people to "get quickly" versus the written explanation. If this is useful, would anyone else like to map this out on a Miro board or something like? 

![Screen Shot 2021-09-14 at 9.58.00 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/5eb57c98-08c8-4b79-a53a-1cd41652fca2)
