### ISSUE TITLE
TS activations (what is the end date, how does that impact outreach for activations)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1009]
## 📋   Anything to add?
Requires board decision. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
From @krisjpi : At the board level we generally had a soft agreement that memberships were annual with an annual expiry/renewal of April 30th of the year, but that this was open to discussion as well

**Comment by mafer-labs** [comment]
This issue passes to this issue https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/1013
