### ISSUE TITLE
Trusted Seed POAP

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1015]
## 🎉   Subtasks

- [ Elaborate discussion on TS POAP] 
- [ Mint] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao @jessicazartler @GriffGreen @tamarandom @Jeff-Emmett 
@mafer-cordovas @YineisyM

**Comment by jessicazartler** [comment]
Thank you @Ekeneodigwe for making this issue :D @knobsdao I will add it to the mid-sprint to chat about it - happy to support with design - perhaps I could work with @markoprljic to make something - should be quick - and maybe I could show/cross-train Ekene/Junior gardeners how to use POAP so they can also learn in case we want to make more in the future? :D 

Have a look in the POAP gallery for inspiration https://poap.gallery/
I am loving the moving/animated ones and would like to do something like that to make it fancy and attractive to have one :D I have only done still graphics.. but would love the TS one to be extra fancy/special!

**Comment by Ekeneodigwe** [comment]
Reached AcidLazzer today on Discord, hoping he'd be on board with this project

**Comment by Ekeneodigwe** [comment]
A DM group of three (Jess, Acidlazzer and Ekene) was created on the Discord server, so far we have agreed to have one animated POAP (GIF) and distribute that at Christmas to the existing TS Members and build it into the pipeline for those who would join.

**Comment by tamarandom** [comment]
Here is the file @acidlazzer delivered! https://drive.google.com/file/d/1qBaH51CYnFGnm-AokxPsdQjDkbdurM1G/view?usp=sharing

**Comment by Ekeneodigwe** [comment]
Over now to @YineisyM for Distribution of The Trusted Seed POAP#1090
