### ISSUE TITLE
Repurpose and Distribute Regen Network – Commons Stack AMA Video 

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1017]
## 🎉   Subtasks

- [ Select Key quotes and make a clip out of them] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler @krisjpi 

## 🔗   Work doc - inspirational links
https://www.youtube.com/watch?v=W8d3E3N4BQ4&feature=youtu.be

**Comment by Ekeneodigwe** [comment]
A 02:20' video was made from the clip, this is the clip to be posted 👇👇 https://drive.google.com/file/d/1jOtCw_6wk7g767Ny1klMRLPb3Z3e9Dlz/view?usp=drivesdk


The copy for the video will read- 
"Onboarding @regen_network as a community is an opportunity to enable inclusive commons-based governance while also setting diverse regenerative tools within the Ecosystem.
What do you want us to focus on in this partnership and how can that help the project you're working on? "

**Comment by jessicazartler** [comment]
Maybe...

Our recent partnership with @RegenFndn will be the first instance of a Community Staking DAO on the @Regennetwork. What other models are their for more inclusive governance in blockchain protocols and #DAOs?"

**Comment by jessicazartler** [comment]
Tweet 2:

📑 Read more about Community Staking DAOs (https://medium.com/regen-network/community-stake-governance-model-b949bcb1eca3)
🎥 Watch the full AMA (link)
🤝 Read more about the CS <> Regen partnership

**Comment by Ekeneodigwe** [comment]
Post made on Twitter - https://twitter.com/commonsstack/status/1442887629071081474?s=20
LinkedIn as well- https://www.linkedin.com/feed/update/urn:li:activity:6848656032332300288

**Comment by Ekeneodigwe** [comment]
Started working on the Giphy, hope to post it today
