### ISSUE TITLE
Core team handover steps/process

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1024]
## 📋   Anything to add?
With two of our core team members exiting, it is a good time to get a good exit process in place. Some of the immediate steps that come to mind:

- Setting time aside to transfer over open issues on the Sprint board
- Capturing thoughts and perception in an exit interview
- A goodbye party of some sort 

## 🎉   Subtasks

- [x] [Dan's document](https://docs.google.com/document/d/18KvLzaPDYOaSIZzeOumRQ4jiqxCu_eVilNkGRPBmyWg/edit#heading=h.pwkt1xppmwue)
- [ ] Kris' document
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Here's what KrisIs did once. https://docs.google.com/document/u/1/d/11x2X5CvbR3YQuKlp9fjyGipEL5lemfMVoA252-VIB-c/edit?usp=drive_web&ouid=100603646152821457059

**Comment by iviangita** [comment]
I made a basic template for the handover report/summary, including the suggested handover process:
https://docs.google.com/document/d/1F-kPUmmsGgvK7FCvtZIZvxCFyPMBAZofkFRiSX64PgQ/edit?usp=sharing

Once the document is filled by Kris/Dan, I will file it in our [Contributors Tracking Sheet](https://docs.google.com/spreadsheets/d/1lv00-eIrVWlhkTKZrMoLey637AXA-T8JXZPio5XHE5o/edit?usp=sharing) for reference.

Hoping to get feedback if anything else needs to be covered in the report :) @tamarandom @GriffGreen

**Comment by tamarandom** [comment]
Looks great to me.

**Comment by iviangita** [comment]
This is @krisjpi's handover document: https://docs.google.com/document/d/1OBRmrbRr99jM_EOtWqRxMBKUo90iWbYzEcLpcUfPd_U/edit?usp=sharing - I think it needs more details and still probably lacks some relevant links - will keep following up :)

**Comment by tamarandom** [comment]
Closing.
