### ISSUE TITLE
Dan // Handover document 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1026]
## 📋   Anything to add?

Create a handover document for the pieces of work that you have been covering.
This document should cover a few things like:
- specific tasks and who will take them over
- specific tasks that do not have anyone to take them over
- knowledge transfer in the form of description of processes that are not self-evident
- schedule of knowledge transfer sessions with peeps on the team

Related to #1024 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer
@iviangita @mafer-cordovas @YineisyM

**Comment by kosmostasis** [comment]
Draft here: https://docs.google.com/document/d/18KvLzaPDYOaSIZzeOumRQ4jiqxCu_eVilNkGRPBmyWg/edit @iviangita @mafer-cordovas

**Comment by mafer-labs** [comment]
I'm good with everything on my side. The next steps for/with me would be the credentials handover for the email and the xDai registry.

**Comment by kosmostasis** [comment]
Provided email and Typeform credentials to @mafer-cordovas and held a session with Max. Shall continue to make myself available when needed be as bandwidth permits it. 🌱

**Comment by tamarandom** [comment]
@mafer-cordovas @YineisyM - is there any reason not to close this out now?

**Comment by YineisyM** [comment]
I'm ok with this, María and I received the pending information so we can close it.
