### ISSUE TITLE
Detailing of v1.0 wireframes

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1028]
## 📋   Anything to add?
Take the wireframes from "low resolution" to "medium resolution" so that @markoprljic can begin looking at graphical identity, etc.

## 🤼‍♂️   Reviewer

@markoprljic 
@knobsdao 
@tamarandom 
@mafer-cordovas 
@YineisyM 

## 🔗   Work doc - inspirational links
https://miro.com/app/board/o9J_lBZsbTg=/

**Comment by tamarandom** [comment]
These are looking fantastic, @kristoferlund !
