### ISSUE TITLE
Moodboards and visual identity

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1030]
## 📋   Anything to add?

Based on wireframes and spec document, produce a visual identity for the TS Dashboard.

## 🎉   Subtasks

- [ ] The Trusted Seed Logo (!!!)
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

Wireframes: https://miro.com/app/board/o9J_lBZsbTg=/

Functional specs: https://docs.google.com/document/d/1M6ojof65O2qOSmPIG9kDhKGlmZcY0renrVH1W6z30eY/edit#

**Comment by tamarandom** [comment]
Nice!

**Comment by tamarandom** [comment]
@markoprljic @kristoferlund - is there any reason not to close this issue now? Stellar work, btw!! Very impressed!!

**Comment by markoprljic** [comment]
I think this can be closed because it refers to visual identity which has been completed.

**Comment by tamarandom** [comment]
Great. Closing!
