### ISSUE TITLE
Communication: Pull the breaks on all CSLOVE airdrop comms 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1038]
## 📋   Anything to add?
As long as the shop is down, we should stop sharing the airdrop / swag comms (email welcome message).

& take it off the website (check with @kristoferlund on this)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@iviangita

**Comment by YineisyM** [comment]
I contacted Kristofer and Ivy for this issue. I created a message to replace the one on the website but at the end the store got fixed so it wasn't necessary to used it or to change the emails messages. Closed.
