### ISSUE TITLE
Troubleshoot Donna's TS Activation

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#1040]
## 📋   Anything to add?
Donna's CSTK (1125) is not showing in BlockScout and the CSDAO. She activated her TS as seen in the Etherscan link but the CSTK wasn't minted to her address as seen in Blockscout.

## 🎉   Subtasks

- [ ] Sync either with Griff or Amin directly or over the Development channel in Discord/Telegram to see what's wrong.
- [ ] Check everything's alright in Blockscout and the CSDAO.

## 🤼‍♂️   Reviewer

@GriffGreen @knobsdao 

## 🔗   Work doc - inspirational links
- https://etherscan.io/tx/0x21917be7b2652450c036034c04f99743cdfb4e468b80a834cb6c13ca9019a343
- https://blockscout.com/xdai/mainnet/address/0xb7805b7b514b4bdbce556772915b2aa9179507a4/tokens
Link of the solution:
- https://blockscout.com/xdai/mainnet/tx/0xeee7729a5e7df97803ef06c4c594b85970eb5500f741347fdecc61fbecb87569

**Comment by mafer-labs** [comment]
Talked to @aminlatifi and he saw the CSTK server needed a restart. Donna's CSTK is now showing and our member's list has no pending CSTK to mint.
