### ISSUE TITLE
Repurpose Jeff's presentation on Permaculture Economics 

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1041]
## 🎉   Subtasks

- @Jessica is to track down the Video, upload the video to YouTube and draft a Tweet
- @Ekeneodigwe will edit/polish and publish
- @Ekeneodigwe can create a new Github issue for a future tweet thread  

## 🤼‍♂️   Reviewer

@jessicazartler @iviangita @tamarandom

**Comment by jessicazartler** [comment]
Heya @Ekeneodigwe - I uploaded the video to YouTube and added a description - you can use something like this for the Tweet - feel free to have a look and make some adjustments with @iviangita if you like with hashtags - thanks!


What lessons can we draw in economics from permaculture? In this lightning talk, @jeffemmett gives a high level overview of this cross-pollination - #PermacultureEconomics and the importance of purpose-driven token ecosystems and biomimetic, integrative systems design.
https://www.youtube.com/watch?v=CbpckUQTM1Y

**Comment by Ekeneodigwe** [comment]
Published 
Twitter 

- https://twitter.com/commonsstack/status/1461357431980658699?s=20

LinkedIn

- https://www.linkedin.com/feed/update/urn:li:activity:6867133274368557056

**Comment by Ekeneodigwe** [comment]
Thanks @jessicazartler for your help on this issue.

**Comment by jessicazartler** [comment]
Thank you so much @Ekeneodigwe !!!
