### ISSUE TITLE
Updating the Trusted Seed Dashboard report in Google Data Studio

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1042]
## 📋   Anything to add?

Keeping update the report in Google Data Studio for the Trusted Seed Dashboard in Notion

## 🎉   Subtasks

- [ ] Updating related Reports (Sheets)
- [ ] Take actions related to the results

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://datastudio.google.com/reporting/3b416db0-999c-4fca-98e7-d9f78c99c5e2

**Comment by YineisyM** [comment]
Pending for adding new sections:

- People that have paid more that $450 in their memberships dues.
- Active members Max Trust information
- Emails Stats

https://datastudio.google.com/reporting/3b416db0-999c-4fca-98e7-d9f78c99c5e2

**Comment by tamarandom** [comment]
Moved to the Trusted Seed Sprint Board! 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/43
