### ISSUE TITLE
Write brief for the Swag shop V2

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1046]
## 📋   Anything to add?
@kristoferlund found an alternative solution to the dshop using WP and woocommerce plugin (for the custom token part). He verified it works, next step is a WP frontend dev to select a good shop template and customize it for the three shops. 

@markoprljic needs a brief to share with this dev/designers. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by kristoferlund** [comment]
Test shop running at http://68.183.14.23/shop, token payments (CSLOVE) working.

**Comment by kristoferlund** [comment]
[Brief](https://docs.google.com/document/d/1VHWPtV0LuX_B7jsgOfiMZZtAn_qv3w_Qbpywlk3Z5UY/edit#)
[Miro board](https://miro.com/app/board/o9J_lnSC_II=/)

**Comment by tamarandom** [comment]
@kristoferlund saved the day and wrote it out! You know praise was dished for this!! 🙏🏾  🌱
