### ISSUE TITLE
Scaffolding session for ABC article

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1047]
## 🎉   Subtasks

- [x] Griff to create channel with a few folks
- [x] Griff/Jess/Carol scaffolding session

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom 

## 🔗   Work doc - inspirational links
https://github.com/commons-stack/iteration0/issues/20

**Comment by jessicazartler** [comment]
@tamarandom just to clarify - my issue is for scaffolding alone for now

**Comment by tamarandom** [comment]
We can call this done since our last call, right @jessicazartler
