### ISSUE TITLE
Design a $1.5 Milllion Dollar Economy ;-)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1048]
Param Parties will be Announced Tomorrow :-D

**Comment by tamarandom** [comment]
I've submitted two last week. Each one brings more clarity and deeper understanding of the factors to take into consideration and consequences.

**Comment by YineisyM** [comment]
I [submitted one](https://github.com/CommonsBuild/commons-config-proposals/issues/65) last week! Yay! :)

**Comment by tamarandom** [comment]
@Ekeneodigwe @YineisyM  - your turn!! :)

**Comment by tamarandom** [comment]
Calling it done!
