### ISSUE TITLE
Community Building - October

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#105]
## 📋   Anything to add?
Connect with:
## 🎉   Subtasks

- [x] Panvala
- [x] Venture DAO
- [x] Metagame
- [x] CCA
- [x] Moloch
- [x] MetaCartel
- [x] Hermez
- [x] 1Hive
- [x] xDAI
- [x] Akasha/RadXChange
- [x] BrightID/IDchain

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
Working on partnership development for the TEC -- also connected BrightID with Zargham
Will make a separate issue for TEC DAO onboarding
