### ISSUE TITLE
Edit Monthly Newsletter

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1052]
## 🎉   Subtasks

- [x] Edit article for Yin, feedback on final draft before sending

## 🤼‍♂️   Reviewer

@YineisyM @krisjpi 

## 🔗   Work doc - inspirational links
https://github.com/commons-stack/iteration0/issues/647

**Comment by tamarandom** [comment]
Linked to #647

**Comment by jessicazartler** [comment]
Dropped comments in Yin's doc and working with her on final edits & sending

https://docs.google.com/document/d/1Xwu7A2Bx6BrVSByUBe6R_qY069mRiROjMbC1n3h4IzM/edit?usp=sharing

**Comment by jessicazartler** [comment]
@YineisyM do you have this month planned? LMK if you need any support

**Comment by YineisyM** [comment]
Hey @jessicazartler! I started the topics/structure [here](https://docs.google.com/document/d/1tU93dgmO1KgQsDzfKom0o660sf3myYdXyj6h33HHvPw/edit?usp=sharing) if you have any suggestions please let me know, maybe I'm missing something. I also added it to the comms agenda :)

**Comment by jessicazartler** [comment]
Thanks for sharing! I added a few thoughts and links - lmk if you need further support and happy to edit when you're done drafting :D

**Comment by tamarandom** [comment]
Another one out the door.

**Comment by tamarandom** [comment]
done.

**Comment by tamarandom** [comment]
Newsletter on old! Will reopen when needed.
