### ISSUE TITLE
Find Lead Contributor for Regen Partnership & TS EnDAOment

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1056]
## 🎉   Subtasks

- [x] Have a call w/ TRossi and Maria to download them on the project and find out TRossi's bandwidth & requirements to join
- [x] Schedule a call w/Tam to discuss project roadmap & TRossi contributor role & agreement

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom @krisjpi

**Comment by jessicazartler** [comment]
Scheduling a call with T Rossi next week - he is keen :D @YineisyM will DM you for times that work for you next week to join

**Comment by YineisyM** [comment]
Happy to help here but I think this issue is between you and @mafer-cordovas hahaha @jessicazartler

**Comment by jessicazartler** [comment]
OMG I'm such a dork! It auto-filled the wrong name - @mafer-cordovas !!!!!! You're my partnerships ride or die - let's do this! <3

**Comment by mafer-labs** [comment]
Happy to be onboard, mate!
 @jessicazartler

**Comment by jessicazartler** [comment]
@tamarandom wrote in Discord to schedule a call - thanks @mafer-cordovas for joining the call! Docs also pinned in Discord channel

**Comment by GriffGreen** [comment]
The TS address: regen1tqcpntpntmpzm6d7xdfp07m85zgf6xhwzd06du (I control it)

**Comment by tamarandom** [comment]
I think we can call this closed. 

@jessicazartler I had a great talk with @T-Rossi today. Tagging him here to capture the regen wallet address above.

**Comment by jessicazartler** [comment]
Great! Thanks Tam - we have a call with Regen tomorrow - T/I will update you in our Discord channel after

**Comment by ghost** [comment]
Hi everyone! So glad to be onboard :D 🙏

**Comment by jessicazartler** [comment]
Welcome Thiago! So happy to have you :D Closing
