### ISSUE TITLE
Typeform for member's projects/daos update and feedback

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1066]
## 📋   Anything to add?
The purpose is to have up-to-date information on our member's current projects and space to hear their ideas to enhance the TS community for next year.
## 🎉   Subtasks

- [x] Create Typeform
- [x] Team feedback
- [x] Distribution

## 🤼‍♂️   Reviewer

@

**Comment by mafer-labs** [comment]
Here's the script for the info update/feedback survey: https://docs.google.com/document/d/1tfO4_U10ilNPq7NW98WCnt44qWgH5ZnEzFpHEN1Na1Y/edit?usp=sharing

You can add your comments and suggestions ✨ @tamarandom @GriffGreen @YineisyM @Ekeneodigwe

**Comment by mafer-labs** [comment]
Typeform 👉 https://the-commons-stack.typeform.com/to/btiK3NTt

**Comment by mafer-labs** [comment]
Will be rolled out at the beginning of next year due to hubspot email limit.

**Comment by GriffGreen** [comment]
Will send out email

**Comment by mafer-labs** [comment]
Will be send in the next newsletter.

**Comment by mafer-labs** [comment]
Will be part of January newsletter

**Comment by mafer-labs** [comment]
It is distributed monthly in our newsletter. Closing since it was meant to create and send it to our community.
