### ISSUE TITLE
'Governing the Commons' Bookclub 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#107]
## 📋   Anything to add?

Weekly book club to read and discuss "Governing the Commons" by Elinor Ostrom

**Comment by GriffGreen** [comment]
We could reach out to the Panvala Activities fund and/or make a proposal to 1hive to auction off HNY and/or Pan during the calls to the active participants that read the chapter :-D

**Comment by GriffGreen** [comment]
https://discord.gg/b9ETJ4aTAZ wow... there is already a DAO book club!
