### ISSUE TITLE
New graphics for call announcements on Twitter

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1078]
## 📋   Anything to add?

We need a graphic designer who can create new graphics for our open calls as well as AMA to catch attention. We've been using the same graphics for almost a year already.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Closing. @rodricastillo9013 finished!

**Comment by iviangita** [comment]
Done! https://docs.google.com/presentation/d/12qjkgksrkxwzyHuT3UVu1-s92J5kPs2BxxC6VFvhbh0/edit?usp=sharing
