### ISSUE TITLE
Partnership Contact Database

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1085]
## 📋   This Database will enable us develop a comprehensive list of DAOs, contact persons and how best to reach them 
Anything to add?

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey I tagged you in this [github issue](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/497) where a contributor in the TEC took the initiative to make such a list.

**Comment by tamarandom** [comment]
Closing out this issue. 👍🏽
