### ISSUE TITLE
CSA pause agreements 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1087]
## 📋   Anything to add?

CSA runs out of funds in Dec. CSA required to send notification of pause on CSA contract to all contributors who are requesting from that fund: Griff, Livia, Ivy, Jess, Tamara 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
I notified Jess then Griff notified Livia and Tam with the message approved by Coach B. Closing!
