### ISSUE TITLE
Contract for insurance

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1088]
## 📋   Anything to add?

Draft a contract for re-insurance

(Background: have fund set aside to cover 2-3% of 317 members, anyone that wants to put up collateral will receive 4% annual)

- A contract that states that the lender (Griff) agrees to loan us (CS Association) capital and in the case of a legal issue, we will use that capital to pay for legal fees
- The contract should have limited validity
- We will pay interest - 3 month installments?

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by iviangita** [comment]
Work in progress -  https://docs.google.com/document/d/1ApNu01RCa9f3pFShSgNCDigXSBSpSWUP0zyPXOIX89Y/edit?usp=sharing

**Comment by iviangita** [comment]
The Board voted in favor of this [loan agreement](https://docs.google.com/document/d/1ApNu01RCa9f3pFShSgNCDigXSBSpSWUP0zyPXOIX89Y/edit?usp=sharing).  Just need to sort out who will sign on behalf of the Trusted Seed

Note: This is temporary to keep the Trusted Seed running. This is not the final solution. We still need to make plans for the long term.

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/108
