### ISSUE TITLE
Distribution of The Trusted Seed POAP

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1090]
## 🎉   Subtasks

- [When it is starting] 
- [How it will be distributed] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1MGp-QeI54uMfS8Sta8EcLECjfJplpPusou8o2Q6rZoM/edit?usp=sharing

**Comment by tamarandom** [comment]
Scope: 
1) send POAP to all active members (hubspot // mail merge) 
2) send POAP to newly activate members (same time as swag communication)

Next steps:
Plan out the whats and hows, dates and execute. 
Target to send out early Dec.

**Comment by tamarandom** [comment]
Hey @YineisyM! @Acidlazzer shared this. @Ekeneodigwe approved! ;)

Here is the file that you will need to use to create POAPs and handle the distribution. https://drive.google.com/file/d/1qBaH51CYnFGnm-AokxPsdQjDkbdurM1G/view?usp=sharing

**Comment by tamarandom** [comment]
Here is the link to create POAPs, happy to help you with this part if you need. https://app.poap.xyz/admin/events

**Comment by acidlazzer** [comment]
Anything you need feel free to ask me :)

**Comment by YineisyM** [comment]
Here's the doc where I'm working this issue: https://docs.google.com/document/d/1MGp-QeI54uMfS8Sta8EcLECjfJplpPusou8o2Q6rZoM/edit?usp=sharing

@tamarandom @Ekeneodigwe

**Comment by YineisyM** [comment]
Hey @tamarandom @iviangita @Ekeneodigwe as I mentioned today during our the Team Sync, I would appreciate your opinions on the texts before creating the event and start with the strategy: https://docs.google.com/document/d/1MGp-QeI54uMfS8Sta8EcLECjfJplpPusou8o2Q6rZoM/edit?usp=sharing

**Comment by YineisyM** [comment]
The plan for this distribution was set and is running. I just want to mentioned that we can make changes to our event, within 30 days of your start date (from Dec 1st) and after that we can't claim more codes. I'm closing this issue.
