### ISSUE TITLE
Provide social media stats to roll up into a TS membership dashboard 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1093]
## 📋   Anything to add?

Attached is a google sheet that displays the stats 

## 🎉   Subtasks

- [ New Followers] 
- [ Impressions] 
- [ Profile Visits] 
- [Mentions ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
[Social Media Stats Google Sheet](https://docs.google.com/spreadsheets/d/1Io2y-ChlOegdS-rr4VFQM9RVjWzba2qmNbElW9T45HQ/edit#gid=0)

**Comment by YineisyM** [comment]
Hi @Ekeneodigwe! please let me know if you are interested in integrating this information into the current Data Studio report :)

**Comment by Ekeneodigwe** [comment]
@YineisyM Could we touch base on the integration into the Data Studio report? Send me an invite to Ekeneodigwe@gmail.com on when works for you 

Who has access to the Commons Stack Medium channel? @krisjpi could you add me or share the access with me.

**Comment by Ekeneodigwe** [comment]
**Fri. Nov 19: Sprint 26: Staking**

- LinkedIn post impressions stand at 2.5k that is a 98% increase from the last sprint, 13 New Followers which is an 18% increase, 84% Unique visitors also an 18% increase and 33% button clicks

- This sprint recorded 38.2k tweet impressions,8,321 profile visits, 163 mentions and 236 New followers.

**Mid Sprint**

- 13 New followers with 2.3k post impressions on LinkedIn

- And on Twitter, we have made 19 tweets with 24.2k tweet impressions, 79 mentions, 5, 964 profile visits, and 185 new followers.

**Fri. Nov 5: Sprint 25: Cross-Pollination**

- LinkedIn Post Impressions currently stands at 1800 that’s 64% increase than the last sprint 

- During this Sprint period on Twitter, posts made earned 1.8K impressions per day. Giving us  20.6K impressions over this Sprint.

**Comment by Ekeneodigwe** [comment]
**Mid Sprint 22 November to 28 November**

- LinkedIn post impressions stand at 2.5k that is a 55%, 20 New Followers which is an 81% increase, 84% Unique visitors also an 32% increase and 100% button clicks

- This sprint we recorded 67.7k tweet impressions,17.1k profile visits, 384 mentions and 425 New followers.

**Comment by Ekeneodigwe** [comment]
**Sprint Friday December 3 - Pastoralism** 

- LinkedIn post impressions stand at 2.5k that is a 45%, 25 New Followers which is an 177 % increase, 99 Unique visitors also an 67% increase and 100% button clicks

- This sprint we recorded 78.1k tweet impressions,19.2k profile visits, 414 mentions and 440 New followers

**Comment by YineisyM** [comment]
Hey @Ekeneodigwe do you have this stats in a spreadsheet ordered by date? If so, we can add the information into the Data Studio Report 👍

**Comment by Ekeneodigwe** [comment]
> Hey @Ekeneodigwe do you have these stats in a spreadsheet ordered by date? If so, we can add the information into the Data Studio Report 👍 

No @YineisyM I do not. 
Meanwhile, I remember you were supposed to help me with the Data Studio report. Whatever happened to that sync?

**Comment by YineisyM** [comment]
> > Hey @Ekeneodigwe do you have these stats in a spreadsheet ordered by date? If so, we can add the information into the Data Studio Report 👍
> 
> No @YineisyM I do not. Meanwhile, I remember you were supposed to help me with the Data Studio report. Whatever happened to that sync?

We can try to have it this week :) let me know what time works best for you, but basically what is needed is to have the data and the KPIs that you want to measure sorted by date so that we can create the report

**Comment by Ekeneodigwe** [comment]
Started a process of moving these stats to an excel sheet then transmitting same to the Dashboard, hoping to conclude this transition by the end of the sprint

**Comment by GriffGreen** [comment]
WIll have an excel at the end of the sprint

**Comment by tamarandom** [comment]
Update: Will start this from Jan, this Sprint.

**Comment by Ekeneodigwe** [comment]
A google sheet document has been created and first entries will be recorded at the end of the month. 

[Social Media Stats](https://docs.google.com/spreadsheets/d/1Io2y-ChlOegdS-rr4VFQM9RVjWzba2qmNbElW9T45HQ/edit#gid=0)

**Comment by iviangita** [comment]
Ekene handed this over to @YineisyM based on his handover document. Yine, can you confirm or update please? Thank you :)

**Comment by YineisyM** [comment]
This task needs to be redone from scratch because the format used by Ekene to keep metrics tracked is not the most suitable to be displayed in the dashboard. I wanted to meet to talk about it but we couldn't.

I consider we can close this one and I can open a new task @iviangita

**Comment by tamarandom** [comment]
Hey @YineisyM Thanks for your feedback on this. We will close this issue for now. If it is needed, we can open a new one at a later date.
