### ISSUE TITLE
Promote highlights from our strategic partners and alliances 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1094]
## 📋   Anything to add?

@Ekeneodigwe suggested this so he can start to to promote our partners and alliances. Promotion on our #buzz in Discord, twitter, newsletter. 

Let's get a list started!! 

1. Blockscience
2. TEC
3. PrimeDAO
4. Token Engineering Academy
5. Governauts 
6. Giveth 
7. Regen 
8. IXO 
9. Longtail Financial 
10. Boson 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Ekeneodigwe** [comment]
Following Lauren up, her explanation covers all that we seek to do with this issue

**Comment by tamarandom** [comment]
Update: use the Discord native announcements feature with these and/or other partners?

**Comment by Ekeneodigwe** [comment]
> Update: use the Discord native announcements feature with these and/or other partners? 

Lauren and I stayed late into the night yesterday trying to sort out a way to bridge both announcements channels. 
I am hoping to touch base with @krisjpi concerning this. 
.@krisjpi when will be alright to chat? 
![Screenshot_20211125-155754_Discord.jpg](https://user-images.githubusercontent.com/85419053/143464806-b36e230b-46d6-4d15-a53e-2531aa927fcc.jpg)

**Comment by Ekeneodigwe** [comment]
When Announcements from Commons Stack are published it now appears on Giveth #partner-updates channel
https://discord.com/channels/679428761438912522/752178860556288001

Working on getting other Partners / Alliances to link thiers with CS

**Comment by tamarandom** [comment]
Closing out this issue. 👍🏽
