### ISSUE TITLE
Create a landing to invite people to CS Discord Server

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1096]
## 📋   Anything to add?

I'll conect with Vyvy-vi and Marko (design) to create a landing for inviting people to our Discord Server: http://discord.commonsstack.org

## 🎉   Subtasks

- [ ] Sync with Vyvy-vi and Marko
- [ ] Start the Magic

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1XqyGLYBpfZKVhRHuYyZFLYKL1fPJLsI4oq4xmNoCP24/edit?usp=sharing

**Comment by YineisyM** [comment]
Hey! Talking with Vyvy-vi he mentioned that this site https://discord.tecommons.org/ is about to be archived. However he mentioned two things related to this:

1. He can set up a website like that for Commons Stack, if we want.
2. He's working on this idea: https://file.coffee/u/V1GBsAQaPMvykR.mov and he mentioned they would be deploying an almost finished version of the TEC onboarding this weekend so perhaps we can set up something similar for the Commons Stack on next Tuesday or Wednesday?

Can you give me your thoughts on this? @tamarandom @GriffGreen @Ekeneodigwe @mafer-cordovas

**Comment by tamarandom** [comment]
@mafer-cordovas is going to take this on...

**Comment by GriffGreen** [comment]
Excited about this! I always say to people: Go to discord.giveth and discord.tec... but then i have to go figure out a discord link... this will be amazing

**Comment by tamarandom** [comment]
Hey @mafer-cordovas just FYI that we are leaving this on the CS Sprint board as it seems to fall more under community building than trusted seed building.

**Comment by usama9500** [comment]
Moving it to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/39
