### ISSUE TITLE
Figure out the plan for levels of CSTK token holders on discord

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#110]
## 🎉   Subtasks

- [x] Token minting
- [x] Adding people who've passed the threshold to the Trusted Seed telegram channel
- [ ] 

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by GriffGreen** [comment]
Needs to be broken up into monthly pieces

**Comment by GriffGreen** [comment]
This hasnt been done for ages :-(

**Comment by GriffGreen** [comment]
At this point its worth planning for...

**Comment by tamarandom** [comment]
Hey @knobsdao What are the next steps on this one?
