### ISSUE TITLE
Visual explainer for Commons Stack Commons, but take away the TEC branding 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1100]
## 📋   Anything to add?

If we take away the references to TEC, this is a great explainer for what the Commons Stack Commons looks like. 
https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/

Same for the 2-phase process:
https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Caranarq** [comment]
Hi! I'm new in Commons Stack. I would like to help with this (I can't access the provided links tho)

**Comment by tamarandom** [comment]
Hi there @caranarq! 

The TEC gitbook was updated and that's why those links don't work anymore. You can see the two visual explainers if you scroll down on this page: https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/what-is-the-tec/master

The idea would be to use the same information but branded with Commons Stack creative assets. We created it for the TEC but want to use it for future deployments. 

Not sure if you still want to take this on! But if you do, def let me or @usama9500 know! We can help and give you more info.

This is the original PPT from which those PDFs were made: https://docs.google.com/presentation/u/1/d/1X3oZ5xjqWYym7RxAnty-F-GfYwZC_BGS/edit?usp=drive_web&ouid=100603646152821457059&rtpof=true

**Comment by Caranarq** [comment]
Hi @tamarandom ! 
I'm taking on this :)
Do you know if there is a Brand manual for Commons stacks? I would be a great guide to replace the TEC branding.
Also, I'm not sure if the terms **_"HatchDAO"_** and **_"Hatch Tokens"_** should stay the same for Common Stacks, can you provide some guidance? 
Thanks

**Comment by usama9500** [comment]
Closed as @tamarandom and I decided not to continue since the current TEC ones needs to be changed significantly.
