### ISSUE TITLE
Define process to dish Sprint Review Praise

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1105]
## 📋   Anything to add?

First, what will the process be to dish the praise from the review call? 
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Can we have a generic "Commons Stack" account dish praise instead of Ivy or Algene?

**Comment by tamarandom** [comment]
Looping in @liviade1

**Comment by iviangita** [comment]
Had a sync with @liviade1 on this, yay! Here's what we propose:

For the **past Sprint Reviews**, Algene has started [transcribing the praise](https://docs.google.com/document/d/18RGwigDC_adevACLWbDZhg4SsrkNOP3538ky_kihGoA/edit?usp=sharing). But instead of her dishing them, I will help her segregate the praise and assign each praise to CS member who's most appropriate to dish the praise. CS member will then simply copy/paste the transcribed praise in the Praise channel.

For **future Sprint Reviews**, since we type the praise in the [Sprint Review agenda](https://docs.google.com/document/d/1KDNEYsV4O-6Mm64w_MgpWg2uBNI3SWC2JG49IRmU3oE/edit?usp=sharing) anyway, then we can just move them to the Praise channel right after the call. 

@tamarandom hope we can add this to the Team Sync agenda next week? 😬

**Comment by iviangita** [comment]
CLOSING! Already discussed with the team - I will sync with @missgene so we can proceed with this
