### ISSUE TITLE
Statute signing is in CSTK Token DApp

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#111]
## 🎉   Subtasks

- [ ] Statutes final
- [ ] Built in to CSTK Token DApp
- [ ] Where does it record that a person has signed? (does token dapp export to some spreadsheet?)

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
Update : statutes to be ratified in Board meeting in early Jan. 
They can still be added to the dApp.
