### ISSUE TITLE
Move CLSOVE swag shop

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1110]
https://cslove.commonsstack.org/#/

**Comment by tamarandom** [comment]
Update: the driver for this change will likely be the next time we need to use the swag shop. Perhaps in the upcoming membership drive? 

@mafer-cordovas Have you considered swag after membership activation? Perhaps it's time for Trusted Seed swag?? I'm sure Rodri would rock that !!!

Looping in @iviangita @GriffGreen

**Comment by tamarandom** [comment]
This is part of the Trusted Seed Dashboard project. Closing this issue.
