### ISSUE TITLE
Move TEC swag shop

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1111]
https://swag.tecommons.org/

**Comment by tamarandom** [comment]
@kristoferlund @iviangita @GriffGreen the TEC swag shop is still on dshop. If we want to move it to the wordpress/crypto-pay-plugin, this should be an issue for the TEC and completed with funding by the TEC. Any objection to closing this issue in the Commons Stack repo?

**Comment by tamarandom** [comment]
Closing this. Since the swag shop is working great (even though we might not be able to fix it if it breaks 😰 ).

This will be something that the TEC can pick up if they want to do this in the future.
