### ISSUE TITLE
Contributors Model Feedback

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1115]
## 📋   Anything to add?

The Contributors Model is almost done here on page 7: https://docs.google.com/document/d/1XqyGLYBpfZKVhRHuYyZFLYKL1fPJLsI4oq4xmNoCP24/edit?usp=sharing We should work on a GitHub model so people can contribute in our GitHub projects.

We should have an infographic of it to be added on Discord channels and update our wiki: https://wiki.commonsstack.org/contributors-guide (actually we have a contributor commit on this: https://github.com/commons-stack/wiki/pull/5/commits/2c65f5c103d65af264af5877743c59de6708e920)

## 🎉   Subtasks

- [ ] Feedback
- [ ] Infographics design and wiki update
- [ ] Publish the info

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

Contributors looking to raise bugs and feature requests can fill out a form as in DAOHaus:
https://forms.clickup.com/f/83fyz-1425/9CJITRZPWXTAD612RP
They also have created a contributor kanban https://sharing.clickup.com/b/h/83fyz-1405/5c588f59600254b

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/1115
