### ISSUE TITLE
Setup Wordpress / WooCommerce / Payment plugin

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1117]
- [ ] Secure installation (akismet, logins, etc)
- [ ] Warning system if problem occurs
- [ ] Backups

What else to make the installation secure and stable? Read what SiteGround has to offer.

**Comment by kkatusic** [comment]
@kristoferlund about security. We can implement Wordfence or WP Security Pro for preventing some brutal force attack to login pages. I disabled commenting in setting in administration, disabled also Theme Editing via administration and added htaccess file to "uploads" directory to prevent executing any php code. My advice is to implement these plugin only after we finish, better say Rodin make changes to his plugin to prevents some error in developing phase. Wordfence has reporting about attacks and WP Security pro also has: https://skitch.kkatusic.com/secpro_2767A9EC.png . 
After all we can also add custom link to login page, something like: http://kristoferl.sg-host.com/logintoadmin that no one will know, only us.

WP has warning system about errors, if some php error occurs it will send email to administrator: https://skitch.kkatusic.com/admin_2767AA92.png

About backups, SiteGround offer backups, but I don't know which package or type of hosting you bought:

_We automatically save daily backups and keep up to 30 copies of your account. Backup restore is the fastest way to resolve a large number of common website issues. Backup restores are free on all of our shared hosting plans. For an additional layer of security the backups may be stored in a data center located in another city, state or country._

we can provide additional backup if you have some backup server in your company, I can build backup.sh script that can make files.zip and database.zip files and send it to whatever location you want.

**Comment by kristoferlund** [comment]
@kkatusic Backups on SiteGround seems sufficient. We use the "hosting plan". 

And I agree, let's look at security after the rest of the issues etc are done.

**Comment by kkatusic** [comment]
@kristoferlund, who besides us still use WP administration? We can change login URL to avoid attacks on wp-login.php?

**Comment by kristoferlund** [comment]
@kkatusic Could you do this rename of the login URL? This is the last issue I have for the Giveth shop.

**Comment by kkatusic** [comment]
@kristoferlund no problem, new URL is: https://swag.giveth.io/loginme , if someone try to open old login URL she will get 404.

You can always change custom login URL on this link: https://swag.giveth.io/wp-admin/admin.php?page=login-settings

**Comment by tamarandom** [comment]
Hey @kristoferlund @kkatusic - with the Giveth swag shop live and having greatly impressed everyone that used it, would you say this issue can be closed now?

**Comment by kkatusic** [comment]
Yes @tamarandom , you can close this issue.

**Comment by tamarandom** [comment]
Great! Closing!
