### ISSUE TITLE
Make a Giveth shop design / skin based on WordPress theme GeneratePress

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1118]
Skin will be simple:
- Giveth logo and colors
- Hero banner on first page

![image](https://user-images.githubusercontent.com/9698363/145208900-e4cfa70c-6068-4b95-8bb8-1c4bef4b4bc9.png)

**Comment by kristoferlund** [comment]
@markoprljic, colors and logo we can snatch from giveth.io. 

But, could we get a hero banner for the first page?

**Comment by markoprljic** [comment]
Yes. Can you please assign Rodri to this?
