### ISSUE TITLE
CS Association

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1126]
## 📋   Anything to add?

This includes all the actions needed according to our (Ivy, Tam, Griff, Coach B) last sync
https://docs.google.com/document/d/1gv-Y-S0u6-blzEG9k1PMiLjeykOJ3vojzQbCEWkHM5I/edit?usp=sharing 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom

**Comment by tamarandom** [comment]
@iviangita this should also go on the list for approval by the board. It is the change to the membership terms. https://docs.google.com/document/d/1M8nlOX8ymWVhCZkNCe5y-CAhlv1LadRAgCTrhnatoZU/edit
It looks like there is agreement to recommend #4 but @mafer-cordovas will confirm!!

**Comment by usama9500** [comment]
Closing this Epic, Moved to Trusted Seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/113
