### ISSUE TITLE
Qualifying DAOs terms & conditions

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1127]

**Comment by iviangita** [comment]
In progress: https://docs.google.com/document/d/1miRmbXaXOMgOgUJWkAzXp1AE1B31BzULMSMnW_Q2SMo/edit?usp=sharing

**Comment by GriffGreen** [comment]
Will present the document to board members

**Comment by iviangita** [comment]
Board meeting on Feb 8th, 4pm CET

**Comment by iviangita** [comment]
The Board started discussing about this. The next step is to consolidate the feedback/comments and make edits on the T&Cs.

**Comment by tamarandom** [comment]
@usama9500 to be moved to Trusted Seed Sprint Board

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/107
