### ISSUE TITLE
Configure WP email sender address

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1130]
- Ideally we would like the sender to be a verified giveth address.

We don't want it to look like this in the users inbox:
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/ccde5d62-1703-4341-945e-872102bb2a5d)

**Comment by kkatusic** [comment]
We have two option here, you can add true email address like info@kristoferl.sg-host.com because Gmail knows that you didn't send that email message from that address. 
Second option is to create one mail address: info@shop-example.com and add SMTP protocol to wp_mail() function.

**Comment by kristoferlund** [comment]
The final domain will be swag.giveth.io. Would the best idea be to have an address like: noreply@swag.giveth.io?

**Comment by kkatusic** [comment]
Excellent we will use that email address, I changed it on this link **/wp-admin/admin.php?page=wc-settings&tab=email** if someone wants to make further changes.
