### ISSUE TITLE
Giveth shop meta tags and social share cards

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1131]
A share image needs to be produced and metatags / description needs to be set.

Verify everything looks good here: 
- https://www.heymeta.com
- https://cards-dev.twitter.com/validator

**Comment by kkatusic** [comment]
Added Yoast SEO plugin to manage metatags and description, every product, page, post and category now have these options: https://skitch.kkatusic.com/yoast_2771D47E.png , change what you need.
