### ISSUE TITLE
Give email template some Giveth love

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1133]
Make sure the emails sent from the store look good. 
- Giveth logo
- Colors
- Texts
- Footer text: Additional Giveth info?

Setting at: WooCommerce / Settings / Email

**Comment by kkatusic** [comment]
We set up colors, logo. Everything about this you can change on this link `/wp-admin/admin.php?page=wc-settings&tab=email`.

**Comment by kristoferlund** [comment]
Great!
