### ISSUE TITLE
See if the Commons Stack or Trusted Seed qualifies to be part of the Digital Public Goods Alliance

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1137]
## 📋   Anything to add?
There are some structures and legal things to be part of this great alliance. Let's see if we can apply to be part of in a near future. It can be also a great exercise to see our status as public good organization.
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://digitalpublicgoods.net/

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/37
