### ISSUE TITLE
Custom thank you page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1138]
When payment is done, the user should be redirected to a custom page with a nice and friendly thank you message.

https://www.tychesoftwares.com/how-to-customize-the-woocommerce-thank-you-page/

**Comment by kkatusic** [comment]
Page that visitor make payment via MetaMask or some other wallet is **_Thank You page_**: https://skitch.kkatusic.com/thankyou_276CF9C6.png .

Now we have two option, add custom div with thank you elements and change that after payment is done, hide other elements and show hidden. Or we can redirect user to fresh new page with thank you message.

I don't know if transaction process provide some variable that we can check and fire redirect? @kristoferlund

**Comment by kristoferlund** [comment]
Ah, ok. Is it possible to detect the completed payment somehow, hide payment instruction and wallet stuff and instead show custom message?

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/0c93f52c-8310-4e0a-af68-7f844a83d935)

**Comment by kkatusic** [comment]
I know how WooCommerce works on this step, it's last step of order. Plugin that make payments, or better say that provide some checkout do some stuff on this last page. There isn't any JS code provided by WooCommerce :(

We can only catch some JS variable if it is available after **Ether and ERC20 tokens WooCommerce Payment Gateway** do its job. But we don't know if that variable exist, we can ask author, you have his contact?

Or we can add some JS listener and check when payment is done and make changes to current page or redirect.

Is there any way that I can add some product about 0,1$ and test transactions, to check if there any variable that we can check?

**Comment by kkatusic** [comment]
We manage to add redirect after payment, but we have left that out for now because payment issue with ETH plugin.

**Comment by kristoferlund** [comment]
Closing because of plugin switch.
