### ISSUE TITLE
Dashboard - Connect wallet

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1139]
## Details
- The dashboard is chain agnostic. The main dashboard page should accept user connecting no matter what chain connected to.
- Components that need on chain interactions on a certain chain are extracted and given a subpage.
- The `Connect wallet` button has four potential states:
  1. Connect wallet
  2. Initialising…
  3. Wrong network
  4. Connected (show eth address and jazzicon)
- Chain requirements on subpages should be displayed alongside `Connect wallet`
## Questions
**- What wallets should we allow for connecting and interacting with the dashboard?**
**- What libraries should we use for the eth connectivity?**
  - Ethers.js
  - Web3.js 
  - …
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/9e258cc0-ffdf-46b2-a15a-c2dc9d8128d7)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
