### ISSUE TITLE
Important messages at the top of the Dashboard

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1140]
This section represents the most important information we want the user to know. Upcoming desired actions, links to blogs, tweets, etc.
Examples:
- Participate in governance…
    - "Don't forget to join this and that vote that begins on date xxx"
- Read this Medium article…

### Details
- Netlify CMS for publishing 

### UI
- Header
- Text
- Image/Icon
- Link
- Link text (Read / Vote / etc)
-

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/2064f5f6-b679-4153-b57c-0f587787e788)

**Comment by mafer-labs** [comment]
I will be taking over for this component.

**Comment by YineisyM** [comment]
Here's where I'm working this information: https://docs.google.com/document/d/1_zYpIod7ee8ehQ6UgCiF_H-DnCnLQRxT4UBnPhC_gA8/edit?usp=sharing

@kristoferlund

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/94
