### ISSUE TITLE
Membership details

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1141]
## Details
- See [main project doc](https://fmckl.notion.site/Trusted-seed-dashboard-2757f8bf9fa441d4bdd5b0f620e85c0e) for details about membership, paid date and expiration. 

### 1. Not connected:
  - Heading: "Membership details"
  - Message: "Connect wallet to view your details "

### 2. Connected, not member
  - Clear call to action!
  - Heading: "Membership details"
  - Message: "The connected address is not in the Trusted Seed registry. If you have already been accepted into the Trusted Seed, please connect with the same Ethereum address that you used to join. If you have not yet applied to be a member of the Trusted Seed, you will need to do that first."
  - Button: "Apply for membership" → links to “Apply Page”

### 3. Membership application approved, membership not activated
  - Heading: "Membership details"
  - Message: Your application to become a trusted seed member has been approved"
  - Button: Activate your membership now → links to Membership page

### 4. Active member
  - Message: Your Trusted Seed membership is active!
  - Join date message: “Member since XXXX”
  - Expiration message: "Membership expires at" 
  - Button: Manage membership → links to Membership page

### 5. Inactive member
  - Message: Your Trusted Seed membership has expired!
  - Expiration message: "Membership expired [date]" 
  - Button: Activate your membership now → links to Membership page

**Comment by usama9500** [comment]
Closing this issue here: moving to trusted seed board: https://app.zenhub.com/workspace/o/trusted-seed/coordination/issues/93
