### ISSUE TITLE
Build a definition for the Regen Partnership in 2 paragraphs

### ISSUE THREAD

**Issue by ghost** [commons-stack/iteration0#1144]

**Comment by ghost** [comment]
Scheduling a sync w/ Austin + Regen folks for this week

**Comment by GriffGreen** [comment]
Sent email today... will make a roadmap based on the doc Jess made.

**Comment by ghost** [comment]
See their tweet about it
https://twitter.com/anDAOrilho/status/1487076245913456640?s=20&t=J3DLeCQI3kSKxxaPqnEWQw

**Comment by tamarandom** [comment]
Closing this issue. The Regen tweet above covers it well.
