### ISSUE TITLE
Twitter Space - checklist and demo 

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1150]
## 🎉   Subtasks

**CHECKLIST** 

- [Prepare Topic of discussion / Sesh] Tam/ Ekene)

- [Add to CS public calendar with all of the necessary links]  (Ivy)

- [Invite Panelists, Confirm their availability ]  (Ekene)

- [Make graphic]  (Ivy)

- [Schedule Tweets ]  (Ekene) - 1 week announcement notice, 24 hour reminder tweet and I hour get ready post

- [ Promote in channels ] (Ekene)

- [ Do the thing!]

- [Join] 

**Demo** 
[Demo / Guide on how to Create, Host, Join and End](https://docs.google.com/document/d/1CwEdZYz8azPcGyb7pKuzgVe0JC31xfKBhVdQWKVEw2Y/edit#)

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Make a google template like we have for gitcoin rounds

**Update:** The google template is ready and has also been shared with the team

**Comment by Ekeneodigwe** [comment]
I would suggest that we take this on a test run sometime in February

**Comment by tamarandom** [comment]
Closing out this issue.
