### ISSUE TITLE
TS Spreadsheets' Hack Sessions

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1153]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by YineisyM** [comment]
This issue is the same that [#1089](https://github.com/commons-stack/iteration0/issues/1089). Mafe I think we should close this one but let me know if it's ok.

**Comment by YineisyM** [comment]
Closing this issue.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/36

**Comment by usama9500** [comment]
Closing this issue.
