### ISSUE TITLE
Membership Termination Process

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1159]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Will be published on the wiki and a notion for internal use

**Comment by mafer-labs** [comment]
Draft for the wiki https://docs.google.com/document/d/1wKyUGQC53JLzNG0ToJ0aN78z1tEi9nNIfb0QOAZxjQM/edit#

**Comment by GriffGreen** [comment]
#345 is worth reviewing

**Comment by tamarandom** [comment]
https://wiki.commonsstack.org/

**Comment by mafer-labs** [comment]
Needs to be revisited for nonpayment of renewal.

**Comment by mafer-labs** [comment]
https://docs.google.com/document/d/1IRokda-cbiKuip9jtFLVHb5T57tk96duONVqrCqg3Uo/edit?usp=sharing

@iviangita has updated the T&C to add the update on nonpayment. 

As soon as these changes are voted by the board. A new Gitbook for the Trusted Seed must be created to publish the membership termination conditions.

**Comment by tamarandom** [comment]
Moved to the Trusted Seed Sprint Board. 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/35
