### ISSUE TITLE
Fiat portal for donations

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#116]
## 🎉   Subtasks

- [ ] Set up Bity w/ Bernd help?
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by lorelei1** [comment]
Bernd says he can set this up, the only tricky part is using the same Swiss phone number for multiple accounts

**Comment by lorelei1** [comment]
Sounds like this is unnecessary with the new plan of redirecting fundraising efforts to TEC build

**Comment by tamarandom** [comment]
Closing.
