### ISSUE TITLE
Get the Trusted Seed on this Airdrop Tool

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1174]
https://mirror.xyz/droplist.eth/YD7rh__n4__XAljW40FKDf64QLCi0M1pFu3LF_4Bob4

They are friends of friends... keep me in the loop and use my social capital... but i need someone else to carry the flag

@YineisyM @mafer-cordovas who wants it :-D?

**Comment by mafer-labs** [comment]
Chris Cyphert, who is a TS member, is also the founder of DropList. I have talked to him and he is happy to have CS, TS, Giveth, and TEC onboard! 🥳

Will follow up with him to learn the enrollment process in detail. @GriffGreen

**Comment by mafer-labs** [comment]
what we would need for the start:
- token standard (one of erc20/erc721/erc1155) 
- title for the community
- description of the community
- chain id
- links to your website & social links

Based on this, we would set up a subgraph, to track all token holders and tokens

@GriffGreen

**Comment by tamarandom** [comment]
@usama9500 This one should be moved to Trusted Seed Sprint Board.

**Comment by usama9500** [comment]
Moved to Trusted Seed board; https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/105
