### ISSUE TITLE
Weekly email to new members for claiming their POAP

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1175]
## 📋   Anything to add?

Select the "Trusted Seed Commons Stack POAP🌱 (Send to more)" email and send it to the new members.

## 🎉   Subtasks

- [ ] Add the link to be claimed in the field used as token (or import a list)
- [ ] Click the "Trusted Seed Commons Stack POAP🌱 (Send to more)" email and by using the option "send to more" add the contacts that should received the email.

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board. 🌱
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/34
