### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1176]
The purpose of this landing page is to get people to join. If we need to push other messages we can create more landing pages.

- Describe the trusted seed, its reason to exist. 
- What is the Trusted Seed about?
- Why is this important?
- Why should you care?
- Why should you join?
- JOIN!
- Exemplify by listing some notable people and projects.
- Hint with benefits without promising airdrops.

Some tips for writing a good landing page: https://webflow.com/blog/high-converting-landing-page

## Details

- Link from landing page to dashboard highly visible!

## Copy

https://docs.google.com/document/d/19ZvQGpfkQxZ5ipIDGXXcBJyqGzMuGD1ZPVR0EG2CaSQ/edit

## Wireframes

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/b78321a2-878d-449c-952f-40904518b9cb)

## 💭 Who should be part of Advice Process on this issue

@GriffGreen @MaxSemenchuk @tamarandom

**Comment by kristoferlund** [comment]
Some good new ideas came up during the TS meeting. The landing page definitely should be focused on storytelling, on the systemic change we would like to see, on the impact you can have by joining, etc.

https://miro.com/app/board/o9J_lmIbyec=/

<img width="1848" alt="Skärmavbild 2022-04-05 kl  15 04 36" src="https://user-images.githubusercontent.com/9698363/161760755-30e5bacb-916f-41fb-b566-d408637d041f.png">

**Comment by YineisyM** [comment]
Can we change the section names (Vision, About, Mission) or add more sections to the landing page if needed? I really like the idea of having a storytelling focus but not sure if we must play with the current sections only @kristoferlund

**Comment by YineisyM** [comment]
@tamarandom @mafer-cordovas @GriffGreen @liviade1 @usama9500 could you please help me with your feedback/comments on the new text I created for the [TS Dashboard landing page](https://docs.google.com/document/d/19ZvQGpfkQxZ5ipIDGXXcBJyqGzMuGD1ZPVR0EG2CaSQ/edit?usp=sharing)? 

For better reference, this is where that text would be: https://trusted-seed-dashboard.netlify.app/

**Comment by YineisyM** [comment]
Griff has already added (and I accepted) his comments on this document, I look forward to any further feedback from the team.

**Comment by GriffGreen** [comment]
@YineisyM this could be made into #1345

**Comment by kristoferlund** [comment]
@YineisyM we can do any sections we want! You lay out the script and we'll ask @rodricastillo9013 have a look at the layout after that.

**Comment by rodricastillo9013** [comment]
@kristoferlund @YineisyM  ok! is the content defined? or it still needs to be defined, count on me to design these new sections.

**Comment by usama9500** [comment]
Moved to Trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/92
