### ISSUE TITLE
Total member count

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1177]
Simple fact box showing the total number of Trusted Seed members.

## Details
- Number of members = number of CSTK token holders.

## Questions
- **How do we retrieve the member count?**
  - A subgraph?

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/b51bd7a8-6448-4238-a221-6aa35ac4aee5)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
