### ISSUE TITLE
My CSTK / Total CSTK supply 

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1178]
Graph showcasing how your CSTK score has grown over time as well as total CSTK supply.

## Details
- Button/tab to switch between "My CSTK" and "Total CSTK Supply".
- Content fetched from subgraph

## Wireframes

![image](https://user-images.githubusercontent.com/9698363/155306411-ce631526-1aec-4216-ac4c-a515c1302f11.png)

## Inspiration

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/1c5070dd-cae4-432b-be64-1f585702b949)

## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
