### ISSUE TITLE
CSTK Score

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1179]
## Details
- Heading: "CSTK Score"
- Optional message: "Want to know how to increase your CSTK score?", links to popup, GitBook or separate webpage.

### 1. Not logged in:
- Message: "Connect wallet to view your details"

### 2. Logged in, not member
- Heading: "CSTK Score"
- Message: "Become a member to view your details"
- Button: "Apply for membership" → links to “Apply page”

### 3. Membership application approved, membership not activated
- Fact: Total CSTK Score
- Fact: Your pending score
- Fact: Your pending score in relation to to total score, percentage
- Fact: You max trust score

### 4. Active member
- Fact: Total CSTK Score
- Fact: Your CSTK score
- Fact: Your CSTK score in relation to to total score, percentage
- Fact: You max trust score

## Open questions

- 

## Wireframes

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/82db4fa8-cf73-4436-89e7-0806d5e7d5bb)

## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
