### ISSUE TITLE
Member spotlight

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1180]
Static content box that can be edited through CMS. Typical link will be to a Medium article or a YouTube vid.

## Details
- 

## Open questions
- Content and ideas for formatting needed @mafer-cordovas @rodricastillo9013 
  - Which members do we highlight
  - How do we present them?
    - Photo?
    - Quote??
    - ...

## 🔗 The links and docs related to this issue

**Comment by YineisyM** [comment]
@usama9500 will help me with this task.

He created this document where we are going to have all the descriptions needed for this section: https://docs.google.com/document/d/1HKzSY_3iJzDPYRlYLuJebdFD7b-vVClupbsffmLFa9Y/edit?usp=sharing

**Comment by usama9500** [comment]
Moving it to trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/88
