### ISSUE TITLE
Trusted Seed Members

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1181]
Show a few of the "top" members along with an icon and one line "job description".

## Details
- Members can be randomised on each load
- Member icons are not clickable
- Show one link to the "Members" page
- Content is stored in CMS, we need to maintain a list of icons and job descriptions.

## Open questions
- Content needed @mafer-cordovas 

## Inspiration

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/0767d9cf-462b-4246-908d-278fcef98c4c)

## 💭 Who should be part of Advice Process on this issue

- @GriffGreen, which members to highlight

## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
