### ISSUE TITLE
TS Association Board

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1183]
## Details
- Message: A short text about the association being headed by a board.
- Fact: Number of board members
- Link: Link to GitBook or own page:

## Open questions
- Content needed @mafer-cordovas 
- For the page component
- … and for the GitBook / webpage describing the board 
  - Members
  - How does decisions get made
  - etc
  

## 💭 Who should be part of Advice Process on this issue

@GriffGreen - board information

## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
