### ISSUE TITLE
Swag Shop

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1185]
Banner box promoting that you get free swag by being a TS member.

## Details
- Heading: "Free Swag Shop"

### 1. Not logged in:
- Message: "Connect wallet to view your CSLOVE balance"

### 2. Logged in, not member
- Message: "Become a member to get free swag!"

### 3. Membership application approved, membership not activated
- Message: "Become a member to get free swag!"

### 4. Active member
- CSLOVE balance >= 1:
  - Message: Great news, you have free swag to claim!
  - Link to: Free swag shop
- CSLOVE balance <= 1:
  - Message: "Another way to donate to is to buy swag"
  - Link to: Paid crossbrand shop

## 🔗 The links and docs related to this issue

**Comment by dan13ram** [comment]
@kristoferlund 
Can you share links to the "Free swag shop" ? 
Is that the same as the  "Paid crossbrand shop" ?

**Comment by kristoferlund** [comment]
The crossbrand shop is still on the drawing board, the free shop is currently being built.

Use https://swag.trustedseed.org for both for now.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
