### ISSUE TITLE
Social channels

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1186]
Icons and links to all TS social channels

## Details
- Telegram, Medium, Calendar, Discord, Twitter

## Open questions
- **Which existing channels do we use?**
- **Will the TS have all above channels?**
@mafer-cordovas @YineisyM @MaxSemenchuk @GriffGreen @tamarandom 

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/42bd72b9-a9b3-44a4-81d3-7ddc3b945fdd)
## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
