### ISSUE TITLE
Claim badges

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1187]
- Count the number of POAPS you have related to all deployed commons. Advertise if you have POAPS to claim.
- Not logged in:
    - General message about Trusted seed and POAPS.
    - Link to join page
- Logged in:
    - Message: "You have 2 badges to claim" or "You have no badges to claim at this time"
    - Link: My badges → links to Membership page

**Comment by YineisyM** [comment]
Hi @kristoferlund I'm the one who has the POAPs links to be claimed for the upcoming new members. I would like to know or understand more on how this could be managed through the Dashboard. I assigned this issue to myself.

**Comment by kristoferlund** [comment]
I can confirm that it is easy to query which eth addresses are allowed to claim a POAP. 

Get addresses: 
https://frontend.poap.tech/delivery-addresses/1241?limit=10&offset=0

Get POAP info:
https://frontend.poap.tech/delivery/1241

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/25340e11-6a62-4865-ba08-e6576ef7c2ee)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
