### ISSUE TITLE
Partnerships

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1188]
Showcase our current and future partners! Keep it simple for now! In the future we would more clearly like to showcase the different kinds of "partnerships" we enter into. But, when we have only one in each category, let's just group them together and let this section be "vague" for now.

All boxes are plain content boxes from the CMS.

## Details
- The partner list
  - Regen Network
  - TEC
- Each box: logos plus a sentence and a link?
- Other options possible, @rodricastillo9013 and @mafer-cordovas please propose ideas

## Open questions
- Content needed @mafer-cordovas @tamarandom @GriffGreen 
  - Which partners?
  - What messages?
- Who make it onto the list?
  - Giveth
  - TE Academy
  - General Magic
  - Blockscience
  - IXO
  - Chili
  - … ?

## Wireframes

![image](https://user-images.githubusercontent.com/9698363/153433043-9987c009-b5ab-4fde-a16e-dbbe37bac33b.png)

## 🔗 The links and docs related to this issue

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
