### ISSUE TITLE
Get help

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1189]
Integration with the HubSpot live chat function.

## Details
- Script, the first messages shown to user:
  - Welcome..
  - What would you like to do next?
    - Visit FAQ section for answers to common questions.
    - Visit #support channel at Discord
    - Chat about my question here

## Open questions
- For the script - @mafer-cordovas do we need more than above? 

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/b801b561-7611-4c58-9b6a-f847f1324c6a)
## 🔗 The links and docs related to this issue

https://www.hubspot.com/products/crm/live-chat

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
