### ISSUE TITLE
Create an Education focus group with TS members

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1194]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
Moved to the Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/33
