### ISSUE TITLE
Make an API so people can easily use Trusted Seed as an identity tool

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1202]
The Trusted Sedd can be used as a KYC of sorts... I could totally see it as a trust score bonus option for gitcoin grants for example.

The TEC and future Commons do this as well.

 it we want to push this... we would need an simple api that can say true or false with an address input.

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/110
