### ISSUE TITLE
Review membership Termination Doc

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1203]
## 📋   Anything to add?
https://docs.google.com/document/d/1wKyUGQC53JLzNG0ToJ0aN78z1tEi9nNIfb0QOAZxjQM/edit# 
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Status: Added to @iviangita's db of legal docs for CSA.https://docs.google.com/spreadsheets/d/1dGSrnBAmQ6azrXClgDhnV0Ire5-ur5YuK9_ktRPNHB0/edit#gid=0
