### ISSUE TITLE
Get the praise bot fixed

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1204]
## 📋   Anything to add?
The praise bot doesn't recognize some Telegram handles because the list of users is corrupted :( Ivy will coordinate with Frederik or Vyvy to fix the issue.

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/86a74977-8d41-4d8a-b43c-e61e6da90509)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
Update: cant be fixed.
