### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1219]
## Details

The about page contains to a large extent similar information as the landing page. This page is less focused on pushing the join message and more on general facts about the TS.

## Open questions

- 

## 💭 Who should be part of Advice Process on this issue

@MaxSemenchuk @tamarandom @GriffGreen 

## 🔗 The links and docs related to this issue

**Comment by kristoferlund** [comment]
@mafer-cordovas can you start a doc with copy for this page? And then we can all help out with comments and content.

**Comment by mafer-labs** [comment]
Let's use the Trusted Seed Sync for now to hack this.

**Comment by usama9500** [comment]
Moving it to trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/80
