### ISSUE TITLE
Membership - 1. Apply

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1220]
Component that displays current membership status

## Details

- Header: **1. Apply** 

### 1. Not logged in:
- Message: "Connect wallet to view your details "

### 2. Logged in, not applied
- Clear call to action!
- Message: "You are not yet a member of the Trusted Seed"
- Button: "Apply for membership" → links to “Apply page”

### 3. Logged in, membership application awaiting approval
- Info: Application date
- Message: Your application is awaiting approval

### 4. Logged in, membership approved
- Info: Application date
- Info: Approval status, ✅ (or similar)
- Message: Your application has been approved

## Open questions

- How do we register that the application is ongoing?
  - We feed a hidden input in the Typeform with the eth address on application
  - Zapier or similar adds eth address to list on GitHub on submit

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/fc66f7dc-af89-4029-afdf-9fbd31881947)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
