### ISSUE TITLE
Membership - 2. Sign

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1221]
To become an active member you must first sign the terms and conditions and statutes.

## Details

Header: **2. Sign** 

### 1. Not logged in:
- Message: Membership in the Trusted Seed is regulated by the following documents:
- Links to documents

### 2. Logged in, not member
- Message: Membership in the Trusted Seed is regulated by the following documents:
- Links to documents

### 3. Logged in, membership application awaiting approval
- Message: Once your application has been approved you can sign the documents to continue the activation process.
- Links to documents

### 4. Logged in, membership application approved, docs not signed
- Message: Read and sign the following documents to continue the activation process.
- Info: Signing status, graphics ✅ or ❌ or similar 
- Button: Sign documents -> Links to Sign page

### 5. Logged in, membership application approved, docs signed
- Message: You have signed the membership documents.
- Info: Signing status, graphics ✅  or similar 
- Links to documents

## Open questions
- 

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/fd95711c-1e9a-4514-a127-2cc491639e0d)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
