### ISSUE TITLE
Membership - 3. Dues

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1222]
To become an active member you must activate your membership by paying the membership dues.

## Details

Header: **3. Dues** 

### 1. Not logged in:
- Message: The Trusted Seed membership year runs Jan 1 through Dec 31. The annual dues are 450 DAI.

### 2. Logged in, not member
- Message: The Trusted Seed membership year runs Jan 1 through Dec 31. The annual dues are 450 DAI.

### 3. Logged in, membership application awaiting approval
- Message: The Trusted Seed membership year runs Jan 1 through Dec 31. The annual dues are 450 DAI.

### 4. Logged in, membership application approved, docs not signed
- Message: The Trusted Seed membership year runs Jan 1 through Dec 31. The annual dues are 450 DAI.

### 5. Logged in, membership application approved, docs signed
- Message: The Trusted Seed membership year runs Jan 1 through Dec 31. The annual dues are 450 DAI.
- Button: Pay dues -> Links to Dues page

### 6. Logged in, active member
- Message: Your membership dues are paid. By paying more membership dues you will further help the mission of the organization.
- Info: Amount paid
- Info: Payment date
- Info: Membership expires date
- Button: Pay additional dues -> Links to Dues page

## Open questions
- 

## Wireframes

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/43509cec-ac3c-46ca-bef7-efd9716cc8b8)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
