### ISSUE TITLE
Membership - badges

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1223]
Here, we would like to showcase POAP badges you as a member have claimed as well as badges you have not yet claimed.

## Details

- Header: **Badges** 
- Layout: The layout should be flexible so that there can be any number of claimed and unclaimed badges.
- Which POAP badges should be included in the list?
  - Maintain a list of badge addresses in the CMS

### 1. Not logged in:
- Display placeholder badge icons

### 2. Logged in
- Display badges, claimed and unclaimed

## Open questions
- How do we determine which user can claim which badge?

## Wireframes
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/0301999a-14b8-4954-8635-0282cd5a3a17)

**Comment by kristoferlund** [comment]
See #1187 for details about how to fetch claiamble POAPs

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
