### ISSUE TITLE
Members page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1224]
The members page list all Trusted Seed members. The page contains same information as current member page at: https://member.commonsstack.foundation/members

## Details
- Page contents in CMS

## Wireframes

![Skärmavbild 2022-02-02 kl. 10.21.16.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/6a108530-86a3-42ef-82dd-c07c8b37f90b)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
