### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1225]
The page contains same information as current FAQ page at: https://member.commonsstack.foundation/help

## Details
- Page contents in CMS

## Wireframes

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/4415661a-a821-46f5-b296-9d99ecad4bcc)

**Comment by usama9500** [comment]
Moved to Trusted Seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/74
