### ISSUE TITLE
Sign page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1226]
On this page a prospective member whose application has been approved can sign the Terms and Conditions and Statutes before moving on to next step - the payment of the dues.

## Tech Details
- Same functionality as the current membership app, https://member.commonsstack.foundation/
- Sign using metamask, see [current implementation](https://github.com/commons-stack/swissmem-dapp/blob/67cfa2467b619068f2bcfa88b63886e3808d140e/src/pages/contribute/components/Statutes.js#L30) for details.
- Save signature to IPFS using the Datapinner service, for details see [current implementation](https://github.com/commons-stack/swissmem-dapp/blob/52933f0e7a051e31f7461fb67ac0c550cb2fbea0/src/util/api.js).
- Statutes: https://ipfs.io/ipfs/QmcGNi9dcVgLJGtxJzjU2CyrrmVKkLnNPEK8JJC2a98zC5
- Terms and Conditions: https://ipfs.io/ipfs/QmYDmtmDYUPR6wjukzaNytibeNnYs41s2co4tNzkUYdd5n

## UI Details

- Message at top of screen describing the documents. 2-3 sentences.
- Display documents contents in iframes
- Link to source documents / open up in full screen

### 1. Not logged in:
- Message: Connect wallet to view signature details.

### 2. Logged in, not member
- Message: You need to apply to the Trusted Seed before being able to sign the documents.

### 3. Logged in, membership application awaiting approval
- Message: You will be able to sign the documents once your membership application has been approved.

### 4. Logged in, membership approved, docs not signed
- Message: Sign the Terms and Conditions and Statutes to continue the activation of your membership.
- Status: Not signed

### 5. Logged in, membership approved, docs signed
- Message: no message
- Status: Signed
- Signed date: 2020-01-01

## Open questions

- 

## Wireframes

There are three wireframes, check Miro for details: https://miro.com/app/board/o9J_lBZsbTg=/

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
