### ISSUE TITLE
Apply page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1227]
The page contains some general information about membership and its benefits as well as an embedded Typeform for applying to the Trusted Seed.

## Details
- Membership benefits: possibly same or similar copy like the old membership dapp
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/2b88b4a6-40a4-4986-9eb7-2aac469444a0)
- Activation process: Nice looking graphics and text describing the steps to become a member

## Open questions
- 

## Wireframes

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/8ddf4a5b-19e4-48a3-87cc-3a972044d1dc)

## 💭 Who should be part of Advice Process on this issue

@mafer-cordovas @MaxSemenchuk @tamarandom @GriffGreen here we need some clear messaging about TS membership, its benefits and the process of activating your account. Just a few sentences.

## 🔗 The links and docs related to this issue

**Comment by usama9500** [comment]
Moved to trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/117
