### ISSUE TITLE
hire a bookkeeper for CS assn

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#123]
## 🎉   Subtasks

- [ ] Hire a bookkeeper?
- [x] Get a physical address?
- [x] @lorelei1 find out with Coach B if these things are necessary

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by lorelei1** [comment]
Coach B needed one for Developer's DAO, so now we can possibly use this method as well (it's just a sticker to put on the home mailbox!)

**Comment by lorelei1** [comment]
Bookkeeper makes sure that VAT is properly managed and tax is easy at the end of the year. Clever Kin may work for us (Coach B is already working with them and they are familiar with crypto). Rotki may be useful too.

**Comment by lorelei1** [comment]
We have an official physical address! This can be found in our shared drive folder under Strategy & Governance>Commons Stack Association>Association Documents>CS Association Address

**Comment by tamarandom** [comment]
Update: Kris shared that Bernd has an idea to use a shared bookkeeper.

**Comment by tamarandom** [comment]
@iviangita @GriffGreen Any reason not to close this out and come back to it if/when the need arises?

**Comment by GriffGreen** [comment]
Coach b has one... is our accounting good enough without it?

**Comment by GriffGreen** [comment]
Confirm with coach b i we need to hire a bookkeeper...
https://docs.google.com/spreadsheets/d/1Na8WorvC6ZkFsML4g1jTsIVw9ahMnbDwEv7azhx0dTI/edit#gid=1795715770

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/109
