### ISSUE TITLE
☝️ Attractive Community

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1234]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Closing the Epic: Moving it to trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/111
