### ISSUE TITLE
☝️ Legally Sound

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1235]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Legally Sound Epic has been moved to the Trusted Seed Sprint Board! 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/30
