### ISSUE TITLE
☝️ Reputation you can trust

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1236]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Closing the Epic, moved to trusted seed repo :
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/99
