### ISSUE TITLE
2022 Renewal campaign

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1243]
## 📋   Anything to add?
https://www.notion.so/giveth/Retention-Campaign-8e00669e82a34a859136eb9fe4318f0a

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/22
