### ISSUE TITLE
Horizon Scan

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1246]
## 📋   Anything to add?
- Position TS as an attractive community that shapes the @agenda around public goods and tokenomics
- Surface prospective partnerships with either NGOs / other collabs

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/19
