### ISSUE TITLE
Terms Updates (in connection to renewal)?

### ISSUE THREAD

**Issue by MaxSemenchuk** [commons-stack/iteration0#1247]
## 📋   Anything to add?
- Grace period
- Activation dates clarification

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by mafer-labs** [comment]
Successful applicant email >
[https://app.zenhub.com/files/280516198/6ff76e83-9b2e-4afc-96fa-bffb72071387/download](https://app.zenhub.com/files/280516198/6ff76e83-9b2e-4afc-96fa-bffb72071387/download)

**Comment by iviangita** [comment]
I edited the document to integrate the latest updates in the membership period and renewal process. @mafer-cordovas kindly review and let me know if there's anything I missed or if you find something inaccurate. Thanks! :)

https://docs.google.com/document/d/1IRokda-cbiKuip9jtFLVHb5T57tk96duONVqrCqg3Uo/edit?usp=sharing

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/18
