### ISSUE TITLE
Commons Stack DAF

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#125]
## 🎉   Subtasks

- [x] Make Giveth DAF and learn how it works #87 
- [x] @GriffGreen will define more

Idea : We can create a US based association that is a member of commons stack, allowing US/crypto donations to be tax deductible. 

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
Likely not necessary - unless legal structure allows for no other means of liability protection, and we need to funnel everyone thru the DAF. Updates to come once #3 is complete.

**Comment by tamarandom** [comment]
Update: This might be a solution for the grant from OneProject if that happens.
@knobsdao sharing this one: https://www.sdgimpactfund.org/

**Comment by tamarandom** [comment]
Closing.
