### ISSUE TITLE
Pay membership dues

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1252]
Members pay their yearly membership dues on this page. Members also can pay "additional dues" to support the Trusted Seed.

## Tech Details
- Payment is made on Gnosis using xDAI.
- Payment is regular transfer to the new Minter contract. The Minter contract in turn mints CSTK tokens as well as CSLOVE tokens. These can then be claimed by the member.

## UI Details

–

## UI States

See Miro board for details on all UI states: https://miro.com/app/board/o9J_lBZsbTg=/

### 4.  Logged in, membership approved, dues not paid.

Messages based on business rules: 

- Max trust score maxed out:
  - Rule: @kristoferlund will specify
  - Message: If you send that much DAI, you will have reached your Max Trust Score. To increase your Max Trust Score, and be able to get a higher CSTK Score, please reach out to the Trusted Seed Team.
  - Pay dues button disabled
- Wallet contains less than 450 xDAI:
  - Rule: Rule active for payment of initial dues only, not for "additional dues" as any amount is allowed there.
  - Message: You need 450 xDAI to pay memberships dues and join the Trusted Seed.
  - Pay dues button disabled

## Open questions

- 

## Wireframes

See Miro board and Figma for details: 
- https://miro.com/app/board/o9J_lBZsbTg=/
- https://www.figma.com/file/X9XOjDIS6U8AEssNxx3SED/Trusted-Seed-Dashboard?node-id=452%3A468

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/3491fbca-bc76-4f84-812b-b0fb3a416cac)

## 💭 Who should be part of Advice Process on this issue

@GriffGreen @paxthemax

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
