### ISSUE TITLE
CSTK Subgraph

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1256]
## Membership stats

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/1246d92b-0a64-40a7-96d5-d67b54c5da85)

- When did user pay membership dues? Dues are paid by transferring xDAI to the new Minter contract developed by @paxthemax. Do we need to emit event in any particular way to be able to track this easily?

## Total member count

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/e97ab17c-aed7-4464-88bf-afc04bffb859)

- Total number of CSTK holders

## CSTK Score

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/9cbb9e5d-9d73-48c4-a808-dc4c1bb4a60e)

- My CSTK Score
- CSTK Supply - Total amount of CSTK in circulation

## CSTK Growth

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/bc67ec06-8ab0-4503-b5d1-8853a2af3e23)

- My CSTK growth over time
- Total CSTK growth over time

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
