### ISSUE TITLE
Regen Partnership - Organize monthly sync between CS & Regen 

### ISSUE THREAD

**Issue by ghost** [commons-stack/iteration0#1257]

**Comment by tamarandom** [comment]
Update: @T-Rossi will send a doodle to get availability from the people he hopes can join (Austin, Gijs, Jess, Maria, Griff) and share an agenda for the meeting.

**Comment by ghost** [comment]
https://doodle.com/meeting/participate/id/eXDrl45e

**Comment by ghost** [comment]
The first one is happening on April, 28 with Austin. I'll send an invite for others that may be willing to participate (Jess, Gijspoor, Mafer, Livia...)

**Comment by tamarandom** [comment]
Closing. To follow up in: #1354
