### ISSUE TITLE
Gather all legal documents and T&Cs in one place

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1268]
## 📋   Anything to add?

Make a database/record of all existing legal documents we have and their links so they are easier to track

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Tracking document: https://docs.google.com/spreadsheets/d/1dGSrnBAmQ6azrXClgDhnV0Ire5-ur5YuK9_ktRPNHB0/edit?usp=sharing

**Comment by tamarandom** [comment]
Status: done! @iviangita says close!
