### ISSUE TITLE
Review Ekene's handover document

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1274]
## 📋   Anything to add?

Distribute/take on tasks he's leaving behind

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1lVIilgFWjshKYOnfXiGn8swlc_DNnEtSuy9O01q5OYI/edit?usp=sharing

**Comment by tamarandom** [comment]
Closing. Comments in doc.
