### ISSUE TITLE
Making graphics for ABC article

### ISSUE THREAD

**Issue by usama9500** [commons-stack/iteration0#1276]

**Comment by tamarandom** [comment]
Update: @usama9500 will be coordinating with @rodricastillo9013 who will do these graphics.

**Comment by rodricastillo9013** [comment]
Project Sumary:
- 12 Graphics
- Deadlaine 5th April
- Article: https://docs.google.com/document/d/1XPR_jvVvmQ0vgXNw8Hi1q-4QNMgLaZ7fFxZByUzn7gE/edit#

@markoprljic

**Comment by usama9500** [comment]
Working on graphics improvements provided by Griff.

**Comment by usama9500** [comment]
Working on graphics improvements provided by Griff.

**Comment by rodricastillo9013** [comment]
done?

**Comment by usama9500** [comment]
@GriffGreen Can we close this issue? @rodricastillo9013 has updated the images. Is there any other feedback or improvement you think we can make in terms of graphics.

**Comment by tamarandom** [comment]
Let's close. If we need changes, we can always open a new issue in GM for Rodri to pick up.
