### ISSUE TITLE
Migrate from CSTK to a trusted seed token

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1279]
## 📋   Anything to add?

Making the distiction between CS and TS clearer should affect the CTSK token as well. Let's create a new trust token and retire CSTK.

**Comment by usama9500** [comment]
Closing this Epic, moved to trusted seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/66
