### ISSUE TITLE
What should Trusted Seed token be named?

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1280]
The Trusted Seed token replaces the CSTK token. It is primarily a reputation token, wouldn't it be cool to name it TRUST?!

Two projects seem to be using that token name already. None of the projects seem overly active though.

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/33b30819-79a9-4c0d-a085-cd08833eb96f)

What say you @tamarandom @mafer-cordovas @YineisyM @MaxSemenchuk @tamarandom ??

**Comment by tamarandom** [comment]
Closing.
