### ISSUE TITLE
Create a new DAO for minting Trusted Seed tokens

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1283]

**Comment by GriffGreen** [comment]
Will make the spec here: https://docs.google.com/document/d/1IVYTkgWX4u-A0LGdtUB99MusfB52wZjHLOKbZm3tRCM/edit

**Comment by GriffGreen** [comment]
Spec is complete needs to be passed to the Board @iviangita

**Comment by tamarandom** [comment]
@iviangita to get feedback from the people listed in the document.

**Comment by iviangita** [comment]
The Board voted in favor of changing CSTK to TRUST. I will be [drafting an article ](https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/96 )and make a comms plan to communicate this change to TS members. @GriffGreen can give updates on the tech side. :)

**Comment by tamarandom** [comment]
Hey @iviangita This one can be closed right!? (Not going to move it to the Trusted Seed Spring Board in that case!)

**Comment by iviangita** [comment]
Yes! It's here: https://aragon.1hive.org/#/trustedseed/0x9e57ee03eccb5b9693124a2f2840ca967a7fb878/vote/20/
