### ISSUE TITLE
Early Seeds POAP

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1287]
## 📋   Anything to add?

The first 50 members to renew their membership will get a special POAP.

## 🎉   Subtasks

- [x] Ask Rodri for the design
- [ ] Distribution

## 🤼‍♂️   Reviewer

@iviangita

**Comment by YineisyM** [comment]
Rodri created three options https://www.figma.com/file/X9XOjDIS6U8AEssNxx3SED/Trusted-Seed-Dashboard?node-id=1264%3A36

We agreed to animate it and add the Trusted Seed logo.

**Comment by YineisyM** [comment]
Rodri is having issues when exporting the art but he is already in communication with Acidlazzer to solve it

**Comment by tamarandom** [comment]
This issue has been moved to the Trusted Seed Sprint Board. 🌱 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/7
