### ISSUE TITLE
Connecting more than 1 sending domains in HubSpot

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1288]
## 📋   Anything to add?

Thinking of creating an email intended only for Trusted Seed matters, we were reviewing what would be the best process for better deliverability for the upcoming campaigns.

## 🎉   Subtasks

- [ ] Opened a Ticket with HubSpot
- [ ] Decide the best way to go

## 🤼‍♂️   Reviewer

@

**Comment by YineisyM** [comment]
I checked in HubSpot the process to connect an email-sending domain and actually, commonsstack.org is not connected because we need at least the Marketing Starter plan: https://knowledge.hubspot.com/domains-and-urls/connect-your-email-sending-domain

We haven't experienced so many issues with info@commonsstack.org email, but when we connect the DNS with HubSpot we're giving them permission to send emails on our behalf and will also remove the via HubSpot text that appears in the sender information at the top of our marketing emails. This will make our emails look more authentic to email filters, avoiding ending up in the spam filter and improve deliverability.

I opened a ticket with HubSpot and received this answer:

![image.png](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/75d4caf6-63ee-4d0c-9609-f32c13eb796c)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/6
