### ISSUE TITLE
Assess results of Commons Prize Phase 1 & share feedback with folk that submitted.

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1293]

**Comment by tamarandom** [comment]
Share the results, pref in xls.

**Comment by YineisyM** [comment]
This's the spreadsheet with the submissions we are receiving: https://docs.google.com/spreadsheets/d/15XQZ6InoGsfaryRcodRF4RyDrB3nyPp_Q6WLv4ImYds/edit?usp=sharing

**Comment by tamarandom** [comment]
Thanks @YineisyM it was such a great surprise to see some really thoughtful submissions in there!!

**Comment by tamarandom** [comment]
Some really thoughtful submission. Assigning to @usama9500 to work with me on giving feedback to those that shared their interest and then we can close this one.

**Comment by tamarandom** [comment]
@usama9500 - we can close this now, right? I think so since you have contacted all those that have signaled interest but have not yet submitted nominations!
