### ISSUE TITLE
Rock the vote campaign (Commons Prize)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1305]

**Comment by tamarandom** [comment]
Campaign details in this doc: https://docs.google.com/document/d/1IbiZGphjJ8966Am390HQ6-DY5j5fgyxYqD-tVqbQDm8/edit#
TS outreach in here: https://docs.google.com/spreadsheets/d/1Wj251ufrUcb-ANDW0E_f7wko57AbJunSiqXQerEP0iY/edit#gid=359597961

**Comment by tamarandom** [comment]
The personal DM outreach being tracked in #1366

**Comment by usama9500** [comment]
Outreach done by me and @YineisyM
