### ISSUE TITLE
plan community building on CS

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#1310]
## 🎉   Subtasks

- [ ] schedule a call with Maria and Yine 
- [ ] build a rodmap 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
- move to analyzing only CS praise
- Analyse CS contributions
- Who’s missing in the server - make a list and reach out

Commons
Collaborative economics
    - Bonding curve 
Cultural build 
Polycentric governance 
    - Conviction voting etc 
Reward system

Books -  
David Bollier "Think Like a Commoner” 
“Governing the commons” 

- Trusted Seed - entity that supports many commons with aligned individuals 
- Commons stack is building the commons economies 
- Book club - David Bollier "Think Like a Commoner” 
- Onboarding - governing ostrom

**Comment by usama9500** [comment]
@liviade1 will be going to create subtasks for it.
