### ISSUE TITLE
Respond to upset emails about the renewal communication 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1313]
## 📋   Anything to add?

Draft template.
Respond asap. 
Create the process to review the upset emails weekly.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by mafer-labs** [comment]
Emails were sent, here's a doc created to record the answer that will be the template for future messages (hopefully not)
https://docs.google.com/document/u/0/d/17mPxfpkB3Tx3SXSvuMbHWCdJRVFJe92PnnECaPaUeb8/edit
