### ISSUE TITLE
Adjust application typeform

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1314]

**Comment by kristoferlund** [comment]
https://trusted-seed-dashboard.netlify.app/apply-stage-two

- Remove CS logo
- Remove first screen or change text
- Adjust form colors to match website theme colors. Use #12BAD6 is possible
- Can we get rid of "Powered by typeform"?

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board.
