### ISSUE TITLE
Create a multisig wallet for TS

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1321]
# trustedseed.eth

**Comment by GriffGreen** [comment]
hahahaha yeah blocked by board meeting

**Comment by GriffGreen** [comment]
Made it on Rinkeby https://rinkeby.etherscan.io/tx/0x9aacbf1f1255b0622db3783b180c9ca388c4492a71e0dd4e5b14cac2253cce3a

**Comment by GriffGreen** [comment]
Not going to deploy to Mainnet and Gnosis Chain until we make the Giveth Project
