### ISSUE TITLE
Retro action: Connect Austin directly to Griff so they can talk regen partnership

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1324]
## 📋   Anything to add?

This came out of our Sprint Retro. @T-Rossi can you make this happen this Sprint (by make this happen I mean have a date locked in the calendar of both Griff and Austin)!

@T-Rossi, see the notes in #1312 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@T-Rossi here are the notes from #1312


liviade1
commented 36 minutes ago
we had a meeting and it was great to understand possible community engagements, research opportunities and raise questions.

questions still open:

what is regen's expectation for the CS team and community?
how would they like us to participate in governance considering we are a whale now
should there be an airdrop for the trusted seed + community building for them to engage in regen?
how to best use the resources from the partnership?
@T-Rossi

**Comment by tamarandom** [comment]
Update: Call next Thursday connecting Regen, Griff, Thiago, Tam.

**Comment by ghost** [comment]
Ok! Nice!!

**Comment by tamarandom** [comment]
Closed!
