### ISSUE TITLE
Move Trusted Seed related issues to the Trusted Seed repo 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1325]
## 📋   Anything to add?

Trusted Seed repo: https://github.com/Trusted-Seed
Zenhub board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/board?repos=469673743 

## 🎉   Subtasks
- [ ] Verify the issues on the TS board and close them on the CS board.
- [ ] Double check the Epics were also correctly moved ;)
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
The issues are moved to the new trusted seed dashboard but there seems to be a conflict with the old tasks.

**Comment by usama9500** [comment]
> For Trusted seed CSA labels
@tamarandom 

**Leftones**

**Cs Association Epic**
[Register Commons Stack DAO in Alderney](https://app.zenhub.com/workspace/o/commons-stack/iteration0/issues/1086) 
This one task is in CS association epic. The task itself doesn’t have a trusted seed label and but the epic has the trusted seed label.

**Attractive Community Epic**
[Landing page:](https://app.zenhub.com/workspace/o/commons-stack/iteration0/issues/1176) As the new sprint label was added, I was not sure whether I should close it or not! its already in the [Trusted Seed board](https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/92) as well.
[Regen Partnership Article:](https://app.zenhub.com/workspace/o/commons-stack/iteration0/issues/1197) Needconfirmation from your side whether we should remove it from that epic.

**Comment by usama9500** [comment]
All the trusted seed issues moved to Trusted Seed Board!
