### ISSUE TITLE
The Spint Review call: How can we improve, make best possible for the audience 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1326]
## 📋   Anything to add?

Study what we can do better. 
Give us some guidelines on how to improve. 

We currently have between 40 - 60 views per Review. Which is pretty great. Though it can feel like we are repeating parts and going too much into minutia. How can we do better!? 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
In progress: https://docs.google.com/document/d/1OtjjTcQEbeEOgyEjougwH690ROePfRpScfFHB3J_Omo/edit

**Comment by usama9500** [comment]
Done!
