### ISSUE TITLE
Unpublish Commons Prize page 

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1328]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@iviangita @tamarandom 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1Ysc8reiDmGtcYrMkfWLTIlcu-zMuOShwqGq0VkRKfrs/edit?usp=sharing

**Comment by YineisyM** [comment]
Still pending to create the plan for phase 2 (voting process, landing page with the submissions videos, etc).

**Comment by tamarandom** [comment]
Unpublish https://commonsstack.org/thecommonsprize and then we can close this ;)

**Comment by YineisyM** [comment]
The landing page was unpublish @tamarandom. I'm closing this issue.
