### ISSUE TITLE
Form to apply as a field test commons

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#133]
## 🎉   Subtasks

- [ ] to be defined by @lorelei1 & @liviade1 ?
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@krrisis

**Comment by lorelei1** [comment]
Yes! This was an idea Livia and I had re: responding to people who want to start a Commons/want to use our tech. It's a very common question in the form responses and telegram channels, and directing their energy towards an application form for becoming one of the Field Test Commons is a great way to capture this enthusiasm.
However, I'm not sure that it's a necessary piece of Milestone 2: Initialize Fundraise... Can anybody speak to that? If not, I'll remove it and put it to a later milestone.

**Comment by tamarandom** [comment]
@liviade1 I propose that we closet this and revisit when we are closer to ready to take this on.

**Comment by tamarandom** [comment]
Closing.
