### ISSUE TITLE
TS Membership Renewal (Follow up) 🌱

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1331]
## 📋   Anything to add?
Updates on the renewal process will go on this issue.
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by mafer-labs** [comment]
So far we have:

- 24 renewals 

- 4 scholarships for renewal approved (1,800 DAI)

- 12,227 DAI Raised from renewals and extra dues.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board. 🌱 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/5
