### ISSUE TITLE
Website is showing 20x20px images in the team section

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1334]
## 📋   Anything to add?

I contacted Paco for reviewing our website because is showing 20x20px images in the team and advisors section: https://commonsstack.org/#coreteam

![image.png](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/27fbe762-a69b-4a2c-b73c-f5a2d9a3808d)

## 🎉   Subtasks

- [x] Contact Paco
- [ ] See with Ivy how she wants to redistribute the information in that section
- [ ] Paco fixes the issue

## 🤼‍♂️   Reviewer

@GriffGreen @iviangita

**Comment by YineisyM** [comment]
I opened a ticket with Tilda for this issue:

![image.png](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/836e7049-c9fc-41e8-8d19-e9b7898becda)

![Lazy load off.JPG](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/eacf4530-d589-480f-9308-d8d693792ea2)

**Comment by YineisyM** [comment]
I got this answer but I'm not sure the answer this person provided is accurate especially since we don't have Google Tag Manager installed just Google Analytics ID and that's something they offer that can be used and shouldn't interfere with loading images.

![image.png](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/084b94cf-e607-4e1c-a373-fd4cd86a38e2)

**Comment by YineisyM** [comment]
Last information from Paco: 

![image.png](https://images.zenhubusercontent.com/6113cc4dd41f1fbf006e10fb/d0b35513-3813-4db3-8d80-f3b87c0fc568)

**Comment by tamarandom** [comment]
Looping in @pakokrew ...

**Comment by pacwoodson** [comment]
We can first disable lazy loading, it will fix the issue. 

Then if disabling lazy loading is really a problem for you I can spend more time on it trying to understand exactly where the problem comes from, but not sure if it'll worth the time vs the benefits. Platform such as Tilda are not made for going too deep into customisation, it ussually breaks it. CS website is full of custom code, obviously done by differents people.

**Comment by YineisyM** [comment]
Hi @pakokrew I disabled lazy loading and everything seems to work.

I think we can close this issue for now and if something new or different comes up we can handle it by opening a new issue. Thank you for helping us with this!
