### ISSUE TITLE
Create the content for a Trusted Seed Project on Giveth

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1345]
## 📋   Anything to add?

Pass it to griff when done to create the actual project 

People will use this to Pay Dues if they are members, or donate if not.

## 🎉   Subtasks

- [ ] needs a banner picture
- [ ] a couple paragraphs with links

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
Tagging @kristoferlund for visibility

**Comment by tamarandom** [comment]
@usama9500 This one created after you ran the script to move these to the Trusted Seed Sprint Board. ;)

**Comment by usama9500** [comment]
Moved to Trusted Seed board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/106
