### ISSUE TITLE
Update the Giveth Project for the Trusted Seed for a real description

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1346]
## 📋   Anything to add?

Use rin:0x3EFa0Ab6F541B075cFCc2388b2E060196aC26181 as the address

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Passed. Much praise to the 54 supporters from Giveth!

**Comment by tamarandom** [comment]
@usama9500 this one created after you rant the script.

**Comment by GriffGreen** [comment]
Made the project

https://giveth.io/project/trusted-seed

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/104
