### ISSUE TITLE
Build out the Commons Prize section of our Notion Page 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1350]
## 📋   Anything to add?

We just created this section on our Notion Page! Slowly building it out and we need to get @usama9500 the rights to edit that page so he can continue to build this out. (We will also create the deployment manual in Notion)

https://www.notion.so/giveth/Commons-Prize-7929eba7b5a24351a4125454aaba8592

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Done!
