### ISSUE TITLE
Please accept the Github invitation to join Trusted Seed org!! 🌱

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1353]
📋   Anything to add?

Hey! Your invitations all expired so I just resent them. 

![Screen Shot 2022-05-03 at 1.24.14 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/81385af0-ed6f-4820-a690-2529862a3f8c)

Once you accept the invitation then Usama can complete the migration to the new board. Until them we are in this funky limbo. Thank you!! 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
We have some 2FA issues left to fix. @mafer-cordovas should be good once she lands home (today/tomorrow) and @liviade1 will need solution post phone-steal. ;( But everyone else, THANK YOU!!

**Comment by mafer-labs** [comment]
All done on my side ✅

**Comment by tamarandom** [comment]
Yes! Welcome back, @mafer-cordovas !!!!!
