### ISSUE TITLE
Coordinate finalist AMA & Voting party 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1383]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Keeping open for the vote for the winner!

**Comment by tamarandom** [comment]
Check-in with the finalists about dates/times we thought could work for voting parties.

**Comment by usama9500** [comment]
Coordination done!!!

**Comment by tamarandom** [comment]
Closing! Gotta hand it to @usama9500, he did an excellent job on the Commons Prize coordination!
