### ISSUE TITLE
Improve CS Twitter profile

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1403]
## 📋   Anything to add?
Add a short description about Commons Stack in the banner and revise bio

PFP - logo
Banner - What you are
Bio - Explain + CTA

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1MwJaEbBRanLLUVWxsM6k9KeUc8naCD0YXX7gLQ2JEJE/edit?usp=sharing

**Comment by YineisyM** [comment]
Should we close this issue @iviangita? 😅

**Comment by iviangita** [comment]
Banners here: https://docs.google.com/presentation/d/1UqQ_OaZyDAYDFa4MeI2PnI7YtbTWR_N8CuRpYHn_3LM/edit?usp=sharing

**Comment by iviangita** [comment]
Closing! If anyone has feedback or suggested changes, please drop your comments here.

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/354e21b7-80a7-49c6-abec-b045f42753db)
