### ISSUE TITLE
Organize a blockchain for good meetings

### ISSUE THREAD

**Issue by Cotabe** [commons-stack/iteration0#1404]
If you're looking at this issue hoping to contribute to the project, welcome! We'd love to have you contribute, so please let us know if you have any questions. 

Comment on the issue or touch base in our [telegram](https://t.me/joinchat/HGrjjRS2PoowbH1ODuefuA). 

## 🎉   Steps to closing this issue:

- [ ] 
- [ ] 
- [ ] 

## 🤓Project Manager - check in with me for questions on this issue!

🙋‍♀️🙋‍♂️ @

## 🔗   Working documents and inspirational links go here: 
👉 
👉

**Comment by Cotabe** [comment]
Sorry this was just a test to use Tokenlog

**Comment by tamarandom** [comment]
Hey @cotabe! No problem. I will close it out now.
