### ISSUE TITLE
Create a template for Giveth milestones monthly payout

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#141]
## 📋   Anything to add?

The current process for what to include in a monthly milestone is not really clear, lets fix that 👍 

## 🎉   Subtasks

- [x] Create a template

## 🤼‍♂️   Reviewer

@Kisgus

**Comment by lorelei1** [comment]
Created the template last week! You can find it in issue #156 (there's both a google doc that is an example milestone, as well as a checklist of what any milestone needs in the text of the issue)

I asked around in Giveth about the template feature in the DApp (wasn't able to find it) but I haven't gotten an answer yet.
