### ISSUE TITLE
Documentation for Praise 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1417]
## 📋   Anything to add?

What documentation needs to be written and what can be reused? 

These are good examples of what can be resused:
https://forum.tecommons.org/t/rules-of-praise/667
https://forum.tecommons.org/t/quantifier-onboarding/825

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Rachaelmalachy** [comment]
Transferred to Iteration0 #1422
