### ISSUE TITLE
Commons Deployment Manual

### ISSUE THREAD

**Issue by usama9500** [commons-stack/iteration0#1426]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
This is really coming along now!! Phase 1 is complete. Three more to go! 

It is still unpublished as @usama9500 and I build it. 
https://app.gitbook.com/o/-Laz-tqO4q098y71WIRD/s/-LZFz-trSCxJphnx62LD/commons-deployment-manual

**Comment by tamarandom** [comment]
Moved to Notion --> https://www.notion.so/giveth/cd9c192e0b38432fab668a578a06add9?v=1d2ba0b1c5b249f8bd27386519cc942b&p=77350ecd5a5c4efb8e285c48a39e65a9&pm=s
