### ISSUE TITLE
Gnosis - schedule kickoff meeting

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1429]

**Comment by Rachaelmalachy** [comment]
Pre-kickoff meeting was held June 22nd
Agenda: https://docs.google.com/document/d/1egaVwiP1lcavrEy5t5RMwscsqJgywR_TWTTXHtLxBEQ/edit#heading=h.e1nbjal0pqel

Main kickoff session scheduled for 3rd August
