### ISSUE TITLE
AMA Call

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#143]
## 📋   Anything to add?

Let's start a monthly AMA at some point - to be defined.

## 🎉   Subtasks

- [ ] Find a Champion
- [ ] Have the Champion coordinate to find a time
- [ ] Champion to fill out rest of these

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
Closing. We're on top of this in Epic #533! ;)
