### ISSUE TITLE
CS - complete Step 3 "Prepare the community"

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1434]

**Comment by Rachaelmalachy** [comment]
Held June 22nd
Agenda: https://docs.google.com/document/d/1inyLvRPyLC52fxZQ87ed4cjnZ5wU0gd8eyNw6TGS0kw/edit
Miro board presentation: https://miro.com/app/board/uXjVOzPidHY=/
Question doc: https://docs.google.com/document/d/1zTyHjcKxZZvcgwVTYCexi3QejFFcfjvzEClvSsi2ldI/edit#heading=h.blrhe7sp518b
Slides: https://docs.google.com/presentation/d/1My7-hgtjdFqVlujPp9CN7mLh9W31EemEkDAwtY89i3c/edit#slide=id.g13194617f20_0_78
