### ISSUE TITLE
Giveth - support Mitch drafting proposal to Giveth community

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1435]

**Comment by tamarandom** [comment]
https://docs.google.com/document/d/19Xc8lhUWSVuN-VdBbll12ZYv9wgxhk4G4_Bt9TxGh1E/edit#

**Comment by Rachaelmalachy** [comment]
https://docs.google.com/document/d/19Xc8lhUWSVuN-VdBbll12ZYv9wgxhk4G4_Bt9TxGh1E/edit#

**Comment by Rachaelmalachy** [comment]
https://docs.google.com/document/d/19Xc8lhUWSVuN-VdBbll12ZYv9wgxhk4G4_Bt9TxGh1E/edit#

**Comment by tamarandom** [comment]
Major praise to Mitch for quarterbacking this through. 
https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98/proposal/33
