### ISSUE TITLE
Praise Twitter Campaign

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1437]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Rachaelmalachy** [comment]
https://docs.google.com/document/d/1mkBcBvlPgNjy4dUH7lMrjQzJY0PsTn6FL_S-USnOcOI/edit

**Comment by iviangita** [comment]
Notes from our sync are [here](https://docs.google.com/document/d/1mkBcBvlPgNjy4dUH7lMrjQzJY0PsTn6FL_S-USnOcOI/edit). I also invited Rachael to join the CS weekly comms meeting. Can we close this @Rachaelmalachy?

**Comment by tamarandom** [comment]
Closing!
