### ISSUE TITLE
Radicle - set up demo for their community for ASAP

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1439]
## 📋   Anything to add?

On our side we will come back to you with some time slots for a  Praise demo for the Radicle community. The criteria is: 1 week advance notice, on a Monday is what they have been doing, 3 or 4 pm CET is best time for Radicle community.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Rachaelmalachy** [comment]
First Praise demo for Radical community scheduled on Mon, June 27th fell through as no community member showed up. Has been rescheduled for Tue, July 12th

**Comment by tamarandom** [comment]
Done!
