### ISSUE TITLE
Update CS logo in different platforms

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1456]
## 🎉   Subtasks

- [X] Medium
- [X] Twitter
- [X] Youtube
- [x] Email/Hubspot
- [x] Graphics

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Hey @YineisyM, would you mind updating the logo in our newsletter and email? Or if you have done that, please tick the box in the description of this issue. Let me know if you need anything from me, thank you!!! :D

**Comment by iviangita** [comment]
Hey @YineisyM, would you mind updating the logo in our newsletter and email? Or if you have done that, please tick the box in the description of this issue. Let me know if you need anything from me, thank you!!! :D

**Comment by iviangita** [comment]
Hey @YineisyM, would you mind updating the logo in our newsletter and email? Or if you have done that, please tick the box in the description of this issue. Let me know if you need anything from me, thank you!!! :D

**Comment by YineisyM** [comment]
I updated it @iviangita I ticked the box. Thanks!
