### ISSUE TITLE
"Assigning Quantifiers" issue on the Praise dashboard

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1459]
## 📋   Anything to add?

Yineisy and I have been having issues with assigning quantifiers for each period.
We are a total of 6 quantifiers and whenever we open a new period and try to assign all quantifiers, it says:
**Additional members needed for quantification: xx
 Quantifier pool requirements are not met.**

So we find ourselves playing around with the settings until we arrive at a number of "Praise per quantifier" that works.
What I normally do to arrive at this number is add all the Praise count for that period and divide it by 2.

Right now, we have 3 quantifiers per praise and Ideally we want all 6 quantifiers to be assigned for each period.

I am not sure if this is a bug or if we are having this issue because we do not have enough quantifiers in the quantifier pool.

We need some help with this issue.

Thank you

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by kristoferlund** [comment]
When you have a small number of quantifiers and/or small number of Praise in a period, use the setting `Assign praise evenly among quantifiers`.
