### ISSUE TITLE
Prepare Praise deployment deck

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1469]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Rachaelmalachy** [comment]
https://docs.google.com/presentation/d/1My7-hgtjdFqVlujPp9CN7mLh9W31EemEkDAwtY89i3c/edit#slide=id.g131e507c609_0_42

**Comment by tamarandom** [comment]
Lets review together @Rachaelmalachy

**Comment by tamarandom** [comment]
Closing.

**Comment by tamarandom** [comment]
Closing.
