### ISSUE TITLE
Create Custom Unsubscribe Page

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#147]
## 🎉   Subtasks

- [ ] find the person to do it (@geleeroyale perhaps?)
- [ ] If on Mailchimp, @krrisis could you help?
- [ ] 

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
https://mailchimp.com/help/how-the-form-builder-works/ 
https://us10.admin.mailchimp.com/lists/designer/?id=331833 
According to that article, we should be able to customize the "update profile" form, ideally to include drop down fields for preference of which type of emails you receive. "The items in the Update Profile section show you what contacts will see when they request to update their profile information like their email address, group preferences, or audience information."
Ideally we would just create a group preferences drop down where someone can select from Transactional Mails Only, Important Updates, or Newsletters ... something like that. This is the "soft unsubscribe" option we would like to give people so they don't fully unsubscribe to everything. 
But I'm SOOOO lost I don't understand why I can't find the way to properly edit the "update profile" form in Mailchimp form builder! The sign up form has the "add custom field" option when editing:
<img width="1223" alt="Screen Shot 2020-09-11 at 9 57 06 AM" src="https://user-images.githubusercontent.com/38163206/92952711-bd687a00-f460-11ea-8a62-3c4b9fa267bc.png">
But when you go to edit the "update profile" form it has none of these options... all the editable details are just design things 
<img width="1226" alt="Screen Shot 2020-09-11 at 10 07 16 AM" src="https://user-images.githubusercontent.com/38163206/92953513-1dabeb80-f462-11ea-90f5-39a31c17dd9b.png">

Perhaps it's this?? (At the very bottom of that page, clicking "advanced mode" - this is writing in HTML, but still looks limited to design TBH; or clicking "completely customized forms" - but the templates this leads you to don't seem to allow any drop downs or check box questions or anything besides really a page to accept money or email addresses) 
<img width="1195" alt="Screen Shot 2020-09-11 at 10 14 26 AM" src="https://user-images.githubusercontent.com/38163206/92954406-b000bf00-f463-11ea-9c8d-02d4bbec3c2a.png">

**Comment by lorelei1** [comment]
Argh! Even tho at the bottom of the emails it says "Want to change how you receive these emails?
You can update your preferences or unsubscribe from this list." Shouldn't the Update Preferences (Profile) page then allow you to deselect some types of emails?!?

**Comment by lorelei1** [comment]
Try to find somebody who does SPECIFICALLY this on Fiver or Upwork

**Comment by lorelei1** [comment]
Made a posting on Upwork: https://www.upwork.com/ab/applicants/1306736104665460736/job-details

**Comment by lorelei1** [comment]
I've hired a person from Upwork. They'll get started today and we need to give them the text for the page. I made a rough outline - please review here! https://docs.google.com/document/d/1J5J7do6Jbex18LnSc37gT_It4tKVFEb3WwL7DJx3UHs/edit?usp=sharing

**Comment by GriffGreen** [comment]
All the design assets are here: https://github.com/commons-stack/commons-stack-assets/

**Comment by lorelei1** [comment]
We've got a design. I still need someone to edit this copy!
[
<img width="925" alt="Screen Shot 2020-10-26 at 10 00 45 AM" src="https://user-images.githubusercontent.com/38163206/97203547-42131b80-17b5-11eb-8be7-3b0b1a935e89.png">
](url)

**Comment by GriffGreen** [comment]
It looks Great!

**Comment by GriffGreen** [comment]
How will it look on mobile?

**Comment by jessicazartler** [comment]
Looks awesome!

For copy:
1) I would say that "opportunities to use your own tech stack" is a little confusing not sure what you mean by that... I would keep it simple with the first line.

2) ...information you'd prefer:  (colon instead of exclamation)

3) Frequency section:

I'd like occasional updates - Monthly newsletters (as we now have them :D)

Give me your all! haha is good (We don't send that much right now! but I am sure that could change..)

Awesome! This is a great initiative to support keeping the subscribers, nice work!
let me know if I can help with anything else on this 🙏

**Comment by jessicazartler** [comment]
@lorelei1 anything else we need for this going forward - or can we close this issue? Thank you again for the awesome work!

**Comment by jessicazartler** [comment]
@knobsdao just so you have awareness - I am closing this issue but if you would like to review just to see if we would like any further changes but I think it's great - closing

**Comment by jessicazartler** [comment]
Actually, we have Rosa I could ask her to help with this issue shouldn't be tooo hard... how does she get back end access to our stuffs? And what is needed? is it Kay?

**Comment by liviade1** [comment]
@jessicazartler do we have updates if Rosa is taking this on?

**Comment by jessicazartler** [comment]
I have not spoken to her.. have not looked at this issue since December haha.. Lorelai had done the original work - have no idea if we need more on this... @krisjpi can advise :D

**Comment by knobsdao** [comment]
@liviade1 if not Rosa, we could ping Kristofer, he helped fix the connection between the TEC website and the newsletter subscription that goes into the TEC's HubSpot.

**Comment by liviade1** [comment]
@knobsdao great idea!
