### ISSUE TITLE
Update and upload Praise documentation  on Notion

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1493]
## 📋   Anything to add?
https://www.notion.so/giveth/Praise-Deployment-8ee2eee8b2114438a5da8aeb5e419834

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
For Praise Deployments.

**Comment by Rachaelmalachy** [comment]
Going up this week, hopefully
