### ISSUE TITLE
Praise life cycle Video for presentation and marketing of Praise

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1510]
## 🎉   Subtasks

Write video script
Have script reviewed by @kristoferlund @liviade1 @tamarandom @iviangita
Set up screen recording software
Record video and audio
Edit recording
Share with the team for feedback
Make edits (if any)
Upload video on Praise website
Share videos on twitter, YouTube, Discord etc.

## 🤼‍♂️   Reviewer

@kristoferlund @tamarandom 

## 🔗   Work doc - inspirational links
Script Draft 
https://docs.google.com/document/d/1HgkXx3A_3B_qhIpmqAlhJJrmWvTnqVOSa2IEKB8ePAM/edit

Video powerpoint concept
https://docs.google.com/presentation/d/1-GJHiEME6peKo0hCtmnxCp-zzkUKzm2r/edit#slide=id.p1

**Comment by kristoferlund** [comment]
Had a great conversation with @Rachaelmalachy about which Praise videos we could/should make and in what order, first one being An introduction to Praise. Please have a look at this list and comment if you believe something should be added.

![image](https://user-images.githubusercontent.com/9698363/186901349-d42f2ed7-6e3e-4717-81dc-f5a659fc774a.png)
