### ISSUE TITLE
Job listing for Community Manager

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#152]
## 🎉   Subtasks

- [x] Write draft (can use format & some content from https://commonsstack.org/open-positions)
- [x] Get feedback
- [x] Publish on wiki

## 🤼‍♂️   Reviewer

@GriffGreen - can you also tell us, based off our roadmap, by what date/milestone do we need to hire a community manager?

**Comment by GriffGreen** [comment]
We need this asap

**Comment by lorelei1** [comment]
Seems like this issue is complete, no?
