### ISSUE TITLE
Re upcoming commons deployment clients 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1526]
## 📋   Anything to add?

Who are the candidates. Based on whether the community rep stated their willingness to pay for this service and ballpark figure of how much and our own experience in interacting with the group.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Filtered list for future clients: https://docs.google.com/spreadsheets/d/1wrwfWhPbNdv23CuebUemxw7PQTsqrSyMaErKoZafBAI/edit#gid=1174112983

**Comment by tamarandom** [comment]
Update: @usama9500 will draft a message and timeline for sending.

**Comment by usama9500** [comment]
Created a Trello board for our Commons funnel: https://trello.com/b/jt58qWUH/commons-product-sales-funnel

**Comment by usama9500** [comment]
This is done, we have created a list of clients and are managing them on Trello board.
