### ISSUE TITLE
CS Newsletter (special edition)

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1565]
## 📋   Anything to add?
https://docs.google.com/document/d/1tU93dgmO1KgQsDzfKom0o660sf3myYdXyj6h33HHvPw/edit?usp=sharing 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Moved to Notion: https://www.notion.so/giveth/cd9c192e0b38432fab668a578a06add9?v=1d2ba0b1c5b249f8bd27386519cc942b&p=fdfdbdec0be8453ba4ac163f5c0097c2&pm=s
