### ISSUE TITLE
Commons deployments as a service - getting the word out this Sprint! 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1570]
## 📋   Anything to add?

In the beginning of Nov, we are announcing we will offer a service to deploy Commons for communities. Between now and then we should be reaching out to communities that we think might be good candidates for Commons. Who will really benefit from deploying a Commons? 

https://trello.com/b/5KM2I6Y9/commons-product-sales-funnel

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
![Screen Shot 2022-10-25 at 8.53.08 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/97e3acdf-67ff-4372-a6a3-ee4d0b850603)
