### ISSUE TITLE
Quick Newsletter to Push Donations for CSTK CV matching experiment

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#158]
## 📋   Anything to add?
A quick CTA for our email subscribers as to how to GET & USE CSTK tokens in our latest CV experiment.

## 🎉   Subtasks

- [x] Get Mailchimp login from Lorelei
- [x] Draft newsletter & review @jessicazartler @liviade1 
- [ ] Publish newsletter

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
N/A

**Comment by jessicazartler** [comment]
@GriffGreen @liviade1 @lorelei1  Jeff and I put together a WIP rough template for the newsletter in Mail Chimp — just sent you the TEST email. 

Let me know if you got it  —  can edit the content this was just an example. Fix the content and send by this Wednesday would be ideal to wrap CV according to chats with Griff.. 

From there this can be the template for a monthly newsletter going forward if you like it..

**Comment by lorelei1** [comment]
Integrating final feedback & will be sent out this week.

**Comment by jessicazartler** [comment]
Test emails sent to @GriffGreen @lorelei1 waiting for Griff results & final thumbs up - ready to send
