### ISSUE TITLE
Update CS project on Giveth

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1580]
## 📋   Anything to add?
Update this every quarter using the same updates we are giving in the newsletter, but shorter

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen

**Comment by GriffGreen** [comment]
@iviangita its not ideal to transfer the project, can you give me the text to update with and i will add it?

**Comment by GriffGreen** [comment]
I think we are updated now
https://giveth.io/project/commons-stack
