### ISSUE TITLE
Tamara's Self and Peer Review

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1581]
The Commons Stack is organizing this self and peer review exercise to gather feedback from you about yourself and your teammates. 

The documents in which you should write your reviews have already been created for you (tamara.helenius@gmail.com) and shared with the people who need to have access. 

All you have to do is fill out the document and notify when you're done.

**Self-review:**
[Your self-review document](https://docs.google.com/document/d/10L4JewnLG911FBd2_-2cFYBoYNGiBunqd5iZ6bQzLCw/edit#heading=h.knq2eobpzpox)

**Peer review:**
Here are the people you are reviewing. Separate documents have been created for each person. Access the documents by clicking on their names

- [x] [Griff](https://docs.google.com/document/d/1J1x0QUQRIkKQuOAelDiomCOPeJPkfOqs88watFryp1w/edit)
- [ ] [Livia](https://docs.google.com/document/d/140waM7D3vVeHcbak8on3cCGGeL176tZAW4lNDxHbxXc/edit)
- [ ] [Usama](https://docs.google.com/document/d/14-mcpsAA9mpl1CcOoXmdViFCmx4Y5yvpoBrrLvxJxPE/edit)
- [ ] [Ivy](https://docs.google.com/document/d/1wD4QdLuv-WHlSwJ1GTLuoIYzSwY9vyygKykS0cVo0Po/edit)
- [ ] [Rachael](https://docs.google.com/document/d/1IQNs7pcmT_b-oUbAWODWzdCnH4uyS_9vUPHX8pycSs0/edit)
- [ ] [Emilia](https://docs.google.com/document/d/1erVgEBtwiRBYp9lwqEYA6ZEPdpQN47ypFID94FPYZ_I/edit)

**Additional Information**
Because you are a feedback giver, you have access to a folder containing the self and peer reviews of other teammates. Ownership rights have been transferred to you (tamara.helenius@gmail.com) for the folder itself and every document contained therein. Please accept all ownership rights in order to restrict unauthorized access to these documents.

- **To accept ownership of the folder:** open the folder > click on the “view details” icon on the upper right-hand corner > click on manage access and accept ownership
- **To accept ownership of a document:** open document > click on the “Share” icon and accept ownership

**_Please note that only the reviewer and you should have access to any particular document._**

[Take me to the folder](https://drive.google.com/drive/u/0/folders/1q8zGoYubha7Bq8y3bXdCN2-lYqvt9lCk)

**Comment by tamarandom** [comment]
Closing! Moved to notion. Also all done except one last one!

**Comment by tamarandom** [comment]
Closing! Moved to notion. Also all done except one last one!
