### ISSUE TITLE
Usama's Self & Peer Review 

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1585]
The Commons Stack is organizing this self and peer review exercise to gather feedback from you about yourself and your teammates.

The documents in which you should write your reviews have already been created for you (usama.ahmed95@gmail.com) and shared with the people who need to have access.

All you have to do is fill out the document and notify when you're done.

**Self-review:**
[Your self-review document](https://docs.google.com/document/d/19Y3MF2R8J3gETsXahdYQMzm9DBcznPfl4giwVbBJSmg/edit?usp=drivesdk)

**Peer review:**
Here are the people you are reviewing. Separate documents have been created for each person. Access the documents by clicking on their names

- [ ] [Tamara](https://docs.google.com/document/d/1_UdCEuSOX2TSCs5VXdNeQy7GnvUfvusouPVibHaQyaM/edit?usp=drivesdk)
- [ ] [Ivy](https://docs.google.com/document/d/1cnQrobhB_zwRVTAhY7tJobrLsR-UwMxyYbuiwhiyrZU/edit?usp=drivesdk)

**Comment by usama9500** [comment]
Closing
