### ISSUE TITLE
Support 1Hive in their emergency cultural build

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#161]
## 🎉   Subtasks

- [ ] Talk to Luke and the TE Community Stewards
- [ ] Make a plan
- [ ] Recrute a team
- [ ] Execute

## 🤼‍♂️   Reviewer

@liviade1

**Comment by jessicazartler** [comment]
@GriffGreen @liviade1 shall we close this? They have a lot of people working now for them on comms and lots of action in their forum.. I will join one call with some of those folks to help provide some context as they are all pretty young and are more DeFi oriented.. and Luke is hardcore decentralist and says it must come from community. For now, it's just kind of documenting some of the processes as I mentioned and watching as they iron things out.. I think they also graduated people to moderators and have a bit better flow seemingly...
