### ISSUE TITLE
Build our xDAI DAO!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#19]
## 📋   Description
The gas fees are stupid on Ethereum... time for a change. Let's move our DAO to xDAI

## 🎉   Definition of done

- [x] Create the initial team (Livia Griff Lorelei? Gustav?)
- [x] Create set of Requirements
- [x] Show to Luke
- [x] Set up a call with Luke/1Hive about what is possible, probably removing some requirements
- [x] Work with 1Hive to do the tech part
- [x] Smother 1Hive with praise
- [x] Consider changing the CSTK token to TST = Trusted Seed Token
- [x] Issue xDAI CSTK tokens to all CSTK Token Holders
- [x] Get Conviction Voting TCR version up on the DAO
- [x] Test Conviction Voting Parameters to ensure they are set right and redeploy if needed
- [x] Write a quick blog post, that also acts as an onboarding guide for the DAO
- [x] Use our Panvala Cluster as a first thing to vote on 

## 🤼‍♂️   Reviewer
Trusted Seed :-D

## 🔗   Links
Our CSDAO: https://aragon.1hive.org/?#/csdao/0xaa89fb730a83146cbf06661fd436e7445b4d0232/

**Comment by lorelei1** [comment]
I just changed this to be a part of the current milestone. I'd like validation on that move! (Seems like this is a blocker to Milestone 2's goals)
