### ISSUE TITLE
ABC Explainer Article

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#20]
## 📋   Description
High-level explainer article for the ABC.

## 🎉   Definition of done

- [x] Rough draft submitted for review to CS Comms channel.
- [x] Kris to review by Wednesday 12/08
- [ ] Comments & feedback integrated.
- [ ] Publish to Medium.

## 🤼‍♂️   Reviewer

@krrisis 

## 🔗   Links
https://docs.google.com/document/d/1aHVI_tyhVBETttblDOjvIIR-XW4LPDwcstvXDe2l_y4/edit?usp=sharing
https://www.notion.so/ABC-Article-691407820fad4259ade3fa54d203a8d3

**Comment by jessicazartler** [comment]
@krisjpi @Jeff-Emmett We decided this will become a TEC hatch article instead? Just wanted to document here and also added to the content production/distribution epic - thanks!

**Comment by krrisis** [comment]
Still deeply hope that the current draft - which is in a pretty progressed state (made a proposal for a simple cut-down version at the top of the doc - could become a simple ABC explainer. We don't have this. So even if the Commons Stack never initiates the build itself through partners (hope it will though), a clear, concise & simple explainer (like we have for conviction voting) that doesn't mix it with running initiatives can be super valuable ànd inspiring to others (as the CV article clearly has been - still gets shared loads). 
A TEC hatch article is definitely useful but this could come into existence separately from this (or steal chunks from the original, longer version lower in the doc). 

Anyways, just once more my thoughts, from far away, haven't been involved in recent discussions, so whatever makes sense, go for it :)

**Comment by krrisis** [comment]
Ps. logically 100% available to review a further/final draft, I outlined the initial structure for that explainer already in feb 2020 (in this doc & comms notes) after chats w/ jeff & griff, so wouldn't mind reviewing final version if we ever get there. 🤞

**Comment by krrisis** [comment]
Pps. to be able to one day answer great twitter Qs like these by just linking to it :) https://twitter.com/krrisis/status/1329879875784675328?s=20

**Comment by jessicazartler** [comment]
https://docs.google.com/document/d/1aHVI_tyhVBETttblDOjvIIR-XW4LPDwcstvXDe2l_y4/edit

**Comment by tamarandom** [comment]
Tagging @danelsuga in case she can be of help as editor on any of this.

**Comment by Jeff-Emmett** [comment]
Hey @danelsuga, feel free to read through this (very old) draft to get a feel for some of the deeper facets of the ABC - there will be a piece in the works in the coming weeks somewhat along these lines, but also with some recent updates and newer diagrams that surfaced during the Crypto Commons Gathering over the last month.

Feel free to ping me when you get a chance to read through this and we can discuss some next steps!

**Comment by danelsuga** [comment]
Awesome @Jeff-Emmett! Thanks! Will get to it asap.

**Comment by tamarandom** [comment]
Hey @jessicazartler The three articles we discussed are being tracked in Epic #1061. Is there any reason to keep this issue open?
