### ISSUE TITLE
Network Collaboration: Generalized Bonding Curve Model 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#206]
## 📋   Anything to add?
Working towards a network collaboration with Block Science, Curve Labs, 1Hive, cadCAD, Interchain Foundation?, IXO? 

## 🎉   Subtasks

- [ ] Jeff talk to the groups and setup up some calls with stakeholders to initiate
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen

**Comment by tamarandom** [comment]
Hey @jessicazartler @Jeff-Emmett @krisjpi is this an epic? Or a simple issue? Still relevant or should it be refined or closed?

**Comment by jessicazartler** [comment]
This is definitely an epic on the backlog... we do not have the resources for this for at least a few months and this will be a huge research project that will require coordination, PM, fundraising, research & documentation. To be discussed for R&D when some bandwidth opens - would likely be a 1-3 month project.

**Comment by jessicazartler** [comment]
@Jeff-Emmett Shawn and Sem worked on this - I am going to close for now :D
