### ISSUE TITLE
Blog: How CS & TEC are connected, Engaging with the TEC from CS perspective

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#207]
## 📋   Anything to add?
We need to tell the story of how CS & TEC are connected and have a bit of a push to engage the CS and Trusted Seed to get more involved in TEC. Will write a blog so we can post around and Livia and Jess can engage community.

## 🎉   Subtasks

- [ ] Find a Champion

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links

PREVIOUS PIECE:
https://docs.google.com/document/d/1ZVDBSud_xdNxK4ZRUo-bmjbAn9vlGW5pGZgb3i0OF6k/edit?usp=sharing

**Comment by jessicazartler** [comment]
I have a draft that went a bit in a different direction haha gonna circle back on this next week with a fresh brain

**Comment by jessicazartler** [comment]
@krisjpi wondering your thoughts.. thank you!

**Comment by tamarandom** [comment]
Backlog refinement. Closing out these old issues.
