### ISSUE TITLE
TEC Blog: Praise Quantification Oct. 24 - Nov. 6 #17

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#216]
## 📋   Anything to add?
CC from TEC https://github.com/TECommons/Coordination/issues/17

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Great work @jessicazartler 🎉 
https://medium.com/token-engineering-commons/your-economy-your-choice-64e8151a1ecb
