### ISSUE TITLE
Strategy for CS contributors 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#217]
## 🎉   Subtasks

- [ ] scope out a few strategies for onboarding contributors to Commons Stack issues
- [ ] share with the team for feedback
- [ ] implement strategy 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
Suggestion from Griff
i think we need one person negotiating payments with clear guidelines... Here is my crack at it: 
1. Everyone gets paid 19 DAI an hour if they want pay
2. Everyone is trusted to track their own hours... we have had a lot of success with assigning one person to cat herd everyone to fill in their hours... ideally this would be on a weekly basis... like every friday, someone goes around and chases all our contributors down to get them to put down their hours 
3. They can choose to get 50% pay and 50% IH and CSTK or only IH and CSTK which would be lavishly slathered on them if they work for just those.
4. The work must be attached to a github issue with a reviewer
5. The reviewer is someone deep in the game (Jess yes, but not new Kris, Tamara or Comms #2, not for a month at least)
6. The reviewer is their buddy and onboarder and main point of contact for that issue.
7. That issue should be added to our weekly sprint

**Comment by liviade1** [comment]
Suggestions from Griff 
i think we need one person negotiating payments with clear guidelines... Here is my crack at it: 
1. Everyone gets paid 19 DAI an hour if they want pay
2. Everyone is trusted to track their own hours... we have had a lot of success with assigning one person to cat herd everyone to fill in their hours... ideally this would be on a weekly basis... like every friday, someone goes around and chases all our contributors down to get them to put down their hours 
3. They can choose to get 50% pay and 50% IH and CSTK or only IH and CSTK which would be lavishly slathered on them if they work for just those.
4. The work must be attached to a github issue with a reviewer
5. The reviewer is someone deep in the game 
6. The reviewer is their buddy and onboarder and main point of contact for that issue.
7. That issue should be added to our weekly sprint

**Comment by GriffGreen** [comment]
This issue is very similar to #162 #209 #217 #242 and #224 

We need to clean this up!!! :-D

@knobsDAO I'm calling on you for this!

**Comment by jessicazartler** [comment]
Merging with https://github.com/commons-stack/iteration0/issues/209
