### ISSUE TITLE
TEC Soft Gov: Automated Options for Onboarding & Rewards Systems Documentation (cadCAD/CS)

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#219]
## 📋   Anything to add?
CC from TEC https://github.com/TECommons/Coordination/issues/14
## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/16fZG4QJycKDTGrJAKWT-caflBE3g53o1L2k64ztIlZM/edit?userstoinvite=liviaieaou%40gmail.com&ts=5f9a0367&actionButton=1

**Comment by tamarandom** [comment]
Moved to [TEC repository](https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/tecommons/coordination/203) & closed.
