### ISSUE TITLE
Write a great email that invites our Applicants to contribute to TEC and CS

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#222]
## 📋   Anything to add?

We hired our people... but all our applicants are likely to be huge contributors if we do things right!

## 🎉   Subtasks

- [ ] Find a champion 
- [ ] Write the emails 
- [ ] Send it out

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@GriffGreen @knobsdao This is done, right? Close now?
