### ISSUE TITLE
Develop a coordinated plan & schedule a call with the Trusted Seed?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#224]
## 📋   Anything to add?

From comms call nov 9th

## 🎉   Subtasks

- [x] Find a Champion
- [ ] Make a plan here

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

Comms Notes
https://docs.google.com/document/d/1k8Lw-s9WNqxOMLLesxi4XcC9gz8irkwY-F8AKtayoMY/edit?usp=sharing

**Comment by GriffGreen** [comment]
This seems like it should be combined with #143 and #242 help me out @krisjpi and adjust these issues

**Comment by jessicazartler** [comment]
15min presentation + questions AMA
Sprint 5 --- (Next Friday start)
