### ISSUE TITLE
High level narratives exercise for the Commons Stack

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#225]
## 📋   Anything to add?

From comms call nov 9th, also would be great

## 🎉   Subtasks

- [ ] Find a Champion, potentially Edu Vegas... !
- [ ] Make a plan here

## 🤼‍♂️   Reviewer

@Jeff-Emmett

## 🔗   Work doc - inspirational links

Comms Notes
https://docs.google.com/document/d/1k8Lw-s9WNqxOMLLesxi4XcC9gz8irkwY-F8AKtayoMY/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
I put a few thoughts on my view of future CS narrative into this document.  Open to discuss as it becomes a priority:

https://docs.google.com/document/d/1buAPUNGMyHe3gAV2yD9gm8vgRkD6NbteppSMcIdEBiw/edit?usp=sharing
