### ISSUE TITLE
Improve the Typeform

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#228]
## 📋   Anything to add?
Ask for LinkedIn, Github, and Twitter accounts

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by knobsdao** [comment]
A comment was made to review if allowing only 0x addresses as a reply was possible under the relevant question.

**Comment by knobsdao** [comment]
Can we allow people to edit their replies?

**Comment by liviade1** [comment]
Using this document from before that is still relevant https://docs.google.com/document/d/1SxjROeFTXy9n6ZZrEcEA_t-PySiop5plaYXTcNV_uyo/edit#

**Comment by knobsdao** [comment]
Note: For the praise accounting process, we will need to start collecting Discord handles.

**Comment by GriffGreen** [comment]
Let people request a call! - Jess
