### ISSUE TITLE
Set up Templated Agreements for Partnerships

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#232]
## 📋   Anything to add?
Creating some agreement templates for project partnerships and regularly occurring process entry flows would simplify 

AGREEMENT TEMPLATE / FILING
Mission alignment / social agreement aspects -- shared purpose
Code of conduct "what is not cool to do with our name"
Making sure we have 2 separate agreements for CS / TEC

## 🤼‍♂️   Reviewer

@knobsdao @Jeff-Emmett @krisjpi 

## 🔗   Work doc - inspirational links
AGREEMENT TEMPLATE WE STARTED https://docs.google.com/document/d/1V7KhUyyFbz_UBJoAM_xeJhC6D0qpvz8ufI5TzihxXfA/edit

**Comment by Jeff-Emmett** [comment]
Awesome Kris, thanks for starting this up!

Also love the reference: https://www.youtube.com/watch?v=tO5sxLapAts 😂

**Comment by jessicazartler** [comment]
Refreshed template https://docs.google.com/document/d/1RQeZYYpeQT9qU4CByT7zf1pQ6UHeXAZ7JhO268Ji-_8/edit
