### ISSUE TITLE
Watch CSTK token dapp receiving address for donations we should reject

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#234]
## 📋   Anything to add?

This is for the Association to make sure that the accounting is easy for membership fees

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Part of Owning CSTK Token Distro #229  and CSTK DApp #2

**Comment by tamarandom** [comment]
closing.
