### ISSUE TITLE
Create a strategy and execute on sharing our review calls

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#239]
## 📋   Anything to add?

We had a review call: https://youtu.be/eAynpm5692A

We could just share it in the Trusted Seed channel... but maybe we should think about it? Maybe we just share it now and then  have a more complete plan for next round?

## 🎉   Subtasks

- [x] Comms Call
- [x] Find a Champion
- [x] Develop a plan
- [x] Pass it by Kris, Griff, Dan
- [x] Execute the plan

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
#8

**Comment by GriffGreen** [comment]
Sprint 4:
https://youtu.be/675QjO_aat0

**Comment by GriffGreen** [comment]
It should be public!

**Comment by GriffGreen** [comment]
Should it be in twitter?

**Comment by GriffGreen** [comment]
Loop in Zep

**Comment by GriffGreen** [comment]
Make a template

End all thought requirements

**Comment by tamarandom** [comment]
Ivy readied the last Sprint Review! Here: https://www.youtube.com/watch?v=675QjO_aat0
Kris, Dan - going to pass this to you for final review & edit, if need be. 

Next one will be next Wed. The [Process is very straightforward :
](https://docs.google.com/document/d/1KDNEYsV4O-6Mm64w_MgpWg2uBNI3SWC2JG49IRmU3oE/edit?usp=sharing)
Before the call : 
(Ivy) Day before the call, remind CS team to list the items to be reviewed to the Review Agenda (this doc!) 
(CS team) Add description to be used  the final video ← this will ensure Ivy has the correct wording when she adds video timelines.

During call :
(Griff) Recording on zoom & upload as unlisted to youtube

Day after the call :
(Ivy) Add title, description, timelines & pass to Kris 
(Kris) Final review, edits if need be and publish 
(Dan) Execute your communication plan for sharing this with Trusted Seed ;)
