### ISSUE TITLE
Execute on what we want to do with recurring tasks 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#244]
https://github.com/imjohnbo/issue-bot
^^^ This looks cool

- [ ] do some googling 
- [ ] pick a strategy
- [ ] make a new better issue covering it's execution

**Comment by GriffGreen** [comment]
if you go the bot route... talk to @krisjpi

**Comment by tamarandom** [comment]
Had a look at the issue-bot. It's pretty straightforward, a cronjob that creates new issues of specific templates. It can work. 

Whichever solution we use, we'll need to input the repeating tasks.  This is an [editable xls](https://docs.google.com/spreadsheets/d/1buTGGYel7GBfVP-GdTF8ldCZaKSJVqD_0v5V2ZcBrTw/edit?usp=sharing) so all can add the ones they have in their working groups and workstreams. 

Having this list should also provide additional insight for what solution will fit best.

**Comment by GriffGreen** [comment]
<img width="1157" alt="Screen Shot 2020-12-05 at 9 42 37 AM" src="https://user-images.githubusercontent.com/14945613/101245967-a5775e00-3710-11eb-8fdb-e2c168fc6ae3.png">
From
https://hewlettpackard.github.io/yoda/Yoda-Agile-Project-Management-with-GitHub.pdf

I wonder if the zenhub guys have any suggestions... 

I couldnt help myself and made a comment here: https://portal.productboard.com/zenhub/1-zenhub-s-roadmap/c/100-issue-and-metadata-automation?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImdyaWZmQGdpdmV0aC5pbyIsImlhdCI6MTYwNzE3OTc4NSwiZXhwIjoxNjA3MjIyOTg1fQ.yzXPhb4cmvETjIrM6l9QvaKI8fywnr0R2aGDS-WM4Aw

**Comment by tamarandom** [comment]
Repeating tasks <-- start tagging!
#repeating : monthly
#repeating : weekly
#repeating : sprint

The last thing I want to look at is an issue template that can't be closed.

**Comment by tamarandom** [comment]
![done.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/4dc2335d-3dc5-4937-b470-deb92debfe42)
