### ISSUE TITLE
Help take Giveth Twitter Over

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#246]
## 📋   Anything to add?

Dani wants to hand over tweeting... we need help!

## 🎉   Subtasks

- [ ] This sprint will be an investigation... So first we investigate! 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
@krisjpi I will get in touch with Giveth credentials for sign in --- then please ask Dani in Public Goods twitter collective channel what she would like us to do - thanks!

**Comment by jessicazartler** [comment]
@krisjpi how is this going? Were you able to get in touch with Dani?

**Comment by jessicazartler** [comment]
Dup #171 Magenta taking over - closing
