### ISSUE TITLE
Giveth Payments and Milestone Creation

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#250]
## 📋   Anything to add?

This is an admin task that we need to stay on top of... Making sure people get paid!!! GRIFF NEEDS HELP!!

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
All the issues in the Epic are closed. Closing it down too.
