### ISSUE TITLE
Establish a D2D partnership template for the communities related to Commons Stack

### ISSUE THREAD

**Issue by Zion-code** [commons-stack/iteration0#288]
## 📋   Anything to add?
After working on the PrimeDAO ambassador partnership proposal, it became clear that a great standardized partnership template would benefit the growing decentralized communities such as Commons Stack, Token Engineering Commons and Giveth and accelerate the overall process.
## 🎉   Subtasks

- Research known partnership processes and templates [ ] 
- Join the onboarding WG and Dispute WG meetings collecting insights & ideas[ ] 
- Create a template based on the findings of the above tasks[ ] 

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen @tamarandom @jessicazartler @Jeff-Emmett 

## 🔗   Work doc - inspirational links
Started a working document [here](https://docs.google.com/document/d/12mXCA6vaL7qE1OL1xvmWGlwHx77S3pdevxFlirAlhsg/edit?usp=sharing).
Great source about DAO fractalization: https://ecosystem.daoincubator.org/fractalizing/fractalization-process
Partner Collaboration doc from an event planned in a decentralized way and emphasizing shared values first, authored by Extinction Rebellion: https://docs.google.com/document/d/1_ToJI-qgLN_zzcqw0KbDvuY1Q1Y9yLAEInC6qD57QvQ/edit

**Comment by jessicazartler** [comment]
Establish a D2D partnership template for the communities related to Commons Stack #288
       Name the partnerships ecosystem i.e. "alliance" "alliance for prosperity" "
       Defining what we can offer/accept
       Agreement Template (Hello Sign)
       Media template - media assets / guidelines / press release
Create a tracking doc ---> Hubspot
       Assign relationship managers
Webpage for partners / typeform


**---NOTES---**

**CURRENT FLOW**
Projects come to Jeff/Jess/Livia/Griff whoever - need process

**LIST**
Create tracking list - kame spreadsheet DIFFERENT tabs / Hubspot

**INBOUND PROCESS**
Website submission
CSTK Token Dapp - Partnership option/section - Benefits: access to potential airdrops

**OUTBOUND** LATER ITERATION
Email campaign for calling for a CS/TEC alliance call out

**EXCHANGE** 
-What are we offering?
Logo swap on websites
Network
Channel in Discord
Other promos (newsletter)
Social media sharings
CSTK tokens? For ambassadors

-What can we accept?
Tokens
Logo/promo opps

**AGREEMENT TEMPLATE / FILING**
Mission alignment / social agreement aspects -- shared purpose
Code of conduct "what is not cool to do with our name"
Making sure we have 2 separate agreements for CS / TEC

**Comment by jessicazartler** [comment]
NEED ISSUES:
        Name the partnerships ecosystem i.e. "alliance" "alliance for prosperity" "
       Defining what we can offer/accept
       Media template - media assets / guidelines / press release

DONE:
       Agreement Template (Hello Sign) -- Set up Templated Agreements for Regular Processes#232

**Comment by jessicazartler** [comment]
@Zion-code Hey there :D Just wanted to offer some experience from working on partnerships for CS ...  I would say it is somewhat challenging to do a generalized template for partnerships as each is VERY different... I do have two agreements that you can have that I did with Regen Network/Seeds and I also have one I did for ixo though it was in a landing page / announcement format.. happy to send those along and share experience if you'd like - nice initiative!

**Comment by tamarandom** [comment]
@jessicazartler yep, each partnership is very unique. At this stage, a partnership template is not feasible. 

Cleaning up the backlog and going to close this now.
