### ISSUE TITLE
Creat a hatching phase diagram

### ISSUE THREAD

**Issue by Santigs** [commons-stack/iteration0#298]
## 📋   Anything to add?

So we we can use to discuss in the legal WG sessions

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

https://www.canva.com/design/DAEOXnY9VGA/T9rgwhirQ9spmYyLRTPa4A/view?utm_content=DAEOXnY9VGA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by tamarandom** [comment]
Moved to the TEC repo.
