### ISSUE TITLE
Get Statutes reviewed by Raph

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#3]
Finalize the actual legal work for the big moves!

**Comment by Kisgus** [comment]
Please specify this issue further @GriffGreen

**Comment by GriffGreen** [comment]
passing the buck to @lorelei1

**Comment by lorelei1** [comment]
Coach B will have a look at the T&Cs and Statutes to make sure they don't contradict one another, and then make an estimate for how much budget we need to set aside for lawyers once he has an idea of how many edits there are to make.
