### ISSUE TITLE
Set dates for Greaterthan workshops 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#301]
## 📋   Anything to add?

Related to issue #243

(snippit from Kate's email below)

This means it will be in the week starting the 7th Dec that we could run the first workshop? I will leave it to you to tell me the best time that suits you all and I will make myself available (I just can't do Monday nights).

## 🎉   Subtasks

- [x] Set dates for 2 x 2hr workshops starting from week of Dec 7th 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
Suggested date for the second workshop - January 11th
