### ISSUE TITLE
Check-in with PrimeDAO 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#306]
## 📋   Anything to add?

Partnership with Commons Stack & PrimeDAO!

## 🎉   Subtasks
-[ ] Are there actions to take as CS Ambassador to PrimeDAO
-[ ] If this is a voting cycle, the vote! If not, just say hi.

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

[How to doc for this ](https://docs.google.com/document/d/1NAu_RqnG8o5M768xB8HpDM1zt-vDT0vq8TxPWQ1IUeA/edit#)

**Comment by tamarandom** [comment]
Had a good sync with Pat and Ruben last week.

**Comment by tamarandom** [comment]
Done! Voted in the last voting round.

**Comment by tamarandom** [comment]
Good for this Sprint!

**Comment by tamarandom** [comment]
Update : 
March 2 : Debrief Cycle 3
March 8 : Kick off Cycle 3

**Comment by tamarandom** [comment]
Update : 
March 2 : Debrief Cycle 3
March 8 : Kick off Cycle 3

**Comment by tamarandom** [comment]
Spontaneous check-in with Luuk and he shares his thinking of an ecosystem wide sync-up in 2-3 weeks. 
Other than that, no new announcements for voting cycles.

**Comment by tamarandom** [comment]
Luuk and I will have a sync this week. Looking to make it regular on a bi-weekly or monthly basis.

**Comment by tamarandom** [comment]
Had a good sync and will have a regular bi-weekly with Luuk going forward. 
They are now setup on Boardroom: https://app.boardroom.info/primedao/proposals
The **Proposal Inverter Spec and Model - TEC Labs Collaboration** should soon be up for vote on PrimeDAO, which includes Commons Stack as advisors. 👍🏽
https://docs.google.com/document/d/135ZH2AByCU7cmXbG501Cu4Xl8LgMcJiHpb_-XzhNlzY/edit

**Comment by tamarandom** [comment]
Had a sync with Luuk. PrimeDAO is heads down building (see the projects they are launching in the updates below). The figmas are looking pretty great. He is really interested in talking with @GriffGreen about Celo and regenerative projects flocking to the same chain. Targeting Jan for that convo - after Giveth and TEC have reach their next HUGE milestones. 

Updates on PrimeDAO:
- 5-6 new contributors 
- About to go live, 4-6 weeks, PrimeLaunch, PrimeRating, PrimePool
-New website launched, 
- Launching PrimeDeals in Q1
- Also working on proposal inverter

**Comment by GriffGreen** [comment]
Sweet! Yeah we are committed to xDai with mainnet presence for launches but in no way is Giveth or CS xDai/ETH Maxis

**Comment by tamarandom** [comment]
Closing this issue for good. Am periodically checking in with PrimeDAO.
