### ISSUE TITLE
Readme description

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#32]
## 📋   Description

Intro to what this entire board is about :)

## 🎉   Definition of done

- [x] Proposal by Kris
- [ ] Review by Gus

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Links

https://github.com/commons-stack/iteration0/blob/master/README.md

**Comment by Kisgus** [comment]
Looks pretty good to me, is it okay I put in some pictures like logo etc @krrisis ?

**Comment by Kisgus** [comment]
Looks good, good job, sorry for the late review :)
