### ISSUE TITLE
Finish bridging Telegram to Discord csddev, and other channels still missing

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#323]
## 📋   Anything to add?

(carry over from #242)
Dan to provide more details, if needed. 

## 🎉   Subtasks

- [ ] figure out what channels are missing
- [ ] link 'em
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by krisjpi** [comment]
Comms and CS dDev are now connected to Discord!
