### ISSUE TITLE
PrimeDAO vesting contract 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#328]
## 📋   Anything to add?

Few things to do here, when time/priorities permit. (thanks Ruben for putting this on my radar!)
https://docs.primedao.io/primedao/tokenomics/roles-and-rewards/vesting-contract-guide

It looks like this can only be done after the Prime DAO launch : 

"6) From PrimeDAO’s mainnet deployment, create a proposal that sends PRIME to the vestingContractAddress. Once passed, the PRIME should transfer, and vesting will begin."

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Submitted but pending .... will keep checking or raise gas to speed things up. 
https://etherscan.io/address/0x9a75944ed8b1fff381f1ebf9dd0a75ea72f75727

**Comment by Zion-code** [comment]
This is your vesting contract adress?

**Comment by tamarandom** [comment]
Hi @Zion-code! It is the "TokenVesting Factory contract on Etherscan" from this [doc](https://docs.primedao.io/primedao/call-for-contributors/proposal-payment-protocol/vesting-contract-guide).

**Comment by tamarandom** [comment]
Pat proposed a social solution ([post on DAOtalk](https://daotalk.org/t/primedao-social-vesting-contact-commons-stack-ambassador/2499
)) until gas prices cool down. Will leave this issue open until the vesting contract is actually created on the main net.

**Comment by Zion-code** [comment]
This issue is closed, right? or will it stay open for the vesting period (which is one year)

**Comment by tamarandom** [comment]
Hey @Zion-code ! It's still open. I have to post the new social contract on DAOTalk for this recent voting period.

**Comment by tamarandom** [comment]
Some issues feel better than others to close! This one FEELS GREAT! 

"Social vesting" : (I also posted in their Discord to get feedback on it)
https://daotalk.org/t/primedao-social-vesting-contract-for-pinc-reward/2579

How to doc : 
https://docs.google.com/document/d/1NAu_RqnG8o5M768xB8HpDM1zt-vDT0vq8TxPWQ1IUeA/edit#
