### ISSUE TITLE
Video introduction 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#34]
## 📋   Anything to add?

Limitations to add to livestream
How to implement in our process?
Add audio at a later date

## 🎉   Subtasks

- [ ] collect feedback 
- [ ] debrief designer
- [ ] delineate process to start using
- [ ] Sonic logo with Josh -> kris to brief

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

https://drive.google.com/file/d/17emrgi2S0B2vVBxPLs3OmWJU7n5N_9vI/view

**Comment by jessicazartler** [comment]
I can easily add audio to this if we want - fast edit
We should use this on all of our videos  -- I suggest title slide of "Trusted Seed Spotlight" or "Research Roundup" followed by this main intro - thoughts?

**Comment by tamarandom** [comment]
This issue still kicking?

**Comment by jessicazartler** [comment]
I would say it is finished -- you can see it at the beginning of this video 
https://www.youtube.com/watch?v=CSWCDbrOeXA&feature=youtu.be

I would upload the file here but the file type isn't supported, here is the GIF version

![CS Gif](https://user-images.githubusercontent.com/43972522/102099575-6a52ea00-3df6-11eb-940f-e1512d892370.gif)
