### ISSUE TITLE
Distribute the CV blog post to Telegram channels

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#340]

**Comment by jessicazartler** [comment]
💸 COMMONS STACK COMMUNITY FUND: CSTK HOLDERS ADD YOUR GRANT & VOTE 🗳

🎉 Gitcoin Grants Round 8 (#GR8!) just kicked off and thanks to Panvala, the Commons Stack Community Fund is offering additional $PAN matching for funds raised towards the community's favorite grants!

💰CSTK token holders can submit a link to their favorite grant on our Conviction Voting DAO and vote to rank their favorite grants! The top 15 grants will receive additional funds from our Panvala League Community Grant. 

⚡️Help us fund important community work!

🔖 If you need help getting PAN to donate or connecting to xdai, we have you covered: 
https://medium.com/commonsstack/commons-stack-community-fund-round-2-3919b522409a

🌈 If you are not yet a CSTK holder/member of the Trusted Seed, apply here 👉 https://commonsstack.org/apply
