### ISSUE TITLE
New github template for tasks that are For Contributors

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#344]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Banged out by @krisjpi (nice work!)

![Screen Shot 2020-12-11 at 12.24.45 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/7bde2b2e-5526-403f-990c-92f092d96188)
