### ISSUE TITLE
Tracking System for Partners

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#350]
## 📋   Anything to add?
We have a spreadsheet but would love to get it set up eventually in a CRM

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler @liviade1 @GriffGreen @Jeff-Emmett 

## 🔗   Work doc - inspirational links

BASIC SPREADSHEET UNTIL WE GET CRM SORTED
https://docs.google.com/spreadsheets/d/1t66w6CmtpPet_h12UJBbfas5dMlev98ZSFl6Xvw15-U/edit#gid=0

**Comment by tamarandom** [comment]
Update: possible to do with Hubspot?

**Comment by tamarandom** [comment]
Hey @jessicazartler I just requested access on the doc. Wondering whether we close this issue now? Is there any reason to keep it open? Maybe pass some knowledge  or details to @iviangita or @T-Rossi ??

**Comment by jessicazartler** [comment]
Hmmm.. I think the main thing was just to have some awareness & keep in touch with partners and potential needs/opportunities/exchanges.. there is a Telegram group called MetaWeavers that Peth from MetaGame and I made - added you and Ivy - as a way for the ecosystem to keep up with different projects and Peth now has an ecosystem section in his MetaGame newsletter with news from all - so I'd say that's a good place.. so yeah, I think you could close this.

**Comment by ghost** [comment]
Hey guys! @jessicazartler feel free to add me as well, maybe it's worth for me to see if there is any useful information.

**Comment by tamarandom** [comment]
Thanks @jessicazartler this is very helpful. For anyone who isn't subscribed to the Metagame newsletter, you can see and subscribe to it here: https://metagame.substack.com

**Comment by tamarandom** [comment]
Closing this now but want to make sure that @YineisyM and @iviangita are aware too. Especially because we should consider that newsletter as a channel for sharing CS big updates (like the upcoming Commons Prize contest).

**Comment by jessicazartler** [comment]
Sure and Thiago and I will meet - he's going to update me about Regen partnership - and ask me about this
