### ISSUE TITLE
GG Round 8 #2 Email Newsletter - Push Donations

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#352]
## 📋   Anything to add?

Need a 2nd email to follow up to Panvala email (Email to Commons Stack Peeps #339)
This email will focus on pushing donations

## 🎉   Subtasks

- [x] Kris draft
- [x] Jess / Kris hack
- [x] Jeff edit
- [x] Send

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen

**Comment by krisjpi** [comment]
Drafted, hacked, edited, and scheduled. Closed!
