### ISSUE TITLE
Metagame Partnership

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#353]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen @Jeff-Emmett @liviade1 

## 🔗   Work doc - inspirational links
https://wiki.metagame.wtf/docs/enter-metagame/guilds-of-metagame

**Comment by tamarandom** [comment]
Hey @jessicazartler @knobsdao What do the nest steps on this look like?

**Comment by jessicazartler** [comment]
Actually I was going to bring this up in the meeting - I think @Jeff-Emmett @GriffGreen had mentioned this at some point, but I don't remember if there was a particular opportunity/context.. we can kind of have a call and tap in at anytime... many of them are in the Trusted Seed already...

**Comment by GriffGreen** [comment]
SEED Airdrop ;-)?

**Comment by tamarandom** [comment]
When I go to this link above, I see Commons Stack is listed as one of the guilds now. Is there any other actions required for this issue? Is there any reason not to close this issue now?

![Screen Shot 2022-03-10 at 1.54.44 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/aca4f9c1-340f-4476-8452-8144c0ca4765)

**Comment by jessicazartler** [comment]
Griff had the idea to ask them for a Seeds drop.. if you are still interested you could speak with Peth at MetaGame to see if this is a possibility but I know they're fundraising so they don't have so many funds.. perhaps if CS could give a donation OR maybe they would do it for CSTK but not sure.. up to you all if you think that's worth asking - otherwise, you can close this - thanks!

**Comment by tamarandom** [comment]
Ah that is interesting. Let's leave it open so we don't lose track of the idea.

**Comment by GriffGreen** [comment]
I spoke with PETH about the seeds drop and he said no go as seeds can only be earned... but he is going to launch $TREES so there might be something there... but it will probably be more like trusted seed can contribute funds as opposed to an airdrop

**Comment by tamarandom** [comment]
OK. Tagging this Trusted Seed and looping in @mafer-cordovas and @MaxSemenchuk. Will leave open so it stays in radar even though we probably won't act on it in the short term.

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/57
