### ISSUE TITLE
A deep dive into onboarding more people into Praise bot

### ISSUE THREAD

**Issue by freedumbs00** [commons-stack/iteration0#355]
## 🎉   Subtasks

- [ Find a Champion] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://forum.tecommons.org/t/praise-quantification-update-and-proposals/144

**Comment by knobsdao** [comment]
@tamarandom should this issue be -or is it already- in the TEC board?

**Comment by tamarandom** [comment]
@knobsdao good question!  @freedumbs00 I'm looping you in as you opened this. This call for a deep dive can be closed now, right?

**Comment by freedumbs00** [comment]
I didnt open this..  I didnt know it was here.  We have had great onboarding in the last two months so I would say, yeah! Close it!
