### ISSUE TITLE
Commons Stack support of Ata on the TEC case study 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#356]
## 📋   Anything to add?

Continual support on this. Repeating every week. 

## 🎉   Subtasks

- [ ] weekly interviews
- [ ] wednesday sessions
- [ ] review part of the interviews doc

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied to TEC Coordination Workspace [issue 218](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/218)

**Comment by liviade1** [comment]
Closing this issue and taking out the repeating tag since Ata is offboarding the Case Studies
