### ISSUE TITLE
Identify WG proposals and assist their submission using the new process

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#357]
## 🎉   Subtasks

- [ ] Make a list of proposals that are emerging
- [ ] speak to the proponents to make sure the new process is used 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
MAKE THE PLAN!

**Comment by iviangita** [comment]
Copied to TEC Coordination workspace [issue 215](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/215)
