### ISSUE TITLE
add working group structure to the Community Stewards group 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#358]
## 🎉   Subtasks

- [ ] prepare a manifesto 
- [ ] organize resources 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Moved to the TEC Coordination repo. ;) 
[Here.](https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/tecommons/coordination/176
)
