### ISSUE TITLE
Look into https://stakes.social/ for staking rewards

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#361]
If you're looking at this issue hoping to contribute to the project, welcome! We'd love to have you contribute, so please let us know if you have any questions. 

Comment on the issue or touch base in our [telegram](https://t.me/joinchat/HGrjjRS2PoowbH1ODuefuA). 

## 💭 Here's some additional context to this issue:
 
This is a very cool protocol, much along the lines of what we want to do for the Commons Stack, but specifically for open source software

## 🎉   Steps to closing this issue:

- [x] Join their discord
- [x] tell them you are from the Commons Stack/Gardens Swarm/Giveth/whatever and want to join the protocol 
- [x] Find out exactly what hoops we would have to jump thru
- [x] Check in with Griff to communicate what it will take
- [ ] If Griff says lets do it, make a new  issue outlining the steps required

## 🤓Project Manager - check in with me for questions on this issue!

🙋‍♀️🙋‍♂️ @GriffGreen 

## 🔗   Working documents and inspirational links go here: 
👉 https://stakes.social/

**Comment by GriffGreen** [comment]
@krisjpi tell griff when its there.

**Comment by krisjpi** [comment]
@GriffGreen we have been approved! We just have to set up the pool, which will be done very shortly.

**Comment by krisjpi** [comment]
passed this on to Griff to create the pool with the Commons Stack address.
