### ISSUE TITLE
Articles (Explainers)

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#37]
Explainer articles: 
- ABC Explainer (started)
- Commons Dashboard Explainer (or good FAQ entry)

Whitepaper articles
- Background 
- Our Goals 
- Iterative Build & Field Test Strategy	
- Fundraising plan (CSTK part done)
- Hatching a Commons 
- Operating a cyber-physical Commons
- Deepdive into TEC use case (possible part II of this)
- Iteration 1 deepdive

**Comment by tamarandom** [comment]
Closing out old epics 🧹 🕸️
