### ISSUE TITLE
Giveth milestones party (end of month to plan date)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#385]
## 📋   Anything to add?

Monthly session to demonstrate how to create Giveth milestones for newcomers or for those of us who prefer to complete our milestones in good company.

All are welcome to join the party. 

## 🎉   Subtasks

- [x] Schedule (one or more) sessions for the start of the month
- [x] Invite all newcomers to the session

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Closing for this month, will reopen next month

**Comment by iviangita** [comment]
Closing for this month! Next Trace Party is set on July 30th 11am EST/5pm CET 

https://calendar.google.com/event?action=TEMPLATE&tmeid=NmZqcG84cnRxZGczYjI5MWM3MjR0a25hcGggY192amRja2ZqNGJoYXJ1b3ZoZDRybW8zZHR2NEBn&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com

**Comment by tamarandom** [comment]
Closing this for good! @freshelle is coordinating this for Giveth universe.
