### ISSUE TITLE
Praise Quantification (first week of the month)

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#386]
## 📋   Anything to add?

Do the monthly quantification of praise

## 🎉   Subtasks

- [x] Find a time and schedule for it (ideally the first week of the month to quantify the past month).
- [x] Hold the session (may extend a-sync).
- [x] Review

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
Closing!
