### ISSUE TITLE
Token dishing

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#388]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@mafer-cordovas I am closing this one. It was old and not used. 
There is already a new one on the Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/52
