### ISSUE TITLE
Monthly Emails

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#390]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
@tamarandom are these the same as the TS acceptance emails from #392? I intend to do those alongside the acceptance (which could be bi-weekly depending on the number of applicants), so I'm confused. There will certainly be more emails/comms in the new engagement design, but those are upcoming.

**Comment by tamarandom** [comment]
Hey @knobsdao ! This was born of the list of repeating tasks transcribed to github. If it does not reflect what is your actual plan, then let's get rid of it! You can add issues that are aligned with your new plan. 🙏🏽
