### ISSUE TITLE
Needs checkpoint & reviews (TEC, Giveth, cadCAD...)

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#391]
## 📋   Anything to add?

Just going over the goals for the month and make sure they are achieve-able

## 🎉   Subtasks

- [ ] TEC
- [ ] Giveth
- [ ] cadCAD
- [ ] CS

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
cleaning up. Closing.
