### ISSUE TITLE
Immunity to change homework - Kate & Greaterthan

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#395]
## 📋   Anything to add?
Don't forget to do your "Immunity to change" homework and/or organize any notes or next steps for the continuation/conclusion of our team culture processes in January =)

## 🎉   Subtasks

- [ ] Do your homework before Jan 11! (https://docs.google.com/document/d/1bwPSGTI4AFKdHQJwTgtxZgs4AJyxHtyDT6CoSir5RqQ/edit#)
- [x] Jeff & Griff set up chats with Ria

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1bwPSGTI4AFKdHQJwTgtxZgs4AJyxHtyDT6CoSir5RqQ/edit#

**Comment by tamarandom** [comment]
Closing this epic! The three issues inside are all closed.
