### ISSUE TITLE
Review the welcome forum section

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#403]
## 📋   Anything to add?

https://forum.tecommons.org/c/welcome-to-the-tec/12

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied to TEC Coordination Workspace [issue 219](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/219)
