### ISSUE TITLE
Fix Amin and Sponnet's CSTK balances (burn and audit!)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#414]
## 🎉   Subtasks

- [ ] Figure out how much they should have with the donations they made
- [ ] burn their tokens to match that amount

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by knobsdao** [comment]
Note in case we haven't addressed this donation by stephen_yo [[link for context](https://twitter.com/GitcoinDisputes/status/1339658671932895233)]

**Comment by krisjpi** [comment]
Fixed the balances and sent to a vote on the CS DAO
