### ISSUE TITLE
Kris must fill this out to officially become members CS - Declaration of acceptance - Board make a pdf of it, sign it and send it on telegram.

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#415]
Kris must fill this out to officially become members of the Board

 make a pdf of it, sign it and send it on telegram.

https://docs.google.com/document/d/1Eub2sDE6JzoSwR4aOdfOclvPAXl4MeENmGQSDzsfp3A/edit?usp=sharing

**Comment by krisjpi** [comment]
signed copy was provided to the board.
