### ISSUE TITLE
TEC Case Study

### ISSUE THREAD

**Issue by ataberkcasur** [commons-stack/iteration0#418]
## 🎉   Subtasks

- [Finish the Review of the Roadmap] 
- [Compile mini-case studies of TEC's recurring themes and main categories ] 
- [Design a structure inspired by Ostrom's 8 Principles ] 

List of the mini case studies (as the emerge): 

1. Praise 
2. Weekly Sync
3. Mission, Vision, Values
4. Roadmap
5. Decision Making 
6. Roles: Stewards, Contributors, Subject Matter Experts
7. Code of Conduct 

## 🤼‍♂️   Reviewer

@GriffGreen 
@liviade1 
@tamarandom

**Comment by tamarandom** [comment]
Hi @ataberkcasur ! Do I have all the right links here? And for the Roles, Stewards and Subject Matter Experts, will those be combined into 1 case study or will the be separate? 

Praise: https://docs.google.com/document/d/12R2gPN49sLMG6B_mJnvKrzmtZz_AGDQMM09Vv9X04Zw/edit#

Roles: https://docs.google.com/document/d/1TfUn9q5-7ZgXFNAd6CxE-ko8_XMRw7o-2dc-INWG2Xs/edit

Stewards:
https://docs.google.com/document/d/1tPAFUFFWMC7PHzdkj3yk8FuPjOyoBVRAvn1s_ndy8Wc/edit?usp=sharing

Subject matter expert: https://docs.google.com/document/d/1megtJ2Toiktz27AqFMF7kRsnFebrIs3VLBl5ERwVr9c/edit

Weekly Synchs: https://docs.google.com/document/d/1XF6-fKgJJIJDZ8JcpDbPKtWPZ2eJm2Iv2z70Lc8FgT0/edit

Advice process: https://docs.google.com/document/d/14x5wJBY2TTvDw19V-dMYS-zZtJNYTRyqVgyqYRB7IOg/edit?usp=sharing

**Comment by tamarandom** [comment]
Tracking what is done, what needs to be done and where everything is in this tracker now: https://docs.google.com/spreadsheets/d/1KaLbNATFLcbRNFFF0H64j0tkxw6jvoUK3O8BPy7DLC8/edit#gid=0

**Comment by tamarandom** [comment]
Closing out the former Case Study issues. New ones will be added as necessary.
