### ISSUE TITLE
FAQ update

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#42]
### 🎉  share with the team for review and word-smithing

- [x] What is the CSTK token?
- [x] What is the Commons Stack? 
- [x] What is a Field Test Commons? 
- [x] What is the iteration 0 of the Commons Stack?

### 🤼‍♂️   Reviewer

@krrisis @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1SxjROeFTXy9n6ZZrEcEA_t-PySiop5plaYXTcNV_uyo/edit?usp=sharing

**Comment by liviade1** [comment]
3rd and 4th questions waiting for Griff's review

**Comment by GriffGreen** [comment]
WOW! I suck.. i;m sorry this fell off my todo list.. but I will make it a priority this week
