### ISSUE TITLE
TEC Praise Mini Case Study

### ISSUE THREAD

**Issue by ataberkcasur** [commons-stack/iteration0#424]
## 🎉   Subtasks

- [x] Reviewed by Griff 
- [x]  Edit 
- [x]  Review by Livia
- [ ] Edit
- [ ] Update with v2

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/12R2gPN49sLMG6B_mJnvKrzmtZz_AGDQMM09Vv9X04Zw/edit?usp=sharing

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/12R2gPN49sLMG6B_mJnvKrzmtZz_AGDQMM09Vv9X04Zw/edit?usp=sharing

**Comment by ataberkcasur** [comment]
@liviade1 need your review

**Comment by liviade1** [comment]
@ataberkcasur reviewd!
