### ISSUE TITLE
Improvements for praise process for CS Twitter posts

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#438]
## 📋   Anything to add?

Review the current process. I'm seeing that some small adjustments should have a big win, making it less prone to error. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1QTL3nZCTIjQzHGncku8XP-R1wZM98pwb7KlkrVF5kXE/edit?ts=5ff6e113#heading=h.xcnx2b67c3uq

**Comment by eduardovegap** [comment]
We have suggested to linked the Forum count post to the Praise system, still checking if it's viable.

**Comment by tamarandom** [comment]
Hey @eduardovegap, great. Can you direct me to the requirements/criteria if it's already documented somewhere. At the moment, @iviangita is improving the process to dish praise to twitter posts and thinking to loop in Forum posts. Even as a short term solution until a more robust one is implemented.

**Comment by iviangita** [comment]
Hi @eduardovegap! I will be also dishing praises for TECommons Forum posts/replies on a weekly basis now and opened a separate issue for that. Here is the [issue link](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/300) for your reference. If you have anything to add there, that would be very much appreciated! :D
