### ISSUE TITLE
Commons Swarm work hours

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#439]
## 📋   Anything to add?
Update Commons Swarm [work hours](https://docs.google.com/spreadsheets/d/1oRDecU-weSTOLv061N5O7VAJcDfU5XGqmu21ntTXOos/edit#gid=1554918051) every week and send to Sem for review.

Copied and moved from TEC repo [issue 200](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/200)
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Handed off to Freshelle :)

**Comment by tamarandom** [comment]
Hey @iviangita @GriffGreen - this is long done, right? Closing.
