### ISSUE TITLE
Designs for small batch of products 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#442]

**Comment by markoprljic** [comment]
Added basic Commons Stack Logo swag to the Printful shop.
<img width="1187" alt="Image 2021-01-11 at 6 21 10 pm" src="https://user-images.githubusercontent.com/5704285/104216054-dba7ac00-5439-11eb-9150-e092cc941b12.png">

**Comment by tamarandom** [comment]
@markoprljic nice work, Marko! This is exactly what we need for now.
