### ISSUE TITLE
Pull in the most immediate issues captured in the miro board

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#457]
## 📋   Anything to add?

Call for help to organize the content pieces captured into this [miro board](https://miro.com/app/board/o9J_krl8Cv0=/) into github so they can be prioritized and assigned. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🔗   Work doc - inspirational links

https://miro.com/app/board/o9J_krl8Cv0=/

![Screen Shot 2021-01-13 at 7.33.45 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/2443b4db-8d79-403d-80de-ab4b96f51242)

**Comment by krisjpi** [comment]
I've linked all existing issues directly from the text in the Miro board for the CS side. I'd like to continue using this board, or at least this process moving forward - I think it works well!

**Comment by tamarandom** [comment]
Backlog refinement! Cleaning things up!! 

Looking at the post-it notes on the miro board, these are done or out of date. Closing.
