### ISSUE TITLE
Library Content List

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#468]
If you're looking at this issue hoping to contribute to the project, welcome! We'd love to have you contribute, so please let us know if you have any questions. 

Comment on the issue or touch base in our [Discord](https://discord.gg/t5Dh5Pttf3) on the "active contributors" chat! 

## 💭 Here's a link to our working brain-dump:
 https://docs.google.com/document/d/1RvePvhCK1OzviciblJVAd40UBqmUER05bOOGZtxP9YI/edit?usp=sharing 

## 🎉   Steps to closing this issue:
- [ ] Gather titles and links to major (or all) educational and foundational pieces CS has published
- [ ] Gather links to open research from partners and aligned communities
- [ ] Once first draft is complete, continue to review external submissions as they emerge

## 🤓Project Manager - check in with me for questions on this issue!

🙋‍♀️🙋‍♂️ @krisjpi

**Comment by jessicazartler** [comment]
Heya @krisjpi I put in all the stuff I had so far into this doc and will work on this if we don't get a contributor :D

**Comment by GriffGreen** [comment]
A lot of this is happening in the Notion.... This will get bonus progress ;-)

**Comment by liviade1** [comment]
Can we close this issue since Notion was created? @krisjpi

**Comment by tamarandom** [comment]
Update : closing this issue. To have a hack session to look at what else needs to be added to Notion. New issues to be created after that session.
