### ISSUE TITLE
Jeff - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#475]

**Comment by GriffGreen** [comment]
- [ ] Get 450 DAI and >0.01 ETH in your CSTK address
- [ ] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [ ] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [ ] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by Jeff-Emmett** [comment]
Github issue: https://github.com/commons-stack/tech-dapp/issues/132

**Comment by Jeff-Emmett** [comment]
Awaiting on scholarship info from @GriffGreen when available!  Otherwise complete. 🙏
