### ISSUE TITLE
Daniel - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#476]
- [x] Get 450 DAI and >0.01 ETH in your CSTK address
- [x] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [x] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [ ] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by knobsdao** [comment]
- Two Connect Wallet buttons on the first screen felt like too much but it's ok once they change.
- T&C/Statutes pop-up window displays in a low part of my screen and it's difficult to visualize even in full-screen; it also can't be moved.
- "Membership in Swiss Commons Stack Associations" is in plural. Shouldn't it be "Association"?
- Text for the options under "FOR YOUR CONTRIBUTION YOU WILL ALSO RECEIVE:" is misaligned.
- Opened the DApp with a wallet without ETH and the notification is great but there's no link to a source to get some.
