### ISSUE TITLE
Kris - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#478]
- [x] Get 450 DAI and >0.01 ETH in your CSTK address
- [x] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [x] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [x] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by krisjpi** [comment]
Just have to work on the scholarship part, but closing this!
p.s. the confetti after completing the flow is a nice touch :)
