### ISSUE TITLE
Plan and Schedule a Trusted Seed AMA around the Swiss Membership app

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#483]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
[Draft version [](here.](https://docs.google.com/document/d/1eC1uF1HVge7V2J2D9MxIkYDC91sR03b2j_V9J-QcYR4/edit?usp=sharing))

**Comment by tamarandom** [comment]
Date is on lock! Thurs Feb 18 4pm CET / 10am EST / 7am PST
