### ISSUE TITLE
Add a link to Jeff's Slides at the end of the FAQ page

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#486]
## 📋   Anything to add?

Check Jeff's Doc for risks to mitigate

## 🎉   Subtasks

- [ ] Most of this is already done, it just needs to be collected
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @krisjpi ! Nate is building this FAQ for the TEC side of comms. Maybe it's useful for you too for the CS side? 
https://docs.google.com/document/d/16UI-EfD4qcwBaAv3Eexlv01SOK7oiDt4gkVT5rEY6X4/edit#heading=h.t62y5prlm779

**Comment by tamarandom** [comment]
hey @krisjpi this deck from @Jeff-Emmett can also be super helpful for you post 
https://docs.google.com/presentation/d/1GnBiXP5sUeCwsCPItXwmqsCzK9TL71pkyGmF5xHlBA0/edit

**Comment by tamarandom** [comment]
Hey @krisjpi  Can you drop an update in here please?

**Comment by tamarandom** [comment]
Note to self : when it's done, pass to @MerlinEgalite to update on member.commonstack

**Comment by tamarandom** [comment]
Note to self : work with @Jeff-Emmett on this.

**Comment by tamarandom** [comment]
🤦🏻‍♀️

**Comment by tamarandom** [comment]
No way was I going to punt this to another Sprint! 😂

Note that for many of the Q's, I copied the bulleted-list answers. 
There are two natural sections: 
1. Trusted Seed Swiss Membership 
2. CSTK Score

@Jeff-Emmett and @krisjpi have a look. Add to our Comms call tomorrow? 

https://docs.google.com/document/d/1JjsylfNwEiSZgCmIMH7rRrHzE8EmrsvMXzcPW3pTdLc/edit#

**Comment by Jeff-Emmett** [comment]
Looks great, I added in a few comments and updated both TS decks with the
relevant Praise Onboarding session & discord link!

Jeff

**Comment by tamarandom** [comment]
@tamarandom to drop into the Swiss Mem repo.

**Comment by tamarandom** [comment]
Opened https://app.zenhub.com/workspaces/swiss-association-membership-dapp-5fdbdf9b377f91000f03122f/issues/commons-stack/swissmem-dapp/319

Closing this one.
