### ISSUE TITLE
Update the CS FAQ doc 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#493]
## 📋   Anything to add?

This is the current [FAQ](https://docs.google.com/document/d/1SxjROeFTXy9n6ZZrEcEA_t-PySiop5plaYXTcNV_uyo/edit#). Needs love. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@liviade1

**Comment by tamarandom** [comment]
@Ekeneodigwe you and @GriffGreen are working on this, right?

**Comment by Ekeneodigwe** [comment]
> @Ekeneodigwe you and @GriffGreen are working on this, right?

Yes we are, the ref link is https://github.com/commons-stack/iteration0/issues/892 so we might close this one
