### ISSUE TITLE
Optimize the fundraising funnel for this fundraise

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#5]
Would like to assign Jess I think... but we have this very old funnel and it needs to be updated and optimized
<img width="837" alt="Screen Shot 2020-07-15 at 6 42 24 PM" src="https://user-images.githubusercontent.com/14945613/87829299-1069ea80-c87f-11ea-80a9-14bf43af68ec.png">

**Comment by Kisgus** [comment]
Please specify this issue further @GriffGreen
