### ISSUE TITLE
CSTK Membership Dapp Launch

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#501]
If you're looking at this issue hoping to contribute to the project, welcome! We'd love to have you contribute, so please let us know if you have any questions. 

Comment on the issue or touch base in our [telegram](https://t.me/joinchat/HGrjjRS2PoowbH1ODuefuA). 

## 🎉   Steps to closing this issue:

- [x] Membership Dapp to launch
- [ ] (option a) Outline the steps to joining the dapp in a post
- [ ] (option b) Create a video or GIF walkthrough of the dapp

## 🤓Project Manager - check in with me for questions on this issue!

🙋‍♀️🙋‍♂️ @krisjpi 

## 🔗   Working documents and inspirational links go here: 
👉 
👉

**Comment by gravenp** [comment]
@krisjpi I'm just getting my bearings for contributing to CS, but this looks like a good one to start with. Is it already in process this sprint? If you still need help on this one, just let me know!

**Comment by tamarandom** [comment]
Hey @gravenp ! Great of you to jump in! We've already soft launched the dApp (yay!) so likely no more help needed there but if you're available Tues. at 8PM CET, @krisjpi leads our Comms Weekly. He's invited the community to jump on and join us. 

This is the [video link](https://meet.google.com/mzi-krya-ppy?authuser=1) we are using but we will soon be moving to our new [Discord Server](https://discord.gg/cWDy2cQ2Gg).
