### ISSUE TITLE
Swag shop women's t-shirt (model we have is discontinued)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#508]
## 📋   Anything to add?

Doh! The women's t-shirt product we are using is no longer available in Printful! 

@markoprljic when can you design a new one? 

![Screen Shot 2021-01-28 at 9.05.00 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/f3f488dd-8b63-4d4c-930f-b6e3cc3b3b68)
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by markoprljic** [comment]
@tamarandom I added new Woman's t-shirt in the shop. The old one I renamed and appended "(Discontinued)" so you know which one to delete.

**Comment by tamarandom** [comment]
Awesome, @markoprljic !!
