### ISSUE TITLE
Articles R&D

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#51]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@Jeff-Emmett, @jessicazartler : Is this epic & these issues still kicking?

**Comment by jessicazartler** [comment]
Hey @tamarandom we can put all of the backlogged CS articles under this - not sure what is ACTUALLY on the board, certainly GDrive's got some.. we can have a look and see.. or is there a better epic you would recommend? Content production is kind of this.. we can discuss in Comms call maybe

**Comment by tamarandom** [comment]
Hey @jessicazartler I've tagged these original comm epics with #refinement so they are on our radar to be revisited and revised or replaced. Example, #22 was opened in July. Is this still relevant? Then let's prioritize it and plan it in a sprint. If not, let's close it. The goal is that the backlog accurately reflects what we will deliver. It is our roadmap. 

This Epic in particular is for R&D and so, sure, we can use it to track the R&D articles for CS. Though I'd like to have @krisjpi and @knobsdao decide how to organize this backlog. They may have other ideas. 

You reminded me to add the #refinement tag review to our agenda tonight. ;)

**Comment by Jeff-Emmett** [comment]
At present we don't have agreement on an R&D mandate for the Commons Stack, until Griff agrees it is a priority (at least I think that's how it works). As of now, he has expressed issues with the narrative proposal I drew up but discussion has been pushed to an unknown date in the future.

This is an old epic full of old issues, so in the interest of keeping the board clean let's close it.

**Comment by jessicazartler** [comment]
@tamarandom @krisjpi @Jeff-Emmett @knobsdao 
Here is the document we came up with on the last CS Comms call w/ Kris/Jeff/me and this is most of the backlogged articles so I suggest using this and updating the roadmap/backlog/making sure all of that is reflected and synced with Github + the stuff we did yesterday on the Miro board:

https://docs.google.com/document/d/1-rlSFia-SFlCouXgsd2Ndoziq0wufNQrREerewQICpk/edit#

**Comment by tamarandom** [comment]
Thank you, @jessicazartler.
