### ISSUE TITLE
BLOCKING : Multiple products are ordered but only 1 makes it to the JSON that is sent to Printful for fulfillment. 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#518]
## 📋   Anything to add?

Shoot. This happened before then seemed to be fixes but it's back again. 

-Multiple products are ordered but only 1 makes it into the JSON that is sent to Printful for fulfillment. 
-The person receives confirmation of the order by email. That shows the multiple items.
-The fulfillment center will only receive ONE of the items to fulfill. 

![Screen Shot 2021-01-29 at 11.11.19 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/5ab2b0af-a4a6-417c-a234-7bea70d78690)

![Screen Shot 2021-01-29 at 11.11.28 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/f2d10906-633a-474a-8358-2c840bd9d003)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@skylar745 See screenshots in the body of the issue.

**Comment by skylar745** [comment]
solved, this was due to missmatch products variant references btw dshop / printful. (probable cause is 1 printful shop can only link to one external shop, was linked to 2)

**Comment by tamarandom** [comment]
Hey @skylar745 ! Excellent. My tests run true too. I'll close this now.
