### ISSUE TITLE
TRUST Score Increase notification(s)

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#523]
## 📋   Anything to add?
We need to tell people when they got tokens.

## 🎉   Subtasks

- [ ] How might we do this over the Discord bot? Telegram? Email?
- [x] How might we track where they are in the process? HubSpot?

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@knobsdao Is this recurring each Sprint? Or is this a one-time issue?

**Comment by knobsdao** [comment]
Draft of comms here: https://docs.google.com/document/d/1eiKrFWQyPMyHdlhKlY3IHOhk0szxuv6a5JysmL7dh3o/edit?usp=sharing @GriffGreen

**Comment by usama9500** [comment]
Closing this issue, moved to trusted seed repo.  https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/101

**Comment by YineisyM** [comment]
This issue belongs to the Trusted Seed workspace. I removed the tag repeating monthly to avoid it reopening again here.
