### ISSUE TITLE
Praise Testing Channel on Discord!

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#527]
## 📋   Anything to add?
Create an invisible praise channel.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by krisjpi** [comment]
Created praise testing channel, moved to the backstage, and made it visible to Praise Givers in the server. Feel free to re-open and comment with any new requests for this channel.
