### ISSUE TITLE
Dishing praise to ecosystem partners more often!

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#529]
## 📋   Anything to add?
Making a list of awesome that we want to have CSTK tokens and dish them praise on the reg for the awesome shit they do.

## 🎉   Subtasks

- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
Scheduled an recurring calendar for ASYNC/30min session to do this every Monday, or poke people to give names and I will do it :D

**Comment by jessicazartler** [comment]
@tamarandom @GriffGreen we are now doing this every Monday in sprint planning/team call - shall we close this issue?

**Comment by jessicazartler** [comment]
Should we close this? :D
