### ISSUE TITLE
Rotate in Community members to be CSTK Quantifiers

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#530]
## 🎉   Subtasks

- [ ] Invite the high CSTK winners (top 5ish in the last rounds)
- [ ] Create easy onboarding/process/guidance for them to jump in.

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Update: @knobsdao will be passing to @mafer-cordovas and @YineisyM

**Comment by mafer-labs** [comment]
For Jan&Feb '22 praise quant, we had Acidlazzer, T-Rossi, and Bustavo. Along with Yine, Griff and myself

**Comment by mafer-labs** [comment]
Our quanters for Jan & Feb were Bustavo, Thiago, and Acidlazzer! 
8 hours of work, almost 4000 rows of praise... success and a lot of patience.

**Comment by mafer-labs** [comment]
Thanks to the Praise gods, we are getting a new system. Ths is now issue #136[](https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/136)
