### ISSUE TITLE
Normalize Transparent Self-Praise

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#531]
## 📋   Anything to add?
Dishing praise to ourselves is not in our culture! let's change it!

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @knobsdao @GriffGreen - I def made an effort to include myself in my praise where it makes sense. Thanks for bringing this up!

**Comment by tamarandom** [comment]
Goodbye! It was worth a try but self-praise isn't taking on.
