### ISSUE TITLE
AMA on Feb 18th. Plan & promotion.

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#533]
## 📋   Anything to add?

Refine or revise the plan and promote the AMA on
Thurs Feb 18 4pm CET / 10am EST / 7am PST 

[Drafted plan here 
](https://docs.google.com/document/d/1eC1uF1HVge7V2J2D9MxIkYDC91sR03b2j_V9J-QcYR4/edit)
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
@knobsdao we need tweets.... and stuff? @krisjpi can be assigned to some of the external comms
