### ISSUE TITLE
Make a Graphic for the AMA

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#546]

**Comment by jessicazartler** [comment]
Feb. 18 10am EST
Discord @krisjpi which voice channel?
Once I have info I can make it :D

**Comment by jessicazartler** [comment]
Thurs Feb 18 4pm CET / 10am EST / 7am PST

https://docs.google.com/document/d/1eC1uF1HVge7V2J2D9MxIkYDC91sR03b2j_V9J-QcYR4/edit#heading=h.d24ta0xzakh1

**Comment by jessicazartler** [comment]
Ahhh I remember.. @tamarandom the date I am good -- just need which voice channel on the new CS discord so I can make a QR code/put it on the graphic thanks!

**Comment by tamarandom** [comment]
![Screen Shot 2021-02-11 at 7 33 26 AM](https://user-images.githubusercontent.com/703624/107608219-9e525c00-6c3b-11eb-8158-14b99477db3f.png)

**Comment by jessicazartler** [comment]
We could rename AMA channel or hold it in the general which we could call Community Hall or whatevs..
Could do fun ones like 1HIve
Library
Cafe
Elevator
Or Community Hall whatevs with emojis

**Comment by GriffGreen** [comment]
The Call Channel will be named: Community Hall

**Comment by jessicazartler** [comment]
![Graphics (30)](https://user-images.githubusercontent.com/43972522/107983640-2fa33480-6f94-11eb-9baf-6eb35e3cc5af.jpg)

**Comment by jessicazartler** [comment]
<img width="418" alt="AMA Graphic" src="https://user-images.githubusercontent.com/43972522/107991561-ddb6da80-6fa4-11eb-93bc-0b71c474bf9c.png">
