### ISSUE TITLE
Create initial draft of the plan

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#547]

**Comment by tamarandom** [comment]
Draft plan is [here. ](https://docs.google.com/document/d/1eC1uF1HVge7V2J2D9MxIkYDC91sR03b2j_V9J-QcYR4/edit)

**Comment by tamarandom** [comment]
Done. Here it is : https://docs.google.com/document/d/1eC1uF1HVge7V2J2D9MxIkYDC91sR03b2j_V9J-QcYR4/edit

@knobsdao Handing this off to you and your capable hands!

Bummer I can't join our first AMA!!  😭 Hopefully the next one!!
