### ISSUE TITLE
Clean/curate the "For Contributor" labelled issues 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#555]
## 📋   Anything to add?

A number of the issues tagged "For Contributor" are not for contributors. ;) 
End goal : the tagged issues are easy for someone new to come in and pick up.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @krisjpi I'm going to leave this one out of Sprint 8. If you get it it, that's great! But it can be for a later Sprint. Not a top priority.

**Comment by GriffGreen** [comment]
We have to do something different here! Why does this never work?

Livia can do a quick survey, and then make a hack sesh happen...?

There is a lot of data in the Trusted Seed form.... once we have good issues, let's pass the issues out to the right people!!
