### ISSUE TITLE
Move cslove codebase to github repo 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#557]
## 📋   Anything to add?

Final destination :  github.com/commons-stack/cslove-dshop 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by skylar745** [comment]
@tamarandom can do that. need permissions though ;)

**Comment by tamarandom** [comment]
https://github.com/commons-stack/cslove-dshop

Completed by @skylar745 !
