### ISSUE TITLE
Swiss Membership (formerly CSTK Token )Dapp Release General Article 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#559]
## 📋   Anything to add?

A why and how piece for the CSTK token dapp including a video walk through/screenshots

## 🎉   Subtasks

- [ ] Write draft 
- [ ] Pass for feedback/edits
- [ ] Publish & distribute

## 🤼‍♂️   Reviewer

@jessicazartler @GriffGreen @Jeff-Emmett

**Comment by GriffGreen** [comment]
I call it the Swiss Membership DApp.. we can rename it something else... but it shouldn't be CSTK Token Dapp anymore

**Comment by tamarandom** [comment]
Hey @krisjpi ! As you heard on the Swiss Asso call tonight the video & transcript will be ready tonight/tomorrow. WOOOOOOOT! This article can be based on that almost entirely, right?
