### ISSUE TITLE
Comms push for the AMA (tweet and whatever else you think is necessary!)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#562]
## 📋   Anything to add?

When
Thurs Feb 18 4pm CET / 10am EST / 7am PST  

Who
CS team : Livia, Griff, Dan 
Moderator : Simon de la Rouviere

Where
Discord streamed to YouTube livestream  (@Krisj can you confirm this?)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
Drafted some messaging [here](https://docs.google.com/document/d/1Gj1x0nQPHXLNJOOlFBmWDEolsDQrEUc1_EKhjrFr4Go/edit?usp=sharing). Will review it myself with a fresh brain. Could use some eyes, ping @jessicazartler @krisjpi @GriffGreen

**Comment by knobsdao** [comment]
Comms shared over Telegram and Twitter, and Email sent via HubSpot to 467 contacts.
