### ISSUE TITLE
Discord / CS Daily Team Touchpoint

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#564]
## 📋   Anything to add?
The CS Daily Team Touchpoint channel isn't showing on my end...please help? 😅

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/8924835d-ae8e-4950-be09-cef02a203feb)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by krisjpi** [comment]
Walked Ivy through this, she now has access!
