### ISSUE TITLE
Review TS Email to share data with TEC

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#565]
## 📋   Anything to add?
Related to #380.
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao @krisjpi 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1dduKeUsDhi1B6ZLDHMyXAsT-qyxD_sbNoqpMsigDV8s/edit#heading=h.xo0feo7u83u3

**Comment by jessicazartler** [comment]
This was already sent, yes @knobsdao ?

**Comment by knobsdao** [comment]
Not yet, @jessicazartler. I'll do it ASAP when the copy is approved and have a link for the CTA. I just sent you test emails for you to check out. ( :

On the CTA, is the website the right choice? I can track individual clicks in the back-end, but we could even link to an opt-in form tied to TEC's own CRM or similar. Maybe @markoprljic has some thoughts on this.

Looking forward to unblock this!

**Comment by markoprljic** [comment]
Thanks @knobsdao What website are you referring to? I'm not clear on what this issue is about. Thanks.

**Comment by knobsdao** [comment]
The TEC website, @markoprljic. This issue is on comms from CS side for the Trusted Seed to opt-into direct comms from TEC.

**Comment by markoprljic** [comment]
Aha, ok :)
Currently we have a CTA on TEC website to subscribe to newsletter, like this in the footer:
![Uploading Image 2021-02-21 at 7.43.48 am.jpg…]()


Rosa is working on making a Wordpress theme based on the designs.

**Comment by knobsdao** [comment]
Check out these comms to direct the TS to the TEC, @GriffGreen: https://docs.google.com/document/d/1dduKeUsDhi1B6ZLDHMyXAsT-qyxD_sbNoqpMsigDV8s/edit#heading=h.xo0feo7u83u3

**Comment by jessicazartler** [comment]
Nice work! @knobsdao gave some edits/feedback, let me know if you have any questions about it :D Thank you!

**Comment by knobsdao** [comment]
@markoprljic where is this newsletter subscription connected to? TEC HubSpot? Elsewhere?

**Comment by markoprljic** [comment]
I assume it should be Hubspot as you mentioned earlier. Rosa is setting up the WP and I believe it will be handled via a plugin there. This is the related issue https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/323

**Comment by rosamoc** [comment]
@markoprljic  Hi, normally I work with mailchimp, I install a plugin on the website, I register a form and after that emails are collected in mailchimp automatically.
I suppose that with hubspot it should be the same, I must install the plugin, register a form and insert it in the web page. In order to send the emails to the hubspot list I would need the list keys.

**Comment by markoprljic** [comment]
Yup, that's why I asked :)
I assume you need the Hubspot ID in order to connect https://cdn2.hubspot.net/hub/2832391/hubfs/Marketing/WordPress/wordpress-plugin-hubspot-account-information-in-plugin.png?width=1200&name=wordpress-plugin-hubspot-account-information-in-plugin.png

I think @knobsdao can provide this to us.

**Comment by rosamoc** [comment]
Yes, thank you!

**Comment by knobsdao** [comment]
This is the TEC HubSpot Hub ID: 9327973 @rosamoc. Sending @markoprljic the HubSpot login info just in case. Ping me if anything. ( :

**Comment by rosamoc** [comment]
@knobsdao @markoprljic I have just installed Contact Form 7 HubSpot plugin and would need the information shown in the attached image. Thank you. 
<img width="1316" alt="Captura de Pantalla 2021-02-25 a les 20 29 51" src="https://user-images.githubusercontent.com/74400450/109206968-d5cb1780-77a8-11eb-8433-dc3cd03f1b29.png">

**Comment by rosamoc** [comment]
@markoprljic You can now visit the page (It is not open to everyone) . The newsletter section is not yet available. But in the meantime you can check it out and give your opinion. I tried to make it as close to your design as possible, but a screen is not the same as a fixed design. 
https://tecommons.org/?page_id=380

**Comment by knobsdao** [comment]
Hi @rosamoc. I sent the API Key and HubSpot login info to @markoprljic. Ping me over Telegram @knobsDAO and I'll send the API Key directly to you.

For those error notifications, the TEC email associated with HubSpot is: tokenengineeringcommons@gmail.com

**Comment by jessicazartler** [comment]
Hey everyone -- I am closing this issue as it is finished -- was a review for our email campaign

Please revert other discussions to the issue Marko mentioned https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/323 or create any new ones needed - thank you! :D
