### ISSUE TITLE
HubSpot

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#572]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @YineisyM, is there any reason to keep this Epic open? Are there other issues related to Hubspot that you want to throw in here?

**Comment by YineisyM** [comment]
Hey @tamarandom the only issue currently associated with HubSpot [is this one](https://github.com/Trusted-Seed/coordination/issues/6).
