### ISSUE TITLE
Create a CS Branded PDF template for Ata's mini-case studies

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#574]
## 📋   Anything to add?

 a PDF template with Commons Stack branding for some case studies/papers we will be releasing

Content https://docs.google.com/document/d/12R2gPN49sLMG6B_mJnvKrzmtZz_AGDQMM09Vv9X04Zw/edit#heading=h.3g1bjyjfqo9r

Design something like this https://www.radicalxchange.org/kiosk/papers/Taiwan_Grassroots_Digital_Democracy_That_Works_V1_DIGITAL_.pdf

**Output:** 

1. PDF Booklet for this particular document linked above
2. Make the PDF Booklet a Template that we can reuse for other content
3. Source file

## 🤼‍♂️   Reviewer

@GriffGreen @Jeff-Emmett @ataberkcasur @liviade1 @tamarandom 

## 🔗   Work doc - inspirational links

Branding assets https://github.com/commons-stack/commons-stack-assets

**Comment by GriffGreen** [comment]
Talking with @markoprljic he was saying that we may need more a graphic designer? Anyone know anyone :-D?

**Comment by markoprljic** [comment]
@josiprajevic confirmed he'd help. I'll coordinate further.

**Comment by jessicazartler** [comment]
Awesome! Thanks a million Marko!

**Comment by markoprljic** [comment]
Update: 
- I briefed @josiprajevic who will be working on this issue in the coming days
- I updated the issue with more information and resources 

@josiprajevic if you have any questions, please post here in the comments and tag @GriffGreen or someone from the Reviewers.

Thanks a lot for stepping in and helping out :) Glad to have you with us 🤗

**Comment by josiprajevic** [comment]
[Booklet-The Commons Stack Praise System-A Case Study.pdf](https://github.com/commons-stack/iteration0/files/6028732/Booklet-The.Commons.Stack.Praise.System-A.Case.Study.pdf)
Here it is, first draft :)

**Comment by josiprajevic** [comment]
> Update:
> 
> * I briefed @josiprajevic who will be working on this issue in the coming days
> * I updated the issue with more information and resources
> 
> @josiprajevic if you have any questions, please post here in the comments and tag @GriffGreen or someone from the Reviewers.
> 
> Thanks a lot for stepping in and helping out :) Glad to have you with us 🤗

Thank you @markoprljic for opportunity 🤗

**Comment by josiprajevic** [comment]
> [Booklet-The Commons Stack Praise System-A Case Study.pdf](https://github.com/commons-stack/iteration0/files/6028732/Booklet-The.Commons.Stack.Praise.System-A.Case.Study.pdf)
> Here it is, first draft :)

@GriffGreen

**Comment by liviade1** [comment]
it looks great @josiprajevic!! I really like the clean design and the waves flow! thanks for taking this on 🙌 
My only feedback is the text disposition. I'm not sure what could change. Maybe is just about making the words a little bit bigger. @ataberkcasur what do you think?

**Comment by jessicazartler** [comment]
Wow!!!! Looks awesome @josiprajevic !!! 

Just a few notes for discussion before we finalize as well:

@liviade1 I think generally for academic papers the text is even smaller but we don't have to be in that style and agree bigger text could be easier to look at.. depends how academic we want to look generally = to small text size haha

Two requested additions pending discussion:

1) Final page -- CS a little bigger or bold + choose/add social media/links to the right hand side for website/Discord/other CTAs that are appropriate

2) A Creative Commons license or attribution -- we have discussed but have not reached a conclusion -- will discuss in the Comms meeting today -- here are some previous discussions from Telegram:


Hey @GriffGreen @Krisjones what was the final verdict on attribution or CC licensing? 

FROM PREVIOUS CONVOS:

Griff Green,
We are generally copy left... GPLv3 for code and yeah i don't know if we have ever done a CC license... the question is with or without attribution... i'm down for either personally... @Krisjones @Gfriis @JessicaZartler @krrisis or anyone else... have you had these debates before?

Kris Jones, [02.11.20 15:16]
[In reply to Griff Green🌱]
I did look into this a bit when I had to choose how my thesis was published. I would have to check, but a general copy left statement and some version of a creative commons license would sound right to me. Without attribution is probably fine, because unless we want to be litigous about it, with attribution is somewhat toothless. People are more likely to attribute anyway IMO.

Kris Jones, [02.11.20 15:18]
I generally like to push it into builders/remixers hands to see what they can produce rather than try to worry about attribution, as a personal preference


Jess,
Saw this for licensing the other day on Prime DAOs materials - perhaps we can adopt this? Legal question for @lorelai and lawyers? https://ecosystem.daoincubator.org/fractalizing/
![CC license](https://user-images.githubusercontent.com/43972522/108861601-67763180-75bd-11eb-8e1f-5e495b2e39e2.jpg)

**Comment by jessicazartler** [comment]
@GriffGreen is requesting also a second version with inverting colors -- black background with white text to have the dark mode option lol @Jeff-Emmett said this is hard for people who will print it out... Leave it to @krisjpi to decide CC license/CTAs/final edits

**Comment by markoprljic** [comment]
I advise def not dark bg, because of printing and because of readability. @josiprajevic is an expert in print design, should give his feedback on this.

**Comment by josiprajevic** [comment]
I made two versions. Dark background for digital use and white for printing so you can use both for what ever purpose you need. Text is little bigger (around 20%). I can add CC licensing any time if you want. Also when we agree on design I will make google doc or any other word alternative version so you can change anything you want when you want. @GriffGreen @liviade1 @jessicazartler @markoprljic
[Booklet-The Commons Stack Praise System-A Case Study-vers2-dark.pdf](https://github.com/commons-stack/iteration0/files/6036475/Booklet-The.Commons.Stack.Praise.System-A.Case.Study-vers2-dark.pdf)
[Booklet-The Commons Stack Praise System-A Case Study-vers2.pdf](https://github.com/commons-stack/iteration0/files/6036477/Booklet-The.Commons.Stack.Praise.System-A.Case.Study-vers2.pdf)

**Comment by ataberkcasur** [comment]
@liviade1 looks awesome! Should we consider adding some visuals, (praise dish sheet glimpse), (highest praise receivers list in the newsletters), ( a screenshot from the intro stage of the weekly synch recording) etc?

**Comment by jessicazartler** [comment]
@josiprajevic @markoprljic what is the best way to have this as template so we don't need to bother you guys every time? Just a PDF editor or is there any other way you would recommend? Thank you for all your work on this!

**Comment by josiprajevic** [comment]
@jessicazartler I can make template in google document or any other word alternative version so you can change anything you want. It would be good to have some visuals so I can design how to use them in future. Also I hope that I could be useful to this community in future too for any kind of graphic design and also photography if needed. Just ask.

**Comment by josiprajevic** [comment]
@jessicazartler for this design I used InDesign but that is expensive professional tool. I can convert him to any thing you want and regularly use

**Comment by Jeff-Emmett** [comment]
@josiprajevic a google doc template would be SUPER awesome!  Thanks so much for this template, it's beautiful!

**Comment by jessicazartler** [comment]
@ataberkcasur if you have a few samples for the praise Josi can make them look cool and have a template for these as well ☝️ if you want to give a sample or two... thanks Josi the templates will get lots of eyes :D

**Comment by ataberkcasur** [comment]
@jessicazartler @josiprajevic will get on it tomorrow!

**Comment by GriffGreen** [comment]
Sweet! @josiprajevic... make sure to work with @ataberkcasur on this... the rest of us have lots of ideas... but he is the one putting his name on it. :-D

**Comment by ataberkcasur** [comment]
Hey @josiprajevic! I just completed a google drive which includes 6 images + a google doc that has the related location for each image and an explanatory. 

It seems like there is an abundance of images (6) for different aspects of the Praise. I am not sure how they they will look, will they be cramped or not. Or if we should include some of them at the end somewhere like the relevant documents. 

Second thing is one of the images include a screenshot of the community call. Is that a problem @GriffGreen that people's faces are displayed? I guess not, since they are already visible on YouTube. But just wanted to check. 

Here is the link: [https://drive.google.com/file/d/1KQ1kBqOUucRf8woSQN8VLaUlsk6R4-F9/view?usp=sharing](url)

Let me know what you think!

**Comment by tamarandom** [comment]
Hey @ataberkcasur Did you mean to link to a folder with the 6 images inside? The above link only goes to a single image with no way to navigate to the parent directory.

**Comment by ataberkcasur** [comment]
https://drive.google.com/drive/folders/1_JEZzSu-rAjTrIIN_v-dL0FwIjByL4cR?usp=sharing 

Does this work? @tamarandom

**Comment by tamarandom** [comment]
🙌🏼 Perfectly !

**Comment by Jeff-Emmett** [comment]
Hey Ata, I wanted to surface this kumu map created of Commons Stack Praise
(probably a few months out of date at this point), but I figured it would
be awesome to include a visualization of the praise dished in this case
study as well!

https://kumu.io/jeffemmett/commons-stack-praise

If interested to include, I'd be happy to talk to the map creator (Danilo
from BlockScience) and see if it's possible to update.

Jeff

**Comment by josiprajevic** [comment]
[Booklet - 1- dark - with pictures.pdf](https://github.com/commons-stack/iteration0/files/6078947/Booklet.-.1-.dark.-.with.pictures.pdf)
I put pictures in dark template. If this works for you you I will make google doc template. I did research on google doc design possibilities and they are pretty rudimentary but I will try my best to get similar result to this pdf.

@ataberkcasur @jessicazartler @griffgreen @jeffemmett

**Comment by ataberkcasur** [comment]
Thanks @josiprajevic , looks good! I have some feedbacks on the positioning, some seems to cut off a paragraph into two, but I guess that's why you are making the google doc right? to edit them. Also, would be better to have explanatory texts under images smaller and not bold, in my opinion. 

One more thing! I added one more image, if you could integrate it into the cover page, that would be cool :) it is in the drive, titled "Praise COVER IMAGE". Thanks a lot!

**Comment by josiprajevic** [comment]
@ataberkcasur Is this right :)
[Booklet - 2- dark - with pictures and cover.pdf](https://github.com/commons-stack/iteration0/files/6095312/Booklet.-.2-.dark.-.with.pictures.and.cover.pdf)

**Comment by ataberkcasur** [comment]
@josiprajevic :)))))))))))

Looks awesome! 

@liviade1 @GriffGreen @Jeff-Emmett what are your thoughts with the images displayed? If positive, should we move on to the next step in terms of integrating the updated text with this template?

**Comment by Jeff-Emmett** [comment]
Amazing stuff @ataberkcasur and @josiprajevic!

A few points from my end:
- The praise meme is HILARIOUS, but perhaps better to include in the report as a reference to the meme-ification and gamification of the recognition process than on the cover page? Initial intention for the report design was to present more professional and unified series of case studies.

- I feel like the creative commons license is a good inclusion to be clear about our publication status (for reuse or citations), rather than just saying "The Commons Stack 2021". I see the second (inside) page on second page at the bottom is open - perhaps it would be good to include more info there? The RadxChange report gives a bit of context about the organization as well, and I think it comes across really well. I'd be happy to write up a short description if we thought this would be a good model to replicate:

![image](https://user-images.githubusercontent.com/46964190/110374992-5d255000-801f-11eb-839e-4972465b7d54.png)

- @ataberkcasur, I am touching base with Danilo about the praise network map in Kumu tomorrow - I hope to be able to get it updated and included in this report ASAP!

- Re: publication and distribution, has there been any discussion with @krisjpi @jessicazartler @liviade1 about prioritization or timeline?  I know we have a pretty burning piece on the CSTK Dapp coming out early this week, wondering what our projected timeline for this piece is relative to the other pieces we have on the go besides the Dapp launch.

**Comment by josiprajevic** [comment]
[Booklet - 3- dark - with pictures.pdf](https://github.com/commons-stack/iteration0/files/6108354/Booklet.-.3-.dark.-.with.pictures.pdf)
@Jeff-Emmett Here it is

**Comment by ataberkcasur** [comment]
Hi @josiprajevic , the praise case study draft is complete now. Can you prepare the booklet with the latest format with the Booklet -3 format you recently shared, and we can move forward in steps to publishing it? 

This is the latest version: https://docs.google.com/document/d/12R2gPN49sLMG6B_mJnvKrzmtZz_AGDQMM09Vv9X04Zw/edit#heading=h.3g1bjyjfqo9r

**Comment by Jeff-Emmett** [comment]
For the license section, we can probably write something along the lines of:

This Commons Stack Case Study is part of a larger effort by the Commons Stack project to provide detailed analysis and reports on lessons learned from deploying the Commons Stack design pattern to individual Commons deployments.

This publication is licensed under ... <license details to be completed here>

**Comment by josiprajevic** [comment]
@ataberkcasur @Jeff-Emmett Latest light and dark version. Just need to finish licence section (in latest version there was no pictures)
[Booklet - 4- dark.pdf](https://github.com/commons-stack/iteration0/files/6196509/Booklet.-.4-.dark.pdf)
 
[Booklet - 4- light.pdf](https://github.com/commons-stack/iteration0/files/6196510/Booklet.-.4-.light.pdf)

**Comment by ataberkcasur** [comment]
@josiprajevic thanks! could you also incorporate the visuals in the text just like the previous one? If you can share it in editable format we can leave our comments on it too to make your job easier, but that's your call :)

**Comment by ataberkcasur** [comment]
Hi  @josiprajevic. Just for the heads up, I added one more visual to the drive: 

https://drive.google.com/drive/folders/1_JEZzSu-rAjTrIIN_v-dL0FwIjByL4cR?usp=sharing

**Comment by GriffGreen** [comment]
@josiprajevic @ataberkcasur The License should be Creative Commons with Attribution :-D - "CC By"

**Comment by josiprajevic** [comment]
@ataberkcasur Thank you. I think that I corrected that mistake 10 min after uploading pdf. Please download and check again. 
@Jeff-Emmett Here is google docs - first version https://docs.google.com/document/d/1JcKwaHfbFFtriBiFM1J--sCT2ErGYNXZUqWEsGVCjaI/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
Super cool @josiprajevic, thanks for making these templates accessible for future case studies as well!

@ataberkcasur if there is nothing else from your side on case study updates, I would be happy to forward them to the CS comms team (@krisjpi @jessicazartler) to get the case study loaded on our website and into our content distribution pipeline. Let me know if there are any final changes on your end 🙏

**Comment by GriffGreen** [comment]
@josiprajevic @ataberkcasur I made a few changes... all very small, mostly around capitalization... and I would love to get rid of the "the" in front of Commons Stack.. it is fine in the pictures... but the cover page has a "The" and i cant get rid of it.

**Comment by GriffGreen** [comment]
Thank you @Jeff-Emmett for getting rid of the THE!!!

**Comment by GriffGreen** [comment]
PROPOSED NAME CHANGE

Token Engineering Commons Case Study Part 1:
Praise

**Comment by josiprajevic** [comment]
@GriffGreen Double click on the cover page. That will open new window name drawing. Title is white so you can´t see him but try to click and select in the place where he is positioned and you will find him there. After you change what you want just save and close. Google docs are not design friendly :)

**Comment by Jeff-Emmett** [comment]
I updated the license and titles throughout - this is good to go on my end!  
![image](https://user-images.githubusercontent.com/46964190/113881246-42630a00-978a-11eb-932f-cca0a51d0c59.png)

@josiprajevic if you can convert this updated google doc into the dual column PDF, I think we are good to host that on our website and start the distribution process!  (Is there an easy way to get this to print out in the dual column PDF, or does that require some special design tools/skills? Just curious!)

https://docs.google.com/document/d/1JcKwaHfbFFtriBiFM1J--sCT2ErGYNXZUqWEsGVCjaI/edit

**Comment by josiprajevic** [comment]
[Booklet - 6- dark.pdf](https://github.com/commons-stack/iteration0/files/6302548/Booklet.-.6-.dark.pdf)
@Jeff-Emmett hera it is, in two colum, to make that i have to make all in Adobe Indesign. Sorry about delay. Laptop issues. I hope that I helped.
