### ISSUE TITLE
Trusted Seed Spotlight #4 Recording

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#576]
## 🎉   Subtasks

- [x] Schedule 
- [x] Record Intvw

--------------------- For next Sprint ;-) -----------------------
- [x] Edit Video
- [x] Get feedback from team
- [x] Finalize
- [x] Upload
- [x] Dsitribute

## 🤼‍♂️   Reviewer

@GriffGreen @krisjpi

**Comment by jessicazartler** [comment]
Call set up with Simon DLR for next Friday, Feb. 19

**Comment by GriffGreen** [comment]
woot W00T!!

**Comment by jessicazartler** [comment]
Had a very inspiring and awesome recording sesh with Simon, SUPER looking forward to working on this one :D

**Comment by GriffGreen** [comment]
Newsletter aimed for March 3

**Comment by jessicazartler** [comment]
Once newsletter goes out I will Tweet it - then it's closed!

**Comment by jessicazartler** [comment]
Discussed with @krisjpi on Comms call yesterday - Ivy to Tweet with newsletter content - going to close this :D
