### ISSUE TITLE
Code of Conduct Mini Case 

### ISSUE THREAD

**Issue by ataberkcasur** [commons-stack/iteration0#579]
## 🎉   Subtasks

- [ ] Reviewed by @GriffGreen 
- [ ]  Edit 
- [ ]  Review by @liviade1 
- [ ] Edit

Working Document: 

https://docs.google.com/document/d/1LfAhdPyEK2TnC4O4YFd3wXd6Rfh02oFywyuoNm-cr0w/edit?usp=sharing

**Comment by ataberkcasur** [comment]
@liviade1 @GriffGreen need reviews <3

**Comment by tamarandom** [comment]
Closing out the former Case Study issues. New ones will be added as necessary.
