### ISSUE TITLE
TEC Weekly Synch Mini-Case - Get it Ready for Publish

### ISSUE THREAD

**Issue by ataberkcasur** [commons-stack/iteration0#582]
## 🎉   Subtasks

- [ ] Reviewed by @GriffGreen 
- [ ] Edited
- [ ] Reviewed by @liviade1 
- [ ] Edited

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1XF6-fKgJJIJDZ8JcpDbPKtWPZ2eJm2Iv2z70Lc8FgT0/edit

**Comment by ataberkcasur** [comment]
@GriffGreen @liviade1  ready for review

**Comment by ataberkcasur** [comment]
@GriffGreen @liviade1 need review

**Comment by tamarandom** [comment]
Update : @ataberkcasur needs one final pass on this.

**Comment by tamarandom** [comment]
Closing out the former Case Study issues. New ones will be added as necessary.
