### ISSUE TITLE
Jess  / Monthly Giveth Milestone 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#588]
- [X] Dec
- [x] Jan
- [x] Feb
- [x] Mar
- [x] Apr
- [x] May
- [x] June
- [x] July
- [x] July2 bonus
- [x] August
- [x] September
- [x] October
- [x] November
- [x] December

@freshelle

**Comment by jessicazartler** [comment]
Thanks Tam! Finished January https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/602b23219b17d857430385fc

**Comment by jessicazartler** [comment]
Finshed February https://beta.giveth.io/milestone/jess-february-21-milestone

Do I leave this issue open? :D Thanks! @tamarandom

**Comment by jessicazartler** [comment]
Yay thank you!!

**Comment by jessicazartler** [comment]
@GriffGreen finished and submitted March - thank you!! :D
https://beta.giveth.io/milestone/jess-milestone-for-communications-and-ecosystem-development

**Comment by jessicazartler** [comment]
@tamarandom @GriffGreen submitted milestone for April (Sorry so late!!!) - Thank you! 🙏🐣
https://beta.giveth.io/milestone/jess-milestone-for-communications-and-ecosystem-development

**Comment by jessicazartler** [comment]
@tamarandom @GriffGreen Just did my milestone for May - thank you so much!!

https://beta.giveth.io/milestone/jess-milestone-for-communications-and-ecosystem-development

**Comment by jessicazartler** [comment]
@tamarandom @GriffGreen @hanners717  just submitted my milestone for June - thank you! :D Hope you're having a nice weekend!

https://trace.giveth.io/trace/jess-milestone-for-communications-and-ecosystem-development

**Comment by jessicazartler** [comment]
@freshelle @GriffGreen @tamarandom submitted my milestone for July -- thank you! :D Have an awesome week!!
https://trace.giveth.io/trace/jess-milestone-for-communications-and-ecosystem-development

July2 bonus https://trace.giveth.io/trace/jess-cs-team-reward-july

**Comment by jessicazartler** [comment]
@freshelle @GriffGreen @tamarandom submitted for August - thanks! :D 
https://trace.giveth.io/trace/jess-milestone-for-communications-and-ecosystem-development

**Comment by GriffGreen** [comment]
Filled!

**Comment by jessicazartler** [comment]
Gracias @GriffGreen !!!

**Comment by jessicazartler** [comment]
@freshelle @GriffGreen @tamarandom November submitted https://trace.giveth.io/trace/jess-milestone-for-communications-and-ecosystem-development
Thank you 🙏
