### ISSUE TITLE
Create a competition or something for Designs for the new shop.commonsstack.org  

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#592]
## 📋   Anything to add?

@krisjpi you volunteered to champion this and, whether it be a contest or some other method, it's yours. 

"The Backend" section of [this doc](https://docs.google.com/document/d/13_KtVYHLqJABvUJ7jwoAwgmTlzYiumWnFZTL1ypnn-w/edit?usp=sharing) might be handy for you but hollar if you need anything else!  

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Note that the payment shop will be cross brand and have collections for CS, TEC, Giveth & DappNode!

**Comment by tamarandom** [comment]
Hey @krisjpi, from our comms call today, @bollenta is volunteering to help create designs for the shops.

**Comment by liviade1** [comment]
Hey @krisjpi - we have another issue for contributors to help with design, so I'll remove the tag from this one and once the contest has been created we can have a new issue with directions for contributors.
