### ISSUE TITLE
Canned Welcome Message for new Members

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#595]
## 📋   Anything to add?
A small message with details on CS/TS or other info that would be relevant to new members. Also a warm welcome!

Target: 
- joining Discord (bot welcome message)
- joining newsletter
- joining Trusted Seed <-- being done by @iviangita with the cslove airdrop message 
- joining Telegram 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @krisjpi Is this done? Do you need a hand with this?

**Comment by YineisyM** [comment]
I'm working this in the issue [#739](https://github.com/commons-stack/iteration0/issues/739).  I close this issue.
