### ISSUE TITLE
Change value of CSLOVE tokens to $55

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#601]
## 📋   Anything to add?

Shipping to Brazil is just outside the range of $10 we've estimated for shipping. Though not that far outside that estimate. We want to change the value of 1 cslove token to $55 to cover shipping there (and potentially elsewhere). 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by skylar745** [comment]
@tamarandom just updated the price. Will need to build/deploy before it's live

**Comment by tamarandom** [comment]
Excellent! @skylar745 and I  synced on a deployment Tuesday, Feb 16th. Will close then.

**Comment by tamarandom** [comment]
Closing!
