### ISSUE TITLE
Get a plant to ask questions if there is a lull in the AMA

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#604]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
haha I've reached out to Nate and will also ask in stewards

**Comment by jessicazartler** [comment]
Stewards and friends attended, we had no shortage of questions! :D Everyone did a great job
