### ISSUE TITLE
Notion Knowledge Base Party!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#605]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@Jeff-Emmett @krisjpi @liviade1

**Comment by jessicazartler** [comment]
The CS Notion is now in Giveth workspace and we had a kind of "kick off" today presenting the organization @Jeff-Emmett set up - so next sprint planning we can discuss next steps - likely individual tasks of adding in links/organizing info - and for Kris, this goes along with Onboarding TL;DR/improving contributor process as we discussed some info sharing solution that will help
