### ISSUE TITLE
Weekly CSLOVE airdrop email to all new Swiss Assoc members

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#608]
## 📋   Anything to add?

@iviangita I assigned this to you but we will do it together the next 2-3 times. 

## 🎉   Subtasks

- [ ] Send out CSLOVE email
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
Tracker: https://docs.google.com/spreadsheets/d/1R9JGNzoOT0VYlkbPvVacodXjU5wsyYOTZqcKpCusAnA/edit?usp=sharing

How to find newly activated TS members: https://docs.google.com/document/d/1mof4sSkI8BrHofzDszKvMomG-e_2lRMtl_zSORBWBs0/edit?usp=sharing

CSLOVE email process: https://docs.google.com/document/d/1ahTWZZdE1YITJCGs1t8XwzJtlzu2rr1_joJIJ2LL_U0/edit?usp=sharing

**Comment by tamarandom** [comment]
@GriffGreen We ran into a problem exporting the file from giveth yesterday. Same today.  Here is the error: ![giveth export.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b91dde68-a588-4f72-8e96-07e99ba6f7e0)

**Comment by tamarandom** [comment]
Done for this week. Closing! ;)

**Comment by tamarandom** [comment]
On pause until the shops are working again.

**Comment by iviangita** [comment]
Thank you @YineisyM @mafer-cordovas for taking this on, I added the links in the description above :)

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board. 🌱
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/8
