### ISSUE TITLE
Sketch Whale Tank concept/idea for TS Engagement

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#611]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao @tamarandom @GriffGreen

**Comment by tamarandom** [comment]
Is this like Shark Tank for Whales?

**Comment by jessicazartler** [comment]
Yes haha just put it in to note it -- will write it all out when I get some time.. not priority so idea sketching for next sprint but while I am typing... :D 

It would be a solution for not having enough time in the TEC spotlight/filling a need in the ecosystem of a space for advising/incubating projects -- many inbounds come to Jeff and I for feedback on their systems/projects (some of them not even related to CS or open source) -- so instead, I thought we could have TS OGs/founders/whales advising younger up and coming TS members/minos who need feedback on their cryptoeconomic models/TokenEngineering/suggestions for advisors/network connections/investment/funding/etc. -- maybe offer a prize or bounty from a sponsor... Maybe we could partner with Gitcoin..

It would give a chance also for the "whales" to be recognized for their work so I think it would be a win-win as it would require little resources from CS -- just call planning/promotion/one host (happy to volunteer/produce)-- but I think this could be a great value add for TS and a great engagement activity -- we could try it once to start and see how it goes over/what value it delivers and if the people like it, we could consider once per month
