### ISSUE TITLE
Schedule crazy ideas meeting/doc

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#612]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@krisjpi @liviade1 @tamarandom

**Comment by tamarandom** [comment]
I love crazy ideas. Count me in!

**Comment by tamarandom** [comment]
Hey @jessicazartler ! Someone just shared an idea and I didn't know where to put it so I created this doc so we don't lose track of it. Can we roll Ludo's idea into where ever we end up tracking this stuff? 

https://docs.google.com/document/d/1ZRUfTERBcrfepwabNCjCLRX1JNgbcDKxJr-N4ixlp4M/edit

**Comment by jessicazartler** [comment]
Requested access - thanks so much Tam! Hadn't gotten to this yet.. will have a look at the doc and add a few things - will see and circle back on next steps

**Comment by jessicazartler** [comment]
This turned into the NFT Auction :D
