### ISSUE TITLE
Praise dishing optimization : Telegram, Discord and Twitter - oh my!

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#614]
## 📋   Anything to add?

Recently we've ramped up our praise on twitter and we have just launched the CS Discord but we still rely mainly on a list of telegram handles. See the Commons Stack Retweets / Mentions google doc

Dishing praise across all three mediums would be facilitated with a single db mapping these three handles for our communities (both CS and TEC). 

@knobsdao can you help @iviangita with this task so that it meets your Trusted Seed needs as well as the needs for praise dishing ! 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Hi @GriffGreen @krisjpi @knobsdao can I request for a call to get a clearer idea on how to approach this? Please let me know your availability :)

**Comment by knobsdao** [comment]
In a related update, we now have the new Typeform live and have questions to gather these three handles in place.

The operations side regarding how we combine the information streams is at the top of our minds in the road to the next praise quant. ( :

**Comment by GriffGreen** [comment]
@iviangita Mateo and Juanka in the TEC are also working on this!!! Make sure to sync with them

**Comment by GriffGreen** [comment]
Praise sheet is optimized for Matching Discord and Telegram Handles
