### ISSUE TITLE
Code push to Prod (date tbc)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#618]

**Comment by tamarandom** [comment]
Hey @geleeroyale Might I ask you to explain the process to push dev code to prod. We will need to do that for the launch, of course, but also going forward as we support the dApp.

**Comment by geleeroyale** [comment]
The process is very easy. Once happy with a version from `develop`, just merge a pull request to the `production` branch.

The DApp will then automatically deploy via Netlify Continuous Integration

**Comment by tamarandom** [comment]
This is great! Thank you.
