### ISSUE TITLE
Coordinate our participation in the Metagov & NEAR Protocol Hackathon

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#643]
## 🎉   Subtasks

- [ ] Follow up call to discuss Hackathon / collab & funding opps
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao @Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1_bkHcFXUwaHRHKdhG4-Hjkeo7uk109u-zwwVaT1088o/edit#

**Comment by jessicazartler** [comment]
Sent follow up message to NEAR to schedule a call regarding participation in the hackathon/talks

Also discuss potential funding/resource allocation to the Dashboard project and CS infrastructure

**Comment by jessicazartler** [comment]
Had a call with James & Josh Tan of MetaGov and supporting the hackathon with intros/some other things in the works.. I still need to schedule a separate call to talk with James about funding/resources for CS/cadCAD...

I am chatting with Luke about possibly working with NEAR/MetaGov resources to build a stand alone CV instance that could be portable for any blockchain/DAO @GriffGreen @Jeff-Emmett will keep you posted on if/when that's gonna happen, just for you to be aware

**Comment by GriffGreen** [comment]
Need to organize and make a doc for this

**Comment by jessicazartler** [comment]
Doc we can use for promotions from James https://docs.google.com/document/d/13A6vI2b5q_cwuDFmduAf2iQSpKQjDeQrWyKAcd0JSUA/edit#heading=h.1qi2fu6due1b

**Comment by GriffGreen** [comment]
Bringing in Renzo... 

Might bring in @liviade1 

Z is presenting ABC

**Comment by jessicazartler** [comment]
Tweeted, graphic'd, recorded, YouTubed, shilled in lots of channels - phew! It's done.. also gave to Ivy to put workshops in Evergreen content flow - I'm out! haha
