### ISSUE TITLE
Update the  Burn Log after every mint/burn sesh

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#653]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://wiki.commonsstack.org/transparent-log-of-burn-events

**Comment by knobsdao** [comment]
Burns for 2021 up to May 25th were updated today: https://wiki.commonsstack.org/transparent-log-of-burn-events

**Comment by mafer-labs** [comment]
Updated 2 burn cases: https://wiki.commonsstack.org/transparent-log-of-burn-events

**Comment by mafer-labs** [comment]
The pending re-mint will be left for next year after the praise quant.

**Comment by mafer-labs** [comment]
This is now issue [#135](https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/135) on the TS zenhub
