### ISSUE TITLE
Edit Everything you Need to Know for the Trusted Seed

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#657]
## 🎉   Subtasks

- [x] infographic
- [x] graphics
- [ ] 

## 🤼‍♂️   Reviewer

@Jeff-Emmett @knobsdao @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/presentation/d/1GnBiXP5sUeCwsCPItXwmqsCzK9TL71pkyGmF5xHlBA0/edit?usp=sharing

**Comment by tamarandom** [comment]
@jessicazartler You've done this, right? Those great infographics added to the beginning.

**Comment by jessicazartler** [comment]
Yes, I think this is finished for now :D Thank you!
