### ISSUE TITLE
Swiss Association App

### ISSUE THREAD

**Issue by metaverde** [commons-stack/iteration0#669]
I noticed on the Swiss Association app that it has an `Add CSTK to Metamask` button, so I used it, and it added CSTK to my Ethereum wallet and showed 0 CSTK.

When I changed my wallet to xdai chain, where I had already added CSTK, the app prompted me `You must change networks`.
My Metamask wallet did offer to add CSTK and the amount to my xDai coin list, but it was already there.

I'm not sure this needs fixing, but it could be confusing to people.

**Comment by metaverde** [comment]
Idk the "assigned"?
I'm not sure how I did that?

**Comment by knobsdao** [comment]
@tamarandom is this issue already taken care of in the Membership DApp's repo?

**Comment by tamarandom** [comment]
Hey @metaverde, thanks for logging this. 👍🏽

The consensus is that it is more confusing than helpful. There is an issue open to track removing it in the Swiss Asso dApp repo so I will close this one now.
