### ISSUE TITLE
Update all Commons Stack resources to update the framing around CSTK Score and the activation of the Trusted Seed

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#670]
## 📋   Anything to add?

We had a great start at this by a new contributor
https://github.com/commons-stack/wiki/pull/5/commits/2c65f5c103d65af264af5877743c59de6708e920

TRUSTED SEED. ACTIVATE!
And keep in mind the framing in the case of burning/pending CSTK.

"Activate your Trusted Seed membership by joining the Legal Association"
You are not part of TS until you join the Association.
Trusted Seed score will be burned (when?) BUT it will be recorded so that when you do join the legal association it will be minted.

## 🎉   Subtasks

- [x] Trusted Seed blog post 
- [x] CSTK "Trust Score" blog post
- [x] Contributor guide
- [ ] Website
- [ ] ??? Where else?

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Maybe we write a refreshed article

**Comment by knobsdao** [comment]
Choose to make an "update" comment on our legacy Trusted Seed article as I lean towards not refreshing it. The comment links to our article on "Activating the TS" and when the one of "what's next" after activation is ready, I'll link to it as well.
