### ISSUE TITLE
Review/Update our Wiki

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#674]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://wiki.commonsstack.org/

**Comment by GriffGreen** [comment]
Consider moving this all to the Notion.

**Comment by jessicazartler** [comment]
Added to Comms agenda for discussion tomorrow
https://docs.google.com/document/d/1vQb7DCFqWMmJxK7uRfYEOzyTugbqwTjoJDtLrQqmuoY/edit

**Comment by knobsdao** [comment]
Updated Welcome, Contributors, and Donate sections to avoid confusion. Pausing for now, as the other sections aren't a priority. As a whole, this could merge with the Notion (#613) or work alongside it.
