### ISSUE TITLE
Jess / Fill out CS Notion sections (Check Epic for details)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#683]

**Comment by jessicazartler** [comment]
Yes, I have much more work to do on this! It's kind of a recurring, when I get time/feel inspired I go in and keep building.. but I would like to make an effort to have some public pages open in the next 2 sprints.. thank you for breaking these our Ivy/Tam :D

**Comment by jessicazartler** [comment]
We have a Notion Party work sesh scheduled for Wednesday :D

**Comment by jessicazartler** [comment]
Have updated.. there are definitely more projects for this but closing for now..
