### ISSUE TITLE
Create POAP for Luna Swarm research wrap

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#684]
## 📋   Anything to add?

Tie up the 6 month efforts of the Luna Swarm research group

## 🎉   Subtasks

- [x] Create 
- [ ] Send POAP
- [x] Create summary & update forum post with results and comm hiatus

## 🤼‍♂️   Reviewer

@Jeff-Emmett @tamarandom

**Comment by jessicazartler** [comment]
Updated the forum post https://forum.1hive.org/t/luna-swarm-expanding-the-1hive-cadcad-model/1190/6

And created the POAP, waiting to hear back from POAP - then will distribute

![circle-cropped](https://user-images.githubusercontent.com/43972522/110843653-8ab80680-8276-11eb-9d3d-4727d1f4c38e.png)

**Comment by jessicazartler** [comment]
Created, waiting for approval - told it takes around 7-10 days

**Comment by tamarandom** [comment]
This is really neat!

**Comment by jessicazartler** [comment]
Thank you @GriffGreen !!!!! FINISHED! POAPs awaaaaaaaayyyyyyyyy! <3
