### ISSUE TITLE
Curve Labs TS Onboarding

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#687]
## 📋   Anything to add?
Jeff setting up a chat with the Curve Labs folk to onboard them to the TS.

## 🎉   Subtasks
- [ ] Find call slot that works with team
- [ ] Presentation
- [ ] Follow up

## 🤼‍♂️   Reviewer

@tamarandom

**Comment by tamarandom** [comment]
We call this one done, right @Jeff-Emmett ?
