### ISSUE TITLE
Setup recurring Ask Dan hour  (formerly known as some kind of AMA)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#689]
## 📋   Anything to add?

This would be less of a "big" production than the last one. Something simple like a set hour (weekly or bi-weekly) to send people with questions. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
Now live at issue #724.
