### ISSUE TITLE
Thank you for Gitcoin Grant: Iteration 0

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#698]

**Comment by jessicazartler** [comment]
@GriffGreen @tamarandom scheduled calendar invite for Friday to remind us to send these out

**Comment by GriffGreen** [comment]
Thx jess!

**Comment by jessicazartler** [comment]
The Commons Stack: Iteration 0 : 🙏 Thank you so much for your contribution to the Commons Stack: Iteration 0 - we're so incredibly grateful!

🌐 We are making amazing progress! If you want to see the Commons Stack’s economic model being applied, check out the Token Engineering Commons:
https://forum.tecommons.org/t/5-how-to-join-contribute/98

🤩 Special Shout outs to Super Star Contributors - those who gave _>100 DAI to our various grants will receive CSTK tokens (if they are in the Trusted Seed), a non-transferrable token representing reputation score. Trusted Seed membership offers exclusive access to Commons hatches, airdrops, schwag and legal protection.

🌱 Join the Mission🌱

Apply to the Trusted Seed
https://medium.com/commonsstack/join-the-commons-stacks-trusted-seed-swiss-association-ed51a356cb6c

🔉Discord https://discord.gg/RapbpfFzgN
⌨Telegram channel https://t.me/CommonsStack
🐦 Twitter: https://twitter.com/CommonsStack
🗞️ Newsletter: https://commonsstack.org/resources

🌷 Have a beautiful Spring!

**Comment by jessicazartler** [comment]
<img width="458" alt="GG thank you CS" src="https://user-images.githubusercontent.com/43972522/112701124-25633880-8e66-11eb-8838-dff006a97c45.png">
