### ISSUE TITLE
Thank you for Gitcoin Grant: Token Engineering Commons

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#701]

**Comment by jessicazartler** [comment]
@GriffGreen @cranders1 did this one - thank you Craig!!!!!!

@cranders1 sent a message to funders of Token Engineering Commons. This is what they said:

    Token Engineering Commons : Thanks so much for contributing to the TEC GR9 - we're extremely grateful! Your contribution is supporting sustainable & ethical design for token ecosystems 🥳

🎆 We've been busy fortifying our Cultural Build, onboarding Hatchers, and debugging our tech stack. With close to 300 active community members, the TEC ecosystem continues to gather momentum towards our upcoming Hatch. We are close to freezing the Hatch DAO contracts and currently anticipate a full launch by early May.

Come help us launch the TEC ecosystem  👇🏼

New TEC Website
https://tec-web.netlify.app/

The TEC Dashboard
https://tec-hatch-demo.herokuapp.com/hatch

TEC Gitbook
https://token-engineering-commons.gitbook.io/tec-handbook/

Tokenlog Parameter Voting
https://deploy-preview-16--tokenlog.netlify.app/TECommons/coordination

TEC Funding Proposal Submissions
https://forum.tecommons.org/c/proposals/7

CSTK Swiss Association -- JOIN
https://member.commonsstack.foundation/

**Comment by cranders1** [comment]
cheers
