### ISSUE TITLE
Thank you for Gitcoin Grant: cadCAD

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#703]

**Comment by jessicazartler** [comment]
CADCAD THANK YOU:

Thank you so much for your contribution to cadCAD - we're extremely grateful!

Thanks to your support, we’ll be issuing bounties for developers to work on educational materials so more people can learn how to model complex systems - and you are an important part of it!

🤖cadCAD Onboarding TL;DR https://www.notion.so/cadCAD-Onboarding-TL-DR-e0da826e676344ee94d71d39d65d4fc2
🍎cadCAD Introductory Course cadCAD.education
📆cadCAD Google events calendar https://calendar.google.com/calendar/embed?src=cadcad.org%40gmail.com&ctz=America%2FVancouver
🔉cadCAD Discord https://discord.gg/gJXCh9e5hR
🐦Twitter: https://twitter.com/cadCAD_org
💻Forum: http://community.cadcad.org/
🎥Youtube: https://www.youtube.com/channel/UCQ6UUADq9AczXv0RmzpgBHw?view_as=subscriber

See you in the next round!
