### ISSUE TITLE
Thank you for Gitcoin Grant: Conviction Voting

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#704]

**Comment by jessicazartler** [comment]
First of all, thanks so much to all our grant contributors for supporting our modeling work!

We wanted to send you a quick update on our latest work with feature improvements on the Conviction Voting cadCAD model:


The Luna Swarm has just finished its first round of work, modelling $HNY token issuance in 1Hive to inform decision and policy making. Read more in this forum post https://forum.1hive.org/t/luna-swarm-expanding-the-1hive-cadcad-model/1190/5
Funds are being managed through the Luna Aragon DAO: https://aragon.1hive.org/#/luna/
Join in the conversation on the 1Hive discord: https://discord.gg/XpGPUeW

If you want to learn more about the cadCAD modeling of token ecosystems, check out these resources & links:

🤖cadCAD Onboarding TL;DR https://www.notion.so/cadCAD-Onboarding-TL-DR-e0da826e676344ee94d71d39d65d4fc2
🍎cadCAD Introductory Course cadCAD.education
📆cadCAD Google events calendar https://calendar.google.com/calendar/embed?src=cadcad.org%40gmail.com&ctz=America%2FVancouver
🔉cadCAD Discord https://discord.gg/gJXCh9e5hR
