### ISSUE TITLE
Thank you for Gitcoin Grant: CCG event

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#705]

**Comment by jessicazartler** [comment]
Thank you so much for supporting the Crypto Commons Gathering 2021!

Check out the website and apply to attend:
https://www.crypto-commons.org/

Join us on:
Facebook https://www.facebook.com/Crypto-Commons-Association-326374532130849
Telegram https://t.me/joinchat/EBCUTFq-KAcFv9Qt
Twitter https://twitter.com/GatheringCrypto

Thank you again, and have a beautiful Spring!
