### ISSUE TITLE
MetaFest Presentation & Academic Paper Publication

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#706]
## 📋   Anything to add?
Jeff & Felix presenting this info on Wednesday at MetaFest, but I think we can re-use it to discuss Ostrom's Challenges for the Global Commons in preparation for the imminent academic paper launch!

## 🎉   Subtasks

- [ ] Create presentation
- [ ] Designer to tweak undraw images to dark mode?
- [ ] (Not this sprint) Article summarizing Ostrom's Challenges & the approaches offered by CS/ECSA/Holo in mitigating

## 🤼‍♂️   Reviewer

@jessicazartler @krisjpi 

## 🔗   Work doc - inspirational links
https://docs.google.com/presentation/d/1PhuLezIolwxkfYn5On04jB8C2ke9OM4pQD61eu2HV-E/edit?usp=sharing

**Comment by tamarandom** [comment]
DONE!
