### ISSUE TITLE
Make a Trusted Seed CV Cart

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#707]
## 📋   Anything to add?

Add the grants that are submitted here:
https://cv.commonsstack.org

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
https://gitcoin.co/grants/cart/bulk-add/1155;5;283,2315;5;283,308;5;283,795;5;283,539;5;283,2073;5;283,517;5;283,2305;5;283,2154;5;283,1666;5;283,277;5;283,211;5;283,1769;5;283,184;5;283,1424;5;283,798;5;283,1141;5;283,1732;5;283,213;5;283,2248;5;283,522;5;283,615;5;283,225;5;283,2072;5;283,806;5;283,2225;5;283,684;5;283,1110;5;283,:liviade1
