### ISSUE TITLE
Put the Gitcoin Grants to promote on the Twitter into the twitter sheet

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#708]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Link : https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit#gid=1316217722
