### ISSUE TITLE
Get the Trusted Seed Spotlight #5 - Edit!

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#714]
## 🎉   Subtasks

- [x] Choose person
- [x] Set up interview
- [x] Record
- [x] Edit

---- For next sprint! ----

- [x] Distribute
 

## 🤼‍♂️   Reviewer

@krisjpi @tamarandom @GriffGreen

**Comment by jessicazartler** [comment]
Messaged Zargham to set up a time

**Comment by jessicazartler** [comment]
Interview with Z set for tomorrow afternoon :D TS + TEC 2 for 1!

**Comment by jessicazartler** [comment]
Did the recording - next sprint will edit/distribute :D

**Comment by tamarandom** [comment]
@jessicazartler Just had a quick conversation with fahern (on Discord) who is able to help you with the video editing. Do reach out to him when you can. 🥳

cc @lucashygate

**Comment by jessicazartler** [comment]
FINALLY booking a call with Fahern for hopefully this Friday :D Thank you again @tamarandom !!

**Comment by jessicazartler** [comment]
I sent the raw video, open animation, time codes and all of the graphics to Fahern - he said he will be working on it this week - I will check in again on Friday @tamarandom thanks again! If this goes well, I will pick up the series again with more interviews :D

**Comment by jessicazartler** [comment]
Fahern (Lucas) says he is almost finished, waiting on final editing

**Comment by tamarandom** [comment]
Tagging @lucashygate (aka Fahern).

**Comment by jessicazartler** [comment]
Thanks @tamarandom! Lucas said he is working on trying to create the lower third titles as the last part

**Comment by jessicazartler** [comment]
@iviangita was FINALLY able to get the Trusted Seed Spotlight #5 final edits done -- for now, I've uploaded it to YouTube as unlisted until you give the thumbs up. It's quite longer than normal as it's Zargham 😄 but it's a good mix of Zargham going deep in the wormhole of token engineering, getting philosophical and human - as he introduces his dog 😄 so I didn't cut too much...
https://www.youtube.com/watch?v=84BZpe3l5pw

Let me know any feedback or request for editing - otherwise, I think people will enjoy getting to know Z in this context and it's good to go from my end. Happy to sync for a few anytime on distribution or other planning. Thanks!

**Comment by GriffGreen** [comment]
Yay! Will watch this weekend for sure!

**Comment by jessicazartler** [comment]
OMG it's done :D 
https://twitter.com/JessicaZartler/status/1480578372757565454
