### ISSUE TITLE
Repeating tweets for open Discord calls

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#716]
## 📋   Anything to add?

- CS Comms Meeting - Tuesday's at 3 pm EST (hosted by Kris)
- CS Praise Onboarding - Wednesday's at 12 pm EST (hosted by Kris) (related to issue #343)
- CS Contributors Sync - Thursday's at 12 pm EST (hosted by Dan) (#715)
- CS Trusted Seed Office Hours - Tuesday's at 12 pm EST (hosted by Dan) (#724)

Also, we will have a Commons Stack AMA at 11 am EST Wednesday the 31st. For this one, we'll also need graphics. (#697)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by iviangita** [comment]
Hey @knobsdao the draft copies are now ready for your review :)

https://docs.google.com/document/d/1NZ5U7JkdvcKI_MgyTOwbCpIF5do0F31hdpkKAmSDoak/edit?usp=sharing

**Comment by knobsdao** [comment]
Hey @iviangita. I made these comments on the draft doc for the CS Trusted Seed Office Hours (#724):

CS Trusted Seed Office Hours call is now up in our calendar weekly on Tuesday's at 12 pm EST over Discord.

Calendar link here: https://calendar.google.com/calendar/u/0/embed?src=c_vjdckfj4bharuovhd4rmo3dtv4@group.calendar.google.com&ctz=Eastern/Time/New/York

**Comment by iviangita** [comment]
Removed the Comms Meeting as it will be invite-only 

Note from Kris --> Also just a note, I deleted the tweet about the communications call just now, as we are making that call invite-only for a little while. We really only confirmed that this morning :)

**Comment by iviangita** [comment]
@YineisyM offered to take this on, thanks Yine!

**Comment by tamarandom** [comment]
Part of #1230
