### ISSUE TITLE
CS email campaign reports/stats 

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#722]
## 📋   Anything to add?
An issue to track the outgoing emails from the CS hubspot account. 

-- Objective: to understand how our audience is receiving our communications. Are they opening them, clicking through? What articles are they clicking on the most? Etc.

The idea is to optimize our campaigns by taking into consideration our objectives:
providing our audience information regarding a process, getting more applicants, re-engagement, generating brand awareness, growing a email list, collecting more data about our audience...

**KPIs to consider:**

Number of emails delivered
Open rate
Click-through rate
Bounce rate (hard and soft)

## 🎉   Subtasks

- Gathering the data in a spreadsheet
- Adding it to the existing Google Data Studio Report

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Can this be solved with a media calendar?

**Comment by tamarandom** [comment]
@YineisyM Can you drop a description or sample of the report in here please?

**Comment by YineisyM** [comment]
Hey I updated this issue. I added the KPIs that will be considered for the report and some objectives that will be considering... @tamarandom

**Comment by YineisyM** [comment]
Hey I added this information to our current Data Studio Report. Closing this issue. @iviangita let me know if you want to add something extra, here's the link: https://datastudio.google.com/reporting/3b416db0-999c-4fca-98e7-d9f78c99c5e2 it's on page 2.

**Comment by YineisyM** [comment]
I'm closing this issue because currently HubSpot is being used more to send Trusted Seed communications, therefore the stats are more related to these initiatives. I'll create this same issue in the Trusted Seed Zenhub workspace.

**Comment by tamarandom** [comment]
Closing again. ;) (And taking off the repeating label)
