### ISSUE TITLE
Logos for Giveth and DAppnode for the cross brand shop 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#727]
## 📋   Anything to add?

shoot them over to @tamarandom , please!

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
This is the best folder for Giveth Logos... but there are a lot of great Design Assets in higher folders too
https://github.com/Giveth/giveth-design-assets/tree/master/02-logos/Giveth%20logo

**Comment by GriffGreen** [comment]
Messaged Lanski... he will update for Dappnode logos

**Comment by GriffGreen** [comment]
https://drive.google.com/drive/folders/1MwgxbDoKlrhvO9gg1-bV2TKfLIp462C0?usp=sharing @tamarandom

**Comment by tamarandom** [comment]
Thanks you!
