### ISSUE TITLE
You've Activated Your TS Membership - Now What? - Blog post

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#731]
## 📋   Anything to add?
Short piece, just talking about some of the next steps. How to earn CSTK, particpate in hatches, CV pilots, etc

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
@krisjpi need to mention that CSTK holdings may affect how much you can contribute in TEC and other hatches

**Comment by tamarandom** [comment]
Dupe of #732?

**Comment by GriffGreen** [comment]
Justice and Kris have been discussing this... will prob go into the CSTK piece of be its own piece

**Comment by krisjpi** [comment]
Started the piece - not quite at a shareable draft yet.

**Comment by tamarandom** [comment]
This is quite an old issue and I think this is rolled into the plans @MaxSemenchuk has going for Trusted Seed already but @mafer-cordovas @YineisyM @iviangita, putting on your radar. Should this be closed?

**Comment by tamarandom** [comment]
Thumbs up from @MaxSemenchuk to close.
