### ISSUE TITLE
Z's Article on TEC

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#734]
## 🎉   Subtasks

- [x] Draft
- [x] Edit
- [x] Publish
- [ ] Distribute

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

https://github.com/TokenEngineeringCommunity/resources/pull/3/files

**Comment by Jeff-Emmett** [comment]
https://medium.com/token-engineering-commons/engineering-ethics-in-web3-18d981278018

**Comment by jessicazartler** [comment]
@tamarandom is the distribution represented on TEC board and being handled there so nothing further yeah? Thanks!
