### ISSUE TITLE
ABC sim on website broke... help

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#738]
## 📋   Anything to add?

https://commonsstack.org/abc doesnt work right now?

https://commons-stack.github.io/augmented-tbc-design/ Still works so its the website?

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@krisjpi

**Comment by krisjpi** [comment]
the website has the following in the code block:

    <div id="root"></div>
    <script src="https://drive.google.com/uc?export=download&id=1ykyYHRcRA6071OOkVVALz4ymfIjeKSC2"></script>
    <script src="https://drive.google.com/uc?export=download&id=1CttCBQbRy6Pvb4cnFSnOgrJjrBcueLAF"></script>
    <script src="https://drive.google.com/uc?export=download&id=1-cU7mTjjRgxdsR-mU7n1S42ccXMsSW-J"></script>

I checked to see if the files are all still accessible, and it seems that they are. Still unsure what is breaking down here.

**Comment by tamarandom** [comment]
@dapplion Can you help here? @GriffGreen is sending you dm.

**Comment by krisjpi** [comment]
With the guidance of @dapplion, the page is fully functional again! And I've also got a refresher on some HTML skills and iframes :)
