### ISSUE TITLE
Distribute Academic Paper via Medium Article

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#742]
## 📋   Anything to add?

Distribute the academic paper

## 🎉   Subtasks

- [x] Tweet
- [ ] Newsletter
- [x] CS Telegram/Discord
- [ ] TE Commons
- [ ] TE
- [ ] Partner Communities / Academic Partners

## 🤼‍♂️   Reviewer

@Jeff-Emmett @tamarandom @krisjpi 

## 🔗   Work doc - inspirational links
https://medium.com/commonsstack/challenges-and-approaches-to-scaling-the-global-commons-af1bcb2b67bf

**Comment by jessicazartler** [comment]
Suggestion to @krisjpi to put in the next newsletter

Jeff will schill in Discord channels next Wednesday May 19

**Comment by tamarandom** [comment]
Shill shill shill!

**Comment by tamarandom** [comment]
Closing ....
