### ISSUE TITLE
Discuss Process/Framing/Comms for "Rejected Applicants"

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#745]
## 📋   Anything to add?

As CS gets more "out there" we are increasingly being approached by a diverse pool of actors. From respected TE folk to airdrop hunters, the latter must be discussed. We have simply ignored applicants that don't fit TS in the past, but these numbers are increasing, manifest in 71 applications during March in parallel to GR9 where many of these profiles applied and a handful reached out across channels.

I propose we set up a short meeting to discuss this in the next sprint, or do so during one of the calls hosted by @tamarandom since even if not fully a risk, it does require attention.

## 🎉   Subtasks

- [x] Schedule call.
- [x] Hold discussion.
- [x] Define action items if needed be.

## 🤼‍♂️   Reviewer

@GriffGreen @krisjpi @jessicazartler

**Comment by jessicazartler** [comment]
Great initiative @knobsdao! Is there any current Communications going out to those who are rejected? 

I think also we could look at refining criteria for acceptance - I have always thought, we shouldn't penalize people because in the past they have made money, or just because they have had jobs in corporations or funds - if anything, we can learn from these people and they have money to give! And I was just thinking, maybe we can define a path where they could still be included - like volunteer/contribute.. anyhow, will be a great discussion - thanks for championing this!

**Comment by knobsdao** [comment]
Hi @jessicazartler. So far, they have been getting 1-1 emails or we reach out over Telegram, there aren't standardized comms but one clear action item in my mind is creating them for "we need more personal info". The number of folks scaled in March and it takes a lot of work to process them.

I documented my personal criteria for assessment in the "Trusted Seed Curation" section [in our Notion](https://www.notion.so/giveth/Trusted-Seed-Curation-fd39192ac7cf49b29cb9e8481ba0326e), under TS Process Flow Nº1. You may find it useful and it is something we should go over.

Also, we don't penalize people for the reasons you mention, they can get in, maybe just under an initial lower trust score (two profiles like these have paid membership dues so far and I'm mindful of it). The behaviors I'm pointing out are when little to no personal information is provided and public profiles denote a focus on yield-seeking. When on a 1-1, these profiles usually don't reply or fall out of the journey when I explain it in more detail and mention there's no token listing planned for CSTK, no monetary value in it, no airdrops, etc.

**Comment by jessicazartler** [comment]
Ohhhh, I see okay, awesome, thanks for sharing all this and I see your pain point there. Looking forward to brainstorm :D

**Comment by knobsdao** [comment]
Closing this issue. Email model requesting more information can be found here: https://docs.google.com/document/d/14IvBY-gi6gH3GKa9nqxvKtRy7l0UEB6rmFKIr78bIxg/edit?usp=sharing
