### ISSUE TITLE
Next steps for Angela's LLP to join the Trusted Seed 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#746]
## 📋   Anything to add?

Angela would like to have her LLP join the Trusted Seed. 
The nest steps are two provide her with what must be done based on the precedent set by TrueBlocks.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Its pretty simple... 

On her side, 

1. she needs to write a document saying that her company owns the address she will used for the trusted seed.

2. She could just reapply with the company name (I thought it was a UG?) on our trusted seed list... 

Our side:

3. We accept her as we normally do and add the addy to the registry

4. She uses the address to activate her membership via paying dues

**Comment by tamarandom** [comment]
@GriffGreen We can transfer her personal CSTK score to the new address, right?

**Comment by tamarandom** [comment]
Communicated to Angela. 
@knobsdao can you be on the lookout for an application from conectopia UG and make sure it all goes smoothly for her please?
