### ISSUE TITLE
review & provide feedback on 2021 article 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#751]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hallelujah I have done it! 😇  Comments in the doc.

It's absolutely excellent @Jeff-Emmett and @jessicazartler

**Comment by jessicazartler** [comment]
Woop woop! you da bestest <3
