### ISSUE TITLE
Meme party preparations 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#756]
## 📋   Anything to add?

Go into meme parties with an agenda of 3-4 concepts that are timely and needed mem’ing

This issue is to prepare a list for the next two Friday meme parties! 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Burning tokens 

Twitter threads 

Article points 

core concepts

**Comment by tamarandom** [comment]
I opened this issue as it came out of a previous retro but now question it's existence. 😂

Should we close it or is this a useful reminder to the meme party planners, @GriffGreen ?

**Comment by tamarandom** [comment]
The meme parties are on lock. Closing this issue.
