### ISSUE TITLE
Organizing Partnership Contacts - First Run

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#757]
## 📋   Anything to add?

Need to start working on an organization system for partnerships, sketch a partner journey decision tree/map

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1XnNEszQJ1vJNGsOZutyKIy322eWnGMftovXCVAp1ulY/edit#gid=390705803

**Comment by jessicazartler** [comment]
Thank you so much @knobsdao for your time!!!! I will leave this open until I complete the first run through/iteration of updating/creating the new spreadsheet based on your recommendations

**Comment by jessicazartler** [comment]
Would like to put a little more work into this leading up to hiring our distribution person to take on this organizing for developing a content sharing network

**Comment by tamarandom** [comment]
@YineisyM will take over managing this sheet... 
Closing now.
