### ISSUE TITLE
Sort out contribution flow for ORGS to support CS/TEC

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#760]
## 📋   Anything to add?
We have seen several orgs interested in supporting the CS / TEC launch with contributed funds, but our current structure of the TS only accepting individuals could be hampering our raise potential.

## 🎉   Subtasks

- [ ] Discuss with team.
- [ ] Sort out appropriate flow for organizations who wish to support us.
- [ ] Execute!

## 🤼‍♂️   Reviewer

@tamarandom 

## 🔗   Work doc - inspirational links
https://miro.com/app/board/o9J_laevgm8=/

**Comment by jessicazartler** [comment]
I started a lil' bit in Miro - more sketching pending discussion
https://miro.com/app/board/o9J_laevgm8=/
