### ISSUE TITLE
Revisit the Octalysis Board

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#763]
## 🎉   Subtasks

- [ ] Review work sesh with Juniors.
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
What can be shared from this board to pass on in terms of a knowledge transfer? There was so much good in here.

**Comment by tamarandom** [comment]
https://miro.com/app/board/o9J_kpGPr1U=/

Here is the good. Closing this isssue.
