### ISSUE TITLE
Hiring! Distribution & Social Media Manager 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#778]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
Just closed the one last issue... calling it DONE!!!!!!!! Thank you for all who supported ! @iviangita @tamarandom @GriffGreen @Jeff-Emmett @krisjpi
