### ISSUE TITLE
Review CVs

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#779]

**Comment by jessicazartler** [comment]
@GriffGreen @tamarandom 
I posted it on Crypto Jobs List:
https://cryptojobslist.com/jobs/content-distribution-social-media-manager-at-the-commons-stack-remote
@iviangita so you are aware --- we should be receiving 4 Twitter mentions from @CryptoJobsList if you want to watch out for those and RT - would appreciate it :D thank you all!

**Comment by tamarandom** [comment]
Closed!
