### ISSUE TITLE
Schedule & hold interviews 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#780]

**Comment by jessicazartler** [comment]
Set the first interview for next Wednesday with a great candidate!! :D Jeff and I will interview together, if they pass the first round, will ask @iviangita @krisjpi to maybe take the second interview and/or w/ @tamarandom if you would like to be involved lmk we can chat about the best process

**Comment by tamarandom** [comment]
I trust you all implicitly! Looking forward to meeting our new team mate!

**Comment by jessicazartler** [comment]
Scheduling interviews with two more awesome candidates - one has design experience, would be great if he is a fit! The other has more general marketing experience but mentioned meme creation haha so could be cool as well to see what they're like.. setting these two interviews for hopefully next week...

**Comment by jessicazartler** [comment]
Did two more interviews with Justice Eilers / Farhad Pestonji 
[e6239ab9-e36e-485b-9b7e-9e1313336d7f.pdf](https://github.com/commons-stack/iteration0/files/6758677/e6239ab9-e36e-485b-9b7e-9e1313336d7f.pdf)
[e6239ab9-e36e-485b-9b7e-9e1313336d7f (1).pdf](https://github.com/commons-stack/iteration0/files/6758679/e6239ab9-e36e-485b-9b7e-9e1313336d7f.1.pdf)

We will be bringing on Justice to start as part-time contributor with a few infographics to see how he goes, he also has newsletter/CRM/ambassador program skills that we may try out in the next few months. @krisjpi would you mind adding all his info with @iviangita to our contributor tracking sheet? Would appreciate it!!

I am considering bringing in Farhad to improve our YouTube channel (as he worked for a YouTube specialist subsidiary) and he also is willing to do recording/uploading and tasks similar to TEC transparency, which could come in handy for some research initiatives. Will discuss with the team.

Closing this task and moving to onboarding with Justice CCing @krisjpi @iviangita and will talk to the team about Farhad in the next team meeting.

CC for review @GriffGreen @hanners717 @tamarandom @Jeff-Emmett @knobsdao @liviade1
