### ISSUE TITLE
onboarding new hire

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#783]
Reviewers @tamarandom @iviangita @hanners717

**Comment by jessicazartler** [comment]
Had two meetings with Ekene to go over pay, team calls, cadence, questions, work etc. Had a meeting with Ivy/Kris/Ekene re: Content Distribution flow and improvements. Ekene had meeting with Tam re: Github, and meeting with Dan/Kris to go over hubspot. He also joined for the Gitcoin kickoff and is supporting Peter with Gitcoin Grants content distribution. @tamarandom will chat with you this week to see if there is anything else - I also invited Ekene to our Sprint Retro this week.

**Comment by jessicazartler** [comment]
Ekene went to Happy Money Party with @iviangita but we still need to get the "working agreement" in place - @iviangita can you please kindly follow up with Ekene and send him your new onboarding kit and get the working agreement and paper work in place for him? Would super appreciate it! I am happy to review, but if I can ask for your help to work with him on that would be awesome @hanners717 tagging you also so you are in the loop - thanks so much you two and @tamarandom for your support in improving this process and getting things more organized. 

After that stuff is in place I can close this issue - thank you!

**Comment by jessicazartler** [comment]
Ekene drafted working agreement - reviewing with Ivy

**Comment by jessicazartler** [comment]
Agreement is done and filed - thanks for all your support @iviangita !!!!! Calling it DONE!!! :D
