### ISSUE TITLE
Communicate about the Burning! 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#787]
## 📋   Anything to add?

Make it into a new opportunity to push the "Activate your Trusted Seed Membership" idea

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@Jeff-Emmett @jessicazartler @knobsdao 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1sgFpFslPzy-SdISE-AMdawNkscp8vNXuEiXi8OP52Iw/edit?usp=sharing

**Comment by jessicazartler** [comment]
Jeff scaffolded @krisjpi to write @knobsdao to edit
Then it gets sent with email campaign Dan wrote about the burn 
Target DEADLINE THURSDAY to be going out??

**Comment by knobsdao** [comment]
Thursday is a great target, @jessicazartler. I'll have a better understanding of my times tomorrow, but aiming to make any neccesary arrangements to get this done!
