### ISSUE TITLE
Commons Stack support Ata on TEC Case Study 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#797]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Could have done better with the Roles doc. Looking forward to reviewing and giving feedback on that in the next Sprint.

**Comment by tamarandom** [comment]
We have a snazzy new tracker: https://docs.google.com/spreadsheets/d/1KaLbNATFLcbRNFFF0H64j0tkxw6jvoUK3O8BPy7DLC8/edit#gid=0

**Comment by tamarandom** [comment]
review this: https://docs.google.com/document/d/1JcKwaHfbFFtriBiFM1J--sCT2ErGYNXZUqWEsGVCjaI/edit

**Comment by tamarandom** [comment]
@danelsuga this is a test.

**Comment by danelsuga** [comment]
Hi!

**Comment by tamarandom** [comment]
Closing this. End of an era. Will open new one for the new direction of the Case Study.
