### ISSUE TITLE
Get a bot that updates a spreadsheet with onchain Trusted Seed data (Holdings and Registry) 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#798]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by witwiki** [comment]
Happy to look into this. Just to clarify, when you mean "onchain Trusted Seed data" I assume you mean CSTK token holders or is it something else?

**Comment by witwiki** [comment]
https://duneanalytics.com/clayming-space/Commons-Stack

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/51
