### ISSUE TITLE
Commons Stack Case Study by Felix Medium

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#800]
## 📋   Anything to add?

Jeff had a brilliant idea to do to Felix's paper what he did for his.. it's up on Medium, now we can distribute.

## 🎉   Subtasks

- [x] Write 1-2 tweets
- [ ] Send out in TG/Discord Channels
- [x] Put Tweet in Evergreen rotation here:
https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=1031817319

## 🤼‍♂️   Reviewer

@Jeff-Emmett @krisjpi @iviangita @tamarandom @GriffGreen 

## 🔗   Work doc - inspirational links
https://medium.com/commonsstack/a-case-study-of-the-commons-stack-17abe7cbbc9e

**Comment by jessicazartler** [comment]
Jeff and I will write tweets for this and put in evergreen pipeline to tweet out over the next weeks

**Comment by iviangita** [comment]
Hi @jessicazartler I've already added it in the evergreen content tracker under the Research Papers section. I also drafted 1 tweet for it that's scheduled to go out on May 3. Feel free to edit or add new wording. :)

https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=1031817319

**Comment by jessicazartler** [comment]
Awesome, thank you so much Ivy for taking the initiative!! Going forward, would you mind dropping any content that needs review in the to be scheduled tab to keep it all in one place? I just added some as well, and highlighted for Jeff's review.. so maybe if we can put there and highlight yellow for needs review... then we can change to green when it's ready? What do you think?

And also perhaps whoever authors the piece can do the review is something we discussed in Comms meeting.. let me know if that works and again, you are a rockstar! Will review and then highlight green in to be scheduled.. then we can move to the calendar if that works for you..

**Comment by iviangita** [comment]
@jessicazartler that's great! Thanks for helping improve the process! 🙏

**Comment by Jeff-Emmett** [comment]
https://medium.com/commonsstack/a-case-study-of-the-commons-stack-17abe7cbbc9e

**Comment by jessicazartler** [comment]
Re-opening for @iviangita and I to distribute in TG / Discord channels - we are discussing best process for this going forward

**Comment by jessicazartler** [comment]
Getting sent out in TG/Discord next Monday by Ivy - already on Twitter calendar/evergreen list
