### ISSUE TITLE
Trusted Seed risk mitigations 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#802]
## 📋   Anything to add?

The Sprint 13 Retrospective highlighted where the TS can be strengthened.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
For point number #2 "Investigate method of vouching for new members (similar to moloch)", @GriffGreen and I added two questions to the Typeform:

Do you have any friends already in the Trusted Seed?
If you feel comfortable please share their names and/or handles (Twitter, Telegram, Discord, GitHub).

Do you want to recommend someone to join the Trusted Seed?
If you feel comfortable please share their Twitter handle, Telegram, Discord, or feel free to share the application yourself. Thank you!

Wording can be reviewed at comms. So far it has provided good results.

**Comment by tamarandom** [comment]
Closing this old Epic. Any issues that were still open will have been migrated to the Trusted Seed Sprint Board and can be reviewed and/or closed there.
