### ISSUE TITLE
TS risk mitigation:  invite the ID people who are members of the TS to a closed call

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#803]

**Comment by tamarandom** [comment]
@GriffGreen @iviangita @mafer-cordovas This issue was created to address the possibility of someone in the Trusted Seed applying under false pretense. But it hasn't moved for almost a year. I propose that we close it but first want to make sure that you @mafer-cordovas are tracking these risks somewhere else. Is that something that has come up in the past few months?

**Comment by GriffGreen** [comment]
i think we can close it

**Comment by tamarandom** [comment]
Closing.
