### ISSUE TITLE
Get the swag in the hands of the people 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#805]
## 📋   Anything to add?

Since we switched from notifying new Swiss Mem activations by Telegram and Discord to Email, we've had a drop in the number of people that are actually collecting their swag. Two new members asked us about their swag even though the email went out to them. 

Could be people aren't using their email or that our email gets caught in the spam.

The numbers look like 50% of new members activations have not collected their swag. This is too high. 

How can we make it more clear to people to go get their swag if they haven't? 

Off the cuff ideas 
- follow up with those that haven't opened their email
- send reminder with how-to in next newsletter
- add a note on the Swiss Mem DApp they they will receive notification by email the next Tuesday
- send out a twitter reminder

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey Team! @iviangita agreed to take this on this sprint. 💪🏽

**Comment by iviangita** [comment]
Actions taken:

- Promoted on Twitter: https://twitter.com/commonsstack/status/1397534734574571523?s=20
- Blog post by @krisjpi (thank you!): https://medium.com/commonsstack/using-cslove-to-get-your-free-commons-stack-swag-4b74eb425d90  ([Issue #812](https://github.com/commons-stack/iteration0/issues/812))
- 1on1s by me and @knobsdao :)
