### ISSUE TITLE
Confirm a schedule for Burning

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#806]
@Jeff-Emmett is writing a blog post...

@tamarandom can coordinate the cslove airdrop with the burn

**Comment by knobsdao** [comment]
Picked next Tuesday 25th at 9 pm EST for a Burn Hack Sesh and the following Thursday at 9 am EST to finalize the Burn and populate the Registry - this is Griff and me. It follows the work being done on the Membership DApp and Thurs' meeting precedes a "Swiss Membership DApp Switch Over" session.
