### ISSUE TITLE
Make a Param Submission!!!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#808]
Party Times
https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

**Comment by jessicazartler** [comment]
Thank you @GriffGreen for making this!! :D

**Comment by tamarandom** [comment]
![Screen Shot 2021-05-24 at 12.34.15 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/41437a1e-9ae3-471a-b364-3498b640fd00)
