### ISSUE TITLE
Modify peer/self review form for TEC contributors 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#809]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
This is being done by Hannah. Will assign it to her when she has a github account.

**Comment by liviade1** [comment]
Should we create issues for us as well? will the reviews happen this sprint?

**Comment by tamarandom** [comment]
You mean reviews for core CS peer & self reviews? There is an issue for that, #389, but it has not yet made it into a Sprint.

**Comment by liviade1** [comment]
no I mean for the TEC contributors we listed last week. Should I create an issue as well for filling their review, or hosting sessions with anyone? Might be better to chat quickly about what are the next steps :)

**Comment by tamarandom** [comment]
This is the working doc we're using to define the process, goals, next steps and plan.  Please feel free to review and we can chat it in our sync today.

https://docs.google.com/document/d/1sZrzuNWTARGp9Y4OjhkpaMKo86kYRMOFOLPqc6wYUaE/edit

**Comment by tamarandom** [comment]
Done. Heather and I have been working on these.
Shared with the CS core team for advice process.
