### ISSUE TITLE
Take the Sections of the white paper and make it into blog posts

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#81]
## 🎉   Subtasks

- [ ] Make this into smaller issues
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@sosmissionsuccess

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1DioRXyUttqjCh-EdETTHEVmywf50YUB8ZJThsTYGmXc/edit?usp=sharing

**Comment by sosmissionsuccess** [comment]
Reading white paper now, reviewing it with the perspective of breaking parts off that will be twitter threads that roll into a medium post.

**Comment by Anna-Oz** [comment]
I'm taking on this task. The first article will be most likely based on the Background section.

**Comment by Anna-Oz** [comment]
I'm adding a doc with the draft article on the WP first section. [https://docs.google.com/document/d/14eQGbbX52-6Z_jpuUQZUcx6DsCl9feeEAY4L0YYUB0Q/edit#](url)

**Comment by tamarandom** [comment]
Update: Closing this issue from Aug 2020
