### ISSUE TITLE
Short blog post for claiming CSLOVE 

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#812]
## 📋   Anything to add?

Can we add a section in the website or create a page as a quick reference on the step-by-step process of getting CSLOVE Swag? So we can have a link that we can share on Twitter or on Discord when people ask or so they don't have to dig their emails just to find the process.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Is there someone else that can do this!? I won't be able to get to it right away without displacing another priority!

**Comment by tamarandom** [comment]
@iviangita is working on a simple graphic for this for immediate purposes.

@Jeff-Emmett do you think that I (or @iviangita ) can add the instructions to our Notion? It feels like that would be a lot faster than adding it to our website. 

What do you think, @krisjpi? How easy is it to add a new page to the site right now? Is there a tool we're using to do that?

**Comment by Jeff-Emmett** [comment]
Absolutely - I feel like it could even be a short blog post on its own, which could then be included on our Notion reading list?

"How to turn your TS membership into free & super cool Commons Stack gear!"

**Comment by tamarandom** [comment]
@iviangita, @krisjpi is going to take on writing a very short blog post for this. 

@krisjpi, @iviangita made a great little graphic she's using for twitter & might be good for your article too.

**Comment by krisjpi** [comment]
The short blog explainer is now published - https://medium.com/commonsstack/using-cslove-to-get-your-free-commons-stack-swag-4b74eb425d90
