### ISSUE TITLE
Review Framing for Trusted Seed Membership Removal

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#830]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Personal 1-1 call to explain in person.

**Comment by kosmostasis** [comment]
Necessary steps were taken to remove six members and communicate to them the reasons. All before the Hatch.
