### ISSUE TITLE
Onboard new contributors to Zenhub

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#840]
## 🎉   Subtasks

- [x] Ekene
- [x] Peter?
- [x] Heather ;)

## 🤼‍♂️   Reviewer

@jessicazartler @Jeff-Emmett

**Comment by tamarandom** [comment]
Had first session with @Ekeneodigwe. We should have a followup session after we go through a full Sprint or two. It's easier to grok once you're a little more acclimated to the process.

**Comment by tamarandom** [comment]
Will continue to be here to support any and everyone who needs but these initial sessions are all done.

**Comment by jessicazartler** [comment]
Thank you Tam <3
