### ISSUE TITLE
F/U on Trusted Seed dashboard requirements & user stories brainstorming session 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#843]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
Kristofer hosted us in this amazing board: https://miro.com/app/board/o9J_lBZsbTg=/

**Comment by tamarandom** [comment]
Closing!
