### ISSUE TITLE
Onboard Ekene to Newsletter/CRM/Hubspot Back end Comms

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#847]
## 📋   Anything to add?

@krisjpi @knobsdao could you guys schedule a call with Ekene (maybe beginning next week when I'm gone Mon/Tues/ or Wed) to walk him through back end Comms for newsletter/Hubspot CRM? He was asking me about that and thought it would be great if you all also get to spend time, and he gets a few meetings with a few members with different reflections - thank you!!

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler @tamarandom @GriffGreen @Jeff-Emmett

**Comment by tamarandom** [comment]
The initial session happened. @krisjpi @knobsdao will setup a more regular sync-up.

**Comment by tamarandom** [comment]
The initial session happened. @krisjpi @knobsdao will setup a more regular sync-up.
