### ISSUE TITLE
Content Distribution / SMM Tasks

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#849]
## 🎉   Subtasks

- Get [3-5] YouTube Clips  - that will be 105 seconds for Twitter
- Explore [2-3] Social Tools, write a recommendation that will include how many accounts, pricing, and Properties 
- Create [1-2] Tweet Treads from one of the most engaging articles 
- 1 on 1 with Peter about the Gitcoin project announcement
- Check out [ Slideshare] and make a recommendation
- Set up Hootsuite

## 🤼‍♂️   Reviewer

@

**Comment by Ekeneodigwe** [comment]
- 3 Clips for Twitter sent to @liviade1 for review
- Recommendation for Social Media Tools awaits here reviewshttps://docs.google.com/document/d/17TqI54eC6q6eQt8ydYu4yl7kF4n22TAr011KJFqOm3A/edit
- An evergreen tweet thread created and waiting for review by @jessicazartler 
- @phacker3 and Me published the Gitcoin Grant Announcement on the socials - https://twitter.com/commonsstack/status/1405593064874385415?s=20
- Waiting on @krisjpi to give me Twitter Admin access that way I can set up and link the account on Hootsuite

**Comment by jessicazartler** [comment]
UPDATE/NEXT STEPS:
-Continue on YouTube repurposing 
-Focus next sprint on getting Hootsuite up w/ @krisjpi 
-Tweet thread on Zen Art Understanding piece
-Slideshare (optional)
-Improving the support/questions/FAQ process (create doc & discuss in Comms meeting)
-Refreshing audience doc & strategy on platforms/audience

**Comment by Ekeneodigwe** [comment]
-1 Youtube video repurposed 
-Last sprint Hootsuite was set up w/ @krisjpi
-Tweet thread on Zen Art Understanding piece has been drafted and currently being reviewed by @jessicazartler 
-found a better way to share slides on LinkedIn 
- Improving the support/questions/FAQ process (create doc & discuss in Comms meeting) is in the pipeline
-Started refreshing audience doc & strategy on platforms/audience w/ @jessicazartler @krisjpi & @knobsdao 
-Started working on content sharing network/partnership content development w/ Jess

-11 Github issues  for each task above  were created in July and tagged Jess/Tam/Kris/Jeff were all tagged as "reviewers", 2 has been closed and all the repeating has been moved to the label while some are in backlog sprint

**Comment by Ekeneodigwe** [comment]
> UPDATE/NEXT STEPS:
> Ongoing: improvements on Fbook/Linkedin/Twitter & processes
> 
> -Continue on YouTube repurposing
> -Focus next sprint on getting Hootsuite up w/ @krisjpi
> -Tweet thread on Zen Art Understanding piece
> -Slideshare (optional)
> -Improving the support/questions/FAQ process (create doc & discuss in Comms meeting)
> -Refreshing audience doc & strategy on platforms/audience
> -Start to work on content sharing network/partnership content development w/ Jess
> 
> -Create Github issues for each task above - tag Jess/Tam/Kris/Jeff as "reviewers"

-1 Youtube video repurposed 
-Last sprint Hootsuite was set up w/ @krisjpi
-Tweet thread on Zen Art Understanding piece has been drafted and currently being reviewed by @jessicazartler 
-found a better way to share slides on LinkedIn 
- Improving the support/questions/FAQ process (create doc & discuss in Comms meeting) is in the pipeline
-Started refreshing audience doc & strategy on platforms/audience w/ @jessicazartler @krisjpi & @knobsdao 
-Started working on content sharing network/partnership content development w/ Jess

-11 Github issues  for each task above  were created in July and tagged Jess/Tam/Kris/Jeff were all tagged as "reviewers", 3 has been closed and all the repeating has been moved to the label while some are in backlog sprint
