### ISSUE TITLE
Coordinate all of the TEC Contributor reviews! 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#855]
## 📋   Anything to add?

https://docs.google.com/document/d/1sZrzuNWTARGp9Y4OjhkpaMKo86kYRMOFOLPqc6wYUaE/edit

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen @liviade @tamarandom

**Comment by tamarandom** [comment]
This is well underway. @hanners717 is on top of it! @hanners717 do you want to post your first githhub update here!?

**Comment by hanners717** [comment]
My update is that I've been in contact with all TEC contributors to complete their self-reviews. All replies will be gathered by June 27th.

**Comment by tamarandom** [comment]
Tagging @tamarandom

**Comment by tamarandom** [comment]
Closing these! Praise TEC for funding its own contributors.
