### ISSUE TITLE
Update Pending Scores

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#858]
## 📋   Anything to add?

Successful applicants that have earned praise but haven't activated, have a CSTK Score increase that goes to pending and must be updated in the xDai registry.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Moving issue to Trusted Seed Repo: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/102

**Comment by usama9500** [comment]
Moving issue to Trusted Seed Repo: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/102
