### ISSUE TITLE
Add praisebot to the potluck channel... first to the spreadsheet

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#86]
## 📋   Anything to add?

Context from chatting with will: 

- There is a message sent to people for each different room, so we need a unique message for the potluck room

Will Ruddick CIC Kenya, [20.08.20 19:38]
Wanna write that as a project in the spreadsheet?
Like we would vote to allocate tokens to that project
And you could be the owner, and you end up with 4000 tokens as the initial praise pot
And when ppl spend praise it comes from that pot
...
I might have put a discussion participation reward there already, but can delete that
...
Would be fun. Makes the praise more meaningful to define its source. And if we run out of the tokens in the praise bucket, everyone not participating needs to pay a tax
...
🙈🥶idk

## 🎉   Subtasks

- [x] Redo all the Room Messages!
- [ ] scope out this issue more here

## 🤼‍♂️   Reviewer

@will

**Comment by will** [comment]
I’m @will, which this says it the reviewer. It’s great!! Ship it now!
