### ISSUE TITLE
have a session with greaterthan to co-create our team culture process 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#878]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
maybe we do in september... maybe not at all?

**Comment by liviade1** [comment]
I forgot to ever update this issue - but I had a call with Stefan, explained to him where we were and that we probably wouldn't move forward with the proposal they had but it would be great to share best practices with Greaterthan sometime and develop a more horizontal relationship in this sense. I expressed gratitude from the whole team for the attention they gave us and we had a nice closure.
