### ISSUE TITLE
 Look at a way to thwart impersonations

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#879]
## 📋   Anything to add?

Carried over from #786

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Post a twitter to prove they own the twitter?

**Comment by kosmostasis** [comment]
We added the following question to the application Typeform:

To confirm your identity, it is required to verify over social media. Please share the following message on your Twitter, LinkedIn, or similar.

“I've just applied to become a member of the Trusted Seed of Commons Stack! 🌱”

Paste the link here. ⬇️
