### ISSUE TITLE
shop.commonsstack.org dshop orders are manual, change to automatic 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#887]
## 📋   Anything to add?
After a product is ordered, the order is captured in dshop backend but not sent to Printful until an admin allows it (by clicking send to printful). 

There is a way to change this but ... how? 
Check with Origin dshop support (on their Discord server).

@kristopherlund looping you in in case you can take this one on. It's for the main paid shop on Mainnet not the free swag shops on Rinkeby.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by noncash15** [comment]
#887

**Comment by GriffGreen** [comment]
We can absolutely pay someone to just close this. 

If need be, I can pay crypto straight and be reimbursed by Giveth.

**Comment by tamarandom** [comment]
Nope to everything dshop. Closing.
