### ISSUE TITLE
Repurpose 2 YouTube Videos

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#888]
## 🎉   Subtasks

- [Curate a video Content on Giveth] 
- [Curate another video that explains the purpose of Commons and what sweat equity is] 
- [ ] 

## 🤼‍♂️   Reviewer

@krisjpi 

## 🔗   Work doc - inspirational links

**October** 

- Split Griff's speech at Wyoming into short videos for Twitter (definition, obstacles and Solutions) 
- Turn the main points into a Slide presentation for LinkedIn 

Link -  https://drive.google.com/file/d/1yhMDU4AosJclMTg-XDwb3TmumSmEbcKU/view?usp=sharing

- A demo walkthrough of the Commons Stack Augmented Bonding Curve component. Inviting the audience to come try this illustration, a narrative showcase of cadCAD's capabilities.

https://www.youtube.com/watch?v=ddn_wPm-2E0

**Comment by Ekeneodigwe** [comment]
@GriffGreen could you review this 

Commons Stacks is a community that is focused on making the world a better place through the use of blockchain technology. In this video Product Manager & Cheerleader @griffgreen shares the idea behind our flagship product, the Giveth Donation Application (DApp) which is an integral part of the Commons Stack project. 
Giveth is bringing new governance models into the nonprofit space while fostering a larger network of organizations to help us Build the Future of Giving we envision. .
https://positiveblockchain.io/database/giveth/

03:17 – 04:00 = Our Product Manager & Cheerleader @griffgreen and this week he is explaining the purpose of Commons 

02:30 – 02:59   = Sweat equity is a non-monetary benefit that a company's stakeholders give in labor and time, rather than a monetary contribution that benefit the company. Sweat equity is rewarded in the form of sweat equity shares, wish to learn how we equate that in the Commons Stack? Watch this 
https://www.youtube.com/watch?v=sgoTeOYnv0g&feature=youtu.be

**Comment by GriffGreen** [comment]
> Commons Stacks is a community that is focused on making the world a better place through the use of blockchain technology. In this video Product Manager & Cheerleader @GriffGreen shares the idea behind our flagship product, the Giveth Donation Application (DApp) which is an integral part of the Commons Stack project.
Giveth is bringing new governance models into the nonprofit space while fostering a larger network of organizations to help us Build the Future of Giving we envision. .

rewritten:

Commons Stack is a community that is focused on creating a new way of rewarding contributions to society through the use of token economies. In this video Product Manager & Cheerleader @GriffGreen shares the idea behind our first partner Commons the TE Commons.

**Comment by GriffGreen** [comment]
This Video has nothing to do with Giveth tho

**Comment by Ekeneodigwe** [comment]
> This Video has nothing to do with Giveth tho

There are three copy writings made for the two links. The first that talked about giveth is this 
https://positiveblockchain.io/database/giveth/ 

While the last link focused on TEC and Sweaty Equity.

**Comment by GriffGreen** [comment]
Sorry I am missing this one this week... but it looks like a video got out :-)

**Comment by Ekeneodigwe** [comment]
Hi, @GriffGreen could you help me review this...


02:30 – 02:59 = Sweat equity is a non-monetary benefit that a company's stakeholders give in labour and time, rather than a monetary contribution that benefit the company. Sweat equity is rewarded in the form of sweat equity shares, wish to learn how we equate that in the Commons Stack? Watch this
https://www.youtube.com/watch?v=sgoTeOYnv0g&feature=youtu.be

**Comment by GriffGreen** [comment]
https://youtu.be/PFy458wCQ0g?t=66

This video is the one to cut from for sure

**Comment by Ekeneodigwe** [comment]
> https://youtu.be/PFy458wCQ0g?t=66
> 
> This video is the one to cut from for sure

Our vision and mission are built around creating and sustaining a world where public goods are valued fairly for the benefits they deliver. The deep question however is, what could be classified as a public good?

Welcome to Appreciating Public Goods 101 by @thegrifft!
 
#PGs

Video clip  - " 02:20 "

**Comment by Ekeneodigwe** [comment]
Griff's talk on Collective Psychosis Around Public Goods at the EthCC4 will be turned into 3 mini-series. 
Each handling a section of that presentation. 

1- What's a public good
2- The obstacles to Public good
3- The solution to the issues raised 
 
The idea is to get the Commons to understand what's required of them that way the Collective call of the presentation can be sustained. 

For 1- What is a public good 

The copy will read
"Our vision and mission are built around creating and sustaining a world where public goods are valued fairly for the benefits they deliver. The deep question however is, what could be classified as a public good?

Welcome to Appreciating Public Goods 101 by @thegrifft!
 
#PGs " 

The video will be implanted in this post.....

The Video will start with his introduction to types of public good and stop just right before he started talking about how the government is the one that controls all eg land... 

In total, it's 02:20

**Comment by Ekeneodigwe** [comment]
> Griff's talk on Collective Psychosis Around Public Goods at the EthCC4 will be turned into 3 mini-series. 
> Each handling a section of that presentation. 
> 
> 1- What's a public good
> 2- The obstacles to Public good
> 3- The solution to the issues raised 
>  
> The idea is to get the Commons to understand what's required of them that way the Collective call of the presentation can be sustained. 
> 
> For 1- What is a public good 
> 
> The copy will read
> "Our vision and mission are built around creating and sustaining a world where public goods are valued fairly for the benefits they deliver. The deep question however is, what could be classified as a public good?
> 
> Welcome to Appreciating Public Goods 101 by @thegrifft!
>  
> #PGs " 
> 
> The video will be implanted in this post.....
> 
> The Video will start with his introduction to types of public good and stop just right before he started talking about how the government is the one that controls all eg land... 
> 
> In total, it's 02:20
> 
> 

This video was posted - https://twitter.com/commonsstack/status/1422501208141467684?s=19

**Comment by Ekeneodigwe** [comment]
- 2 ( The Obstacles to Public Goods) 
The copy reads
"The government is a major provider of public goods but at the same time, the non-existence of incentive alignment & top-down approach is all part of what constitute obstacles to public goods.
Join @thegrifft on a new episode of appreciating Public Goods 101" 

The video will go with this post

It will start from where griff said the Number provider of public Goods is the government and will end just before he goes deep into talking about Non for profit 

The Google drive link is https://drive.google.com/file/d/1_3AMwEDinp-1fusFzM3h8alrmMDmQhcx/view?usp=drivesdk

In total, it is 02:11

**Comment by Ekeneodigwe** [comment]
> - 2 ( The Obstacles to Public Goods) 
> The copy reads
> "The government is a major provider of public goods but at the same time, the non-existence of incentive alignment & top-down approach is all part of what constitute obstacles to public goods.
> Join @thegrifft on a new episode of appreciating Public Goods 101" 
> 
> The video will go with this post
> 
> It will start from where griff said the Number provider of public Goods is the government and will end just before he goes deep into talking about Non for profit 
> 
> The Google drive link is https://drive.google.com/file/d/1_3AMwEDinp-1fusFzM3h8alrmMDmQhcx/view?usp=drivesdk
> 
> In total, it is 02:11 

This video has been posted - https://twitter.com/commonsstack/status/1431211722048774145?s=19

**Comment by GriffGreen** [comment]
That was great!!

**Comment by Ekeneodigwe** [comment]
Repurposed and posted 

- https://twitter.com/commonsstack/status/1447864923569197060?s=20

- Walkthrough video of the Commons Stack Augmented Bonding Curve component https://twitter.com/commonsstack/status/1452924503273639936?s=20 

**LinkedIn**

- The walkthrough video of the Commons Stack Augmented Bonding Curve component: https://www.linkedin.com/feed/update/urn:li:activity:6858768077081870336 

- Augmented Bonding Curve Design Simulation Assignment https://www.linkedin.com/feed/update/urn:li:activity:6858827445336858624 

- Conversation, is it possible to implement the Augmented Bonding Curve (ABC) after the token is launched? https://www.linkedin.com/feed/update/urn:li:activity:6859047087267434496

**Comment by Ekeneodigwe** [comment]
This **Sprint**   I will run two video series segmented in to 3 

1. Griff on Bankless - https://www.youtube.com/watch?v=cVC9SbTmfSg 
will feature 

- How I got into Crypto

- What I have learnt in this Journey 

- Why it all matters 

2. The Commons Stack: Realigning Incentives around Public Goods by Kris Decoodt @ Paris P2P Festival #0 - https://www.youtube.com/watch?v=XMwxpVlOMb0 

-

**Comment by Ekeneodigwe** [comment]
> This **Sprint** I will run two video series segmented in to 3
> 
> 1. Griff on Bankless - https://www.youtube.com/watch?v=cVC9SbTmfSg
>    will feature
> 
> * How I got into Crypto
> * What I have learnt in this Journey
> * Why it all matters
> 
> 1. The Commons Stack: Realigning Incentives around Public Goods by Kris Decoodt @ Paris P2P Festival #0 - https://www.youtube.com/watch?v=XMwxpVlOMb0

Bankless Series 
Twitter
-  How I got into Crypto - https://twitter.com/commonsstack/status/1458557008152518665?s=20 
- What I have learnt in this Journey- https://twitter.com/commonsstack/status/1459517199949905923?s=20 

LinkedIn

- How I got into Crypto- https://www.linkedin.com/feed/update/urn:li:activity:6864318699218731008
- What I have learnt in this Journey - https://www.linkedin.com/feed/update/urn:li:activity:6865265965974736896

**Comment by Ekeneodigwe** [comment]
> > This **Sprint** I will run two video series segmented in to 3
> > 
> > 1. Griff on Bankless - https://www.youtube.com/watch?v=cVC9SbTmfSg
> >    will feature
> > 
> > 
> > * How I got into Crypto
> > * What I have learnt in this Journey
> > * Why it all matters
> > 
> > 
> > 1. The Commons Stack: Realigning Incentives around Public Goods by Kris Decoodt @ Paris P2P Festival #0 - https://www.youtube.com/watch?v=XMwxpVlOMb0
> 
> Bankless Series Twitter
> 
> * How I got into Crypto - https://twitter.com/commonsstack/status/1458557008152518665?s=20
> * What I have learnt in this Journey- https://twitter.com/commonsstack/status/1459517199949905923?s=20
> 
> LinkedIn
> 
> * How I got into Crypto- https://www.linkedin.com/feed/update/urn:li:activity:6864318699218731008
> * What I have learnt in this Journey - https://www.linkedin.com/feed/update/urn:li:activity:6865265965974736896

The last part of the bankless Series was published - LinkedIn 

- https://www.linkedin.com/feed/update/urn:li:activity:6866752090065117184  

Twitter

- https://twitter.com/commonsstack/status/1460975589960126471?s=20

**Comment by Ekeneodigwe** [comment]
**This Sprint 22nd November to 4th of December** 

- Token Engineering Commons with Griff | Public Goods Call https://youtu.be/wd5krPdr7WA?t=2985 t

- How could an Augmented Bonding Curve support a community? https://www.youtube.com/watch?v=ClEuV_CtaL4&t=81s

**Comment by Ekeneodigwe** [comment]
**These Two Videos have been Repurposed and Published** 

1. Token Engineering Commons with Griff | Public Goods Call

**Twitter** 

- https://twitter.com/commonsstack/status/1463184584426807297?s=20 

**LinkedIn**
- https://www.linkedin.com/feed/update/urn:li:activity:6868944934104256512

2. How could an Augmented Bonding Curve support a community?  

**Twitter** 

- https://twitter.com/commonsstack/status/1463573603933372422?s=20 

**LinkedIn**

- https://www.linkedin.com/feed/update/urn:li:activity:6869339511197863936 

-

**Comment by Ekeneodigwe** [comment]
**On this Sprint 6th December to 18th December 2021**

- Griff’s conversation with John Paller, one of the co-founders of EthDenver and Opolis on Mission critical infrastructure for DAOs- https://www.youtube.com/watch?v=sTszn9IMJQM 

Repurpose some clips from Commons Stack November AMA: Bonding Curves - https://www.youtube.com/watch?v=2XPPkyolzpY&t=11s

**Comment by Ekeneodigwe** [comment]
This research month we started off with the Trusted Seed Spotlight of Dr. Michael Zargham - https://youtu.be/84BZpe3l5pw  

Posted on Twitter https://twitter.com/commonsstack/status/1479336935562825729?s=20

**Comment by Ekeneodigwe** [comment]
This strategy delivered but we are changing things up, Currently implementing themed months strategy.

**Comment by Ekeneodigwe** [comment]
This strategy delivered but we are changing things up, Currently implementing themed months strategy.

**Comment by Ekeneodigwe** [comment]
Closing this as I have developed and currently employing new strategies for Video content distribution.
