### ISSUE TITLE
Use Slideshare for LinkedIn posts

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#891]
## 🎉   Subtasks

- [Repurpose the Tweet threads into Slide Share for posting on LinkedIn] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by Ekeneodigwe** [comment]
Found a better way to post slides on LinkedIn. Took a lot of time to edit and fit them all in but I am happy because it's all worth it. ....
Check out this link
 https://www.linkedin.com/posts/the-commons-stack_building-a-grammar-of-blockchain-governance-activity-6823289695863099392-pEpg

**Comment by jessicazartler** [comment]
This looks awesome @Ekeneodigwe what tool did you end up using?

**Comment by Ekeneodigwe** [comment]
Thanks, Jess, I created them on PowerPoint then exported them as PDF before posted them as documents on Linkin
