### ISSUE TITLE
Refresh Audience doc & Strategy on platforms 

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#893]
## 🎉   Subtasks

- [Evaluate the existing one and improve on different levels for different channel audiences] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@tamarandom

**Comment by GriffGreen** [comment]
work with @krisjpi @knobsdao @jessicazartler

**Comment by kosmostasis** [comment]
@jessicazartler @Ekeneodigwe @krisjpi The analysis I did on our legacy audience using Octalysis is here on slides 9-15: https://docs.google.com/presentation/d/1RiqPLsleKfobglON4sqqJMLjmZHrF1LD9PBSoRC_hbY/edit#slide=id.gb739c7e729_0_0

**Comment by tamarandom** [comment]
Closing out this issue. 👍🏽
