### ISSUE TITLE
Start work on Content sharing Network/ Partnership content development 

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#894]
## 🎉   Subtasks

- [ Strategic distribution on all platforms ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by jessicazartler** [comment]
@Ekeneodigwe - Just saw @quefear posted it on our CS telegram would you mind reaching out and asking how to submit news to this publication? 

https://medium.com/paradigm-fund/daos-openlaw-releases-the-tribute-dao-makerdao-completes-its-decentralization-uniswap-grants-39fa11fbab74

**Comment by Ekeneodigwe** [comment]
Hello Jess, I just finished talking with her, She is the author and editor of this digest and says we could write our news directly to her. 

I followed up by asking for an email address and once that comes I will pass it forward.

**Comment by Ekeneodigwe** [comment]
> Hello Jess, I just finished talking with her, She is the author and editor of this digest and says we could write our news directly to her. 
> 
> I followed up by asking for an email address and once that comes I will pass it forward.
> 
Here is the email address of the author/publisher for Paradigm on Medium https://medium.com/@paradigmfund - quefearr@gmail.com

**Comment by Ekeneodigwe** [comment]
A more refined agenda on this is contained [In this issue #1094](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/1094)

**Comment by tamarandom** [comment]
Closing out this issue. 👍🏽
