### ISSUE TITLE
CSTK holder transparency list (names & groupings)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#9]
## 📋  Description

We need to have a clear list of CSTK Token holders... we should probably have a list (in no particular order) of the top 15 token holders, and then the next 40, and then the rest... Something like that? This needs to be better defined

## 🎉  Definition of done

- [x] Decide who wants to take this on
- [ ] Schedule a call with Griff and that person/people to spec this out
- [x] Chase the trusted seed holders that need to give approval to display their name on our website
- [ ] Design a sort of Grouped Leaderboard
- [ ] Human touch, links to their twitter

## 🤼‍♂️  Reviewer
Griff

## 🔗  Links
Trusted Seed - CSTK Token Spreadsheet (can't be linked... but relevant)
New Form Responses (can't be linked... but relevant)

**Comment by krrisis** [comment]
Idea here is also to not make this public at all - we can have trusted seed members apply/invite to join field test commons - at that moment the field test commons can decide what they need to know about the trusted seed members that want to join. This would simplify everything a whole lot. Could this work?

**Comment by jessicazartler** [comment]
@GriffGreen is there a second duplicate issue or is this the only one?
@knobsdao @krisjpi will take this task on - I think Livia and I are just here to have an awareness for TEC and of course can assist with strategy/ideas or to share what has happened up until this point - thank you!

**Comment by GriffGreen** [comment]
A comment from Jeff in the Strategy doc:

Whether we should display to CSTK holders not just their ABSOLUTE holdings, but also their RELATIVE holdings (e.g. what % of CSTK tokens do their holdings represent) to give more knowledge about who holds power in this community?  The RELATIVE vs ABSOLUTE token holdings could also be a way that we PREVENT DOXXING of contributors - when people know the % of tokens received rather than the # amount, they can't cross reference addresses with identities in the real world. 

 I'm wondering if a pie chart or other display method would benefit TS members in knowing the distribution of tokens in the Trusted Seed, so that we can continually aim to improve the breadth & depth of TS participation, and continue to reduce the gini coefficient of the TS 

-----

I would still suggest groupings over percentages... but it is worth noting

**Comment by tamarandom** [comment]
Update : 
Have list of 99 paid membership members. 
Good candidate for the first round of TS audit. 
Output: publish the High Score TS list.

**Comment by tamarandom** [comment]
Closing this. This list exists and is being updated frequently. 

The idea for a leaderboard is excellent but can be a new issue that is opened and Dan is creating an issue is the Swiss Mem dApp repo to add a leaderboard (or something similar) as a feature for the TS Dashboard.
