### ISSUE TITLE
Fundraising 

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#90]
## 🎉   Subtasks

- [ Are we calling these individual fundraises? Like 20 of 'em? Or do we have a name for what we're raising for that's larger than a 250k chunk?] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@knobsdao @jessicazartler @krisjpi @Jeff-Emmett 

## 🔗   Work doc - inspirational links
Fundraising Iteration 1 Ramp up notes from Kris/Lo
https://docs.google.com/document/d/1t8bqFkAb4AO7Vt42IEWu8mag-yf0xJC-8lxDPOEbeV4/edit

Fundraising Meeting Notes & Jess Strategy 
https://docs.google.com/document/d/1QCg-3pm8DuCeUNol7ZPvv7hxtOlTorELr2paiUdrt24/edit

Original Fundraising Strategy 
https://docs.google.com/document/d/1sGTqiYavlmMP9rV-bNZItJjNbByxF72o9oxoHNFb0dA/edit#heading=h.ei9l9a3b8j2r

TEC Fundraising Strategy Meeting Notes from last Gitcoin Round
https://docs.google.com/document/d/1GEpluLzmWWyfDzt62edXnfAo0HJC5R0iO2KTG2D3vsA/edit#heading=h.iivb6vmdbfbw

**Comment by GriffGreen** [comment]
Iteration 1 is about the Commons model...

Iteration 0 of our Flagship Commons Model is the cultural build + 1hive Gardens... Field-Tested by the TEC
Iteration 1 of our Flagship Commons Model is the Improved cultural build + ABC&CV Simulation + Commons Stack template of the ABC+CV DApp... Field-Tested by whoever wins the Community Competition

Iteration 2 of our Flagship Commons Model is the improved cultural build + improved ABC&CV Simulation + improved Commons Stack template of the ABC+CV DApp + Giveth DApp Interoperability... Field-Tested by whoever wins the Community Competition

**Comment by lorelei1** [comment]
Griff also wanted to give names to tiers of Trusted Seed members, like Trusted Saplings, Seedlings, etc

**Comment by jessicazartler** [comment]
Added all docs we've had in the past to be integrated into the new strategy to go under our new fundraising epic and will be worked into the plan going forward

**Comment by jessicazartler** [comment]
@tamarandom do you want to keep this epic? just saw that it was still open - if yes, we could add this issue for the upcoming discussion of strategy:

https://github.com/commons-stack/iteration0/issues/466

**Comment by tamarandom** [comment]
Hey @jessicazartler I tagged this one "#refinements" back in Dec to identify it as an issue that can't be closed until someone has a look at it to determine what we need to keep from the docs and history here. Perhaps the fundraising lead when she/he is hired? 

Let's leave this unassigned until we have someone leading fundraising.

And sure, it can be discussed as part of #466.

**Comment by jessicazartler** [comment]
Sounds good - thank you!

**Comment by tamarandom** [comment]
CLosing
