### ISSUE TITLE
Get the template to push the weekly sync case studies out 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#900]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@liviade1 @tamarandom

**Comment by liviade1** [comment]
@ataberkcasur I think you can use the same template from last time, if we need to change anything we can ask someone to help diagraming and it should be simple

**Comment by tamarandom** [comment]
****
