### ISSUE TITLE
Organizational Development Discussions: Identifying Key Topics & Next Steps

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#908]
## 📋   Anything to add?

Draft a process to have discussions around compensation/org boundaries/governance/roles & work loads & resources needed

## 🎉   Subtasks

- [x] Jess draft ideas
- [x] Advice process meeting with Tam/Livia/Dan (a-sync for those who can't attend) - July 6

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen @Jeff-Emmett @liviade1 @krisjpi @knobsdao 

## 🔗   Work doc - inspirational links
Jess Org Dev working Doc
https://docs.google.com/document/d/1JnrKnIbc6PO2wHWzMdEKiywR6l8eFRjR2WGFrux9eWY/edit

GT proposal draft
https://docs.google.com/document/d/1e1zfc7ak_fKBjpdIXmEjrgNS_SYv7WkG5GzFfrBgmQo/edit

**Comment by GriffGreen** [comment]
Needs to be renamed and scoped for this sprint

**Comment by jessicazartler** [comment]
This has morphed into Jeff's circle proposal - cross linking to the new issue https://github.com/commons-stack/iteration0/issues/952 

And will also file there for record keeping for these notes - thanks everyone!
