### ISSUE TITLE
Review Ekene's Working Agreement

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#909]
## 🎉   Subtasks

- [x] Jess review
- [x] Ivy edit
- [x] Finalize & file

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen @hanners717 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1gdWgWBDpydgtYwA0GShDfUQZQIxEmUKuVMvBRG2QDDQ/edit?ts=60e32843#

**Comment by jessicazartler** [comment]
Heya @iviangita I put my edit suggestions and comments in the doc. Flagging one section about paying contributors after they leave - if you can tell me where that came from, I want to make sure that isn't going in contributor agreements elsewhere.

I would prefer we use the language and processes I am suggesting, and would like to make sure that is seen/heard/discussed with @tamarandom @hanners717 @liviade1 for the TEC contributor process as well. 

Thank you for your support in working on this!

**Comment by tamarandom** [comment]
Hey @jessicazartler I just requested access to that doc.

**Comment by iviangita** [comment]
@jessicazartler The "Terms" section in the Work Agreement Template was empty when I shared it with Ekene and added it only after he completed the other parts (he hasn't seen those terms yet). But I left a comment there to clarify with you first if the terms also apply to him or not.

I didn't have any other Terms as basis except the terms in my own work agreement and I assumed the same terms apply for all contributors - apologies, my bad. 

May I suggest to draft a set of terms for each type of contributor (full time, hourly, fixed) so we can add them in our template? We can include this in our discussion of the onboarding process. :)

**Comment by iviangita** [comment]
Hi @jessicazartler I've updated the work agreement with your comments/changes - let me know if it's good to go so I can share with Ekene and add to our tracker :)

https://docs.google.com/document/d/1gdWgWBDpydgtYwA0GShDfUQZQIxEmUKuVMvBRG2QDDQ/edit?usp=sharing

**Comment by jessicazartler** [comment]
@iviangita thank you so much! I added one section about Deliverables - passing to @tamarandom for a final review in the case there is anything else - otherwise, from my side looks great! Thank you again for driving and supporting!!!! <3

**Comment by jessicazartler** [comment]
@tamarandom do you want to review or no? Then @iviangita we can finalize, send and file unless there is anything else? Thank you both!!

**Comment by tamarandom** [comment]
Reviewed and added 2 small comments!

**Comment by iviangita** [comment]
Closing this! Shared the final work agreement with Ekene and filed in our tracker :)

**Comment by jessicazartler** [comment]
Thank you so much @iviangita !!!! Do you also have a GDrive where you are filing? Thanks again for all your support! This will be a very valuable template
