### ISSUE TITLE
Compensation model 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#912]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
I would suggest a 10% raise for everyone to start.

**Comment by tamarandom** [comment]
Update: On hold until after revenue discussions are held

**Comment by tamarandom** [comment]
Following the summer bonus, I am closing this one. Will come back to this within the framework of a larger scope.
