### ISSUE TITLE
Audit of scholarships - reach out to those that have not activated

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#915]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by YineisyM** [comment]
I have contacted them and I'm doing the follow up for the pending ones:

Those are:

Nathalia's Scholarship: Pending for collecting.
Thiago's Scholarship: He needs some ETH to activate, he mentioned to resolved it by his own during this week )5/11/2021 before going to a rural area in Brazil.
Pranav's Scholarship: No answered yet.
Kyle’s Scholarship: He doesn't have a laptop/desktop to activate, maybe he activate this week 8/11/2021.

@mafer-cordovas

**Comment by YineisyM** [comment]
Pranav replied. He requested just 300 DAI and is figuring out how to obtain the remaining 150 DAI to activate... I suggested Pranav to write Griff about this.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/49
