### ISSUE TITLE
Repurpose Tam's talk at the DAOist event

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#918]
## 🎉   Subtasks

- [An Excerpt of the talk is to be written and a clip attached] 
- On the 23rd of July, Our Program Manager @tamarandom told the Daoist gathering of how the work of our first partner commons' stewardship responsibility is inspired by Scrum, majorly because it is within our internal processes which are Transparency, inspection and adaptation. 
Check it out - 

https://drive.google.com/file/d/1XJT2jZW8tVR4gC_Q6VFg2x-WUTBg_VHS/view?usp=drivesdk

## 🤼‍♂️   Reviewer

@tamarandom 

## 🔗   Work doc - inspirational links
https://youtu.be/syA24RXvln0

**Comment by tamarandom** [comment]
Hey @Ekeneodigwe,

Thank you for taking the time to do this. 🙏🏼   I would propose alternative wording:

In July, our Program Manager @tamarandom spoke at the DAOist conference about how Stewards at the TEC (our first partner Commons) integrate the three pillars of empiricism - transparency, inspection and adaptation - into their cultural practices. Check it out -

**Comment by Ekeneodigwe** [comment]
> Hey @Ekeneodigwe,
> 
> Thank you for taking the time to do this. 🙏🏼   I would propose alternative wording:
> 
> In July, our Program Manager @tamarandom spoke at the DAOist conference about how Stewards at the TEC (our first partner Commons) integrate the three pillars of empiricism - transparency, inspection and adaptation - into their cultural practices. Check it out -
> 
> 

Thanks, I will move this to the Twitter planning sheet

**Comment by Ekeneodigwe** [comment]
This has been repurposed on posted on LinkedIn - https://www.linkedin.com/posts/the-commons-stack_commonsstack-tokenengineering-dao-activity-6835887556287045632-b8ro 
As of today with 15 views, 4 reactions, 68 Impressions, 2 shares, 4 clicks and 14.71%  engagement 


While on Twitter 
- https://twitter.com/commonsstack/status/1430120450235977733?s=19

It has 176 views, 5 Retweets, 13 likes, 1481 impressions, 178 media clicks, 34 engagements, 7 detail expands, 6 media engagements and 3 profile clicks
