### ISSUE TITLE
Hack together a way to check pending CSTK Score

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#920]
## 📋   Anything to add?
This came up through conversation with Peter Jones on Twitter. He was wondering if there is any way to check pending CSTK balance prior to joining the Swiss Association and paying dues. This would be a great way to show people the value they've already created and create a stronger incentive for contributors that are already participating but not yet activated to see their contributions and the value to contributing whether or not they have activated.

Ideally this could be integrated over the long term into the Commons Dashboard. cc @kristoferlund 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Isnt this done?

**Comment by mafer-labs** [comment]
This issue passes to be part of the dashboard development.
