### ISSUE TITLE
Work on the blurb from past Newsletter

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#922]
## 🎉   Subtasks

- [ Draft a frame and content] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@krisjpi

**Comment by Ekeneodigwe** [comment]
Attn: @krisjpi 
The draft is prepared and can be accessed here
 https://docs.google.com/document/d/1G2tL_yj5Sx221OtdNr5uUvvlvDlYAqr6VtqTOUN4MHw/edit?usp=drivesdk

**Comment by krisjpi** [comment]
This looks great Ekene, thank you!

**Comment by Ekeneodigwe** [comment]
This blurb was contained in the August 2021 Newsletter update
