### ISSUE TITLE
Run BSci Open Research Office Hour

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#931]
## 📋   Anything to add?
Open Research office hour on relevant primitives, models, and tools for wide use in the web3 ecosystem.

## 🎉   Subtasks

- [ ] Run session
- [ ] Follow up on deliverables & action items to carry the initiative forward

## 🤼‍♂️   Reviewer

@JessicaZartler

**Comment by GriffGreen** [comment]
:fire:

**Comment by GriffGreen** [comment]
Proposal inverter coming in hot

**Comment by Jeff-Emmett** [comment]
CRITICAL: Ensure the measure of Conviction in dollars instead of token seconds.

Key for interoperability of different CV DAOs.

**Comment by jessicazartler** [comment]
@GriffGreen also updating: So Z/Shawn are looking over the Curve Labs Spec to see if it meets the needs of what Jeff/Z were envisioning for the primitive and if not, Z is training Shawn to write Smart Contract specs and they will work together on iterating on these if you wanna have a look:

Z wrote a tech spec https://docs.google.com/document/d/1N6nkuxlC7SqTiOFg4lcZL0AugErSePUIhyG9YoKZqKY/edit
And here is the Github repo if you want to have a look https://github.com/BlockScience/proposal-inverter

Also, we are looking for funding for Shawn to do modelling of the inverter, and I suggested we put Shawn with Ruben to submit a proposal to Prime DAO, so I am working on that - and also think it would be great for CS to continue to compensate Shawn for the work he is doing, and if he can't procure what he needs from Prime DAO or others, that CS can at least give him a little. But I am working with Shawn on presenting to a few partners/DAOs so CS doesn't have to bear too much cost and Shawn can be properly compensated.

We are also thinking of going to Berlin after CCG to have a chance to meet with Pat, and continue discussions on how we can collaborate. Will keep you posted as well but hopefully you can join another office hours soon! :D

**Comment by GriffGreen** [comment]
https://github.com/1Hive/conviction-voting-app/issues/52

^^ Some conversation about conviction in units of the proposal request :-D

**Comment by GriffGreen** [comment]
https://commons.invisionapp.com/console/Conviction-Voting-Prototype-ck0khwxhk02hd01d23mgl75rg/ck0khwyqe0myb01c7f6rnsv06/play
^^ Invision app with dai conviction

**Comment by tamarandom** [comment]
Can we add this to Commons Stack cal as well?

**Comment by tamarandom** [comment]
Wish I was able to hop onto these calls but they are exactly during a school-pickup run. Closing out these older issues for a Sprint Board refresh.
