### ISSUE TITLE
Work Agreement - Peter

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#937]
## 📋   Anything to add?
Prepare Peter's work agreement when he starts his next project - @jessicazartler will let Ivy/Freshelle know 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler @iviangita

**Comment by freshelle** [comment]
Peter's work agreement has been completely filled out. I updated the "CS Hiring / Contributors Tracker" for filing.
