### ISSUE TITLE
Update Trusted Seed Membership List

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#939]
## 📋   Anything to add?
Updating the list with the latest active members, member count and total CSTK in supply.

This list: https://member.commonsstack.foundation/members

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Dan will pass to Maria & Yineisy

**Comment by mafer-labs** [comment]
@kristoferlund we found a problem while updating the JSON. I will reach out for support.

The issue is that the JSON is not applying changes and it deletes the modification history.

**Comment by tamarandom** [comment]
Update: This is on hold because the dashboard will have the membership list when it launches and to fix it will take dev time away from higher priority projects. 

Closing.
