### ISSUE TITLE
Create a system for adding DAOs to the Trusted Seed's "Qualifying DAO's" List

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#943]
https://docs.google.com/document/d/1xtE6jIqO9AgpD6mfp6j3PeP4Suz_DkC-TfZckr9beDY/edit

^^^ Starting point

**Comment by GriffGreen** [comment]
@krisjpi maybe you can support me in this?

**Comment by GriffGreen** [comment]
Made some progress: https://docs.google.com/document/d/1xtE6jIqO9AgpD6mfp6j3PeP4Suz_DkC-TfZckr9beDY/edit

**Comment by mafer-labs** [comment]
@GriffGreen and I discussed the process and details for the Qualifying DAOs application. We agreed on the following to-do list:

- [x] Edit system doc
- [x] Get feedback from Griff, Jeff, Coach B, Z, Kris (association board)
- [x] Make the typeform
- [ ] Talk to Dan, Livia, Kristofer about making the snapshot
- [ ] Have Griff Fill out the typeform for the TEC and CLRfund
- [ ] Go through the process to get them approved!

**Comment by mafer-labs** [comment]
https://docs.google.com/document/d/1Zy8dpSNxWuwGzCfqu1mHP7r_ZzzpHoy3lPam3RzRCmQ/edit?usp=sharing

After a great discussion, I have compiled the main questions remaining to move on with the process.

**Comment by mafer-labs** [comment]
First typeform draft! 
https://the-commons-stack.typeform.com/to/TvE12wFx

**Comment by GriffGreen** [comment]
Closing in favor of #1127
