### ISSUE TITLE
Prepare a work agreement for Kelsie 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#945]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@tamarandom

**Comment by GriffGreen** [comment]
work with @jessicazartler @iviangita and @freshelle on this

**Comment by jessicazartler** [comment]
Wrote Kelsie to ask about how many hours she can commit per month to come up with a monthly retainer for a 3-month duration. Will discuss with @liviade1 and present for approval to team for budget
