### ISSUE TITLE
Christina Funderaiser lead exploration

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#955]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by tamarandom** [comment]
Linked to #914

**Comment by jessicazartler** [comment]
I would like to be informed and in the loop on this as I am currently fulfilling some fundraising functions and have suggested the following criteria and experience for the role in this Github issue https://github.com/commons-stack/iteration0/issues/914:

FROM JOB DESCRIPTION ISSUE #914 
I requested that we please use this template for the job description @hanners717 :
https://docs.google.com/document/d/1Rtf1lJxq3TjgiKOsuiuIhq6TwAfGsv3M3qal-cH2BP8/edit

And also do a bit of research around language/responsibilities for fundraiser roles - looking at both VCs and non-profits to include in the job description.

The main tasks/responsibilities that should also be included in the description are:
-Developing/iterating on the fundraising/business model strategy & development
-Leading Gitcoin Grants (You can check out this issue for more details around the work: #658)
-Grant & proposal writing for grant submission to DAOs & organizations
-Relationship management for private donors / angel donors
-Working with accountant/Program Manager/association board/legal on budgets/entity agreements/compliance

-Ideally the person would have experience in fundraising for non-profits/VC/CFO/accounting experience
-At least basic knowledge of Web3/Crypto

@GriffGreen @tamarandom feel free to weigh in further, or we can schedule a brief call to discuss. I would say this role falls under Operations circle, however a lot of this work I have been doing (Gitcoin/Grant writing) and I would like to hand it off to a role/person, or the person leading fundraising strategy that can hire a part-time support for these roles or tap existing collaborators i.e. Peter who currently support PMing Gitcoin grants / Ruben for DAO proposal. 

I suggest a role that includes all of the above functions and acts more like a CFO, that could manage pat-time contributors for specific tasks i.e. Gitcoin Grants rounds/angel donor relations

**Comment by GriffGreen** [comment]
I don't think the same person who is good at talking to angel investors is the same person who is good at maintaining gitcoin grants... and it might turns someone off from taking the job.

Gitcoin grants IMO would be a bit of a distraction and is best as part of the Comms crew.
