### ISSUE TITLE
Bring the CCG crew into the TEC case studies fold

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#958]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Jeff-Emmett** [comment]
I had some great conversations over the course of the CCG with various researchers (Felix, Vangelis, Scott Morris, etc) who are very eager to contribute to the Commons Stack Research Circle, including potential future case studies.  Given that we just signed a work agreement with Kelsie for current case studies, the next steps on these further research collaborations will follow the budgeting & task roadmap of the Research Circle.
