### ISSUE TITLE
Fundraising Ramp Up Comms

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#96]
## 🎉   Subtasks

- [x] @krrisis talk with loie to spec this out way more
- [ ] Fill this issue out with the items listed in brainstorm doc (this should be done in conjunction with COmms Lead)
- [ ] 

## 🤼‍♂️   Reviewer

@krrisis

**Comment by lorelei1** [comment]
We had a meeting today and got down some good lunar notes on how to approach this https://docs.google.com/document/d/1t8bqFkAb4AO7Vt42IEWu8mag-yf0xJC-8lxDPOEbeV4/edit?usp=sharing

**Comment by lorelei1** [comment]
This is huge, made a plan with @krrisis (at least a lunar one) but I think the next step is to break out all those items into individual issues and timelines, and obviously a comms lead is crucial here. I *may* be able to do some of the planning/specing/timeline-ing before having that person... but I should only really go so far before we get the new hire involved because otherwise we'll just have to change a lot of things!

**Comment by lorelei1** [comment]
All the spec'ing and timing will happen after we hire a Comms Lead

**Comment by jessicazartler** [comment]
I will close this issue as we are creating a new Epic for this and will add the notes doc and integrate with the other docs into the plan going forward. Thank you for all this work and the document!
