### ISSUE TITLE
Change feature video on our Youtube page 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#964]
## 📋   Anything to add?

https://www.youtube.com/channel/UCoyHywZn8YMalyx4ZbvQoyw
![Screen Shot 2021-08-27 at 12.24.32 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/bba154d9-8e2a-495c-ae00-23c0a35519ff)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Rather than leave no feature video, should we add one of the more recent ones? @krisjpi,  @iviangita, @Ekeneodigwe  - what do you think? 

![Screen Shot 2021-09-14 at 9.50.45 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/5c15b9fb-eb3c-4d11-b719-acc1318b42f6)

Also this "Commons Stack Questions & Answers" is very outdated! All these are over a year old and mostly with another team entirely! Would anyone care to give our Youtube page a little TLC in an upcoming Sprint? Maybe bring this up in the Comms call tonight? CC: @jessicazartler @Jeff-Emmett @GriffGreen 

![Screen Shot 2021-09-14 at 9.52.19 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b26dd989-2c14-429e-8dae-13c5655a2607)

**Comment by GriffGreen** [comment]
Great call! I don't know if anyone is actively maintaining this... @Ekeneodigwe @krisjpi @iviangita it would be good to have someone owning it and making sure it is up to date... and then I would delegate decision making power to that person for which video should be featured

**Comment by tamarandom** [comment]
@Ekeneodigwe @iviangita, just coming back round to this as I notice that we still have the same very old video as our feature video. Not sure who will take this though .....

**Comment by iviangita** [comment]
Hi @tamarandom we've already changed the featured video in the Settings but it doesn't reflect on the channel - we're still trying to fix it :/ cc: @krisjpi 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/9f24075a-2884-4abc-8fc1-905885609a73)

**Comment by iviangita** [comment]
FIXED IT! 🥳 

https://www.youtube.com/c/CommonsStack/featured

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/62ebb843-a0a7-4942-85f9-b186648b6bea)

**Comment by jessicazartler** [comment]
That's a good one --- this one might be even better for HOME as its more about CS https://www.youtube.com/watch?v=oF3nsRVSyJc&t=114s @iviangita probably the best general AMA we've had

**Comment by tamarandom** [comment]
Nice!! Thank you @iviangita, @krisjpi !!!

**Comment by iviangita** [comment]
Replaced the video with the Feb AMA suggested by @jessicazartler
