### ISSUE TITLE
Repurpose Anna-Marie's Blog post

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#971]
## 🎉   Subtasks

- [Create a 2 Minutes Video on the insight of the post ] 
- [ Curate the Blog into three (3) parts - The Intro, The Tools and a call to join Commons stack] 
- [ Republishing the piece on other Blockchain Blog sites  ] 

## 🤼‍♂️   Reviewer

@MrsBadgerface, @krisjpi 

## 🔗   Work doc - inspirational links
https://medium.com/commonsstack/commons-the-heart-of-the-creation-era-c4b1ccdb864d

**Comment by Ekeneodigwe** [comment]
@krisjpi please check out this Intro to the blog post. This will be posted with the blog post-medium link  https://drive.google.com/file/d/1d2VLcU88Bkld5dUjupw6-p78PcZ1xeQI/view?usp=drivesdk

**Comment by Ekeneodigwe** [comment]
This was made public today 
Twitter- https://twitter.com/commonsstack/status/1437432294994817025?s=19
LinkedIn- https://www.linkedin.com/feed/update/urn:li:activity:6843202217114128384

**Comment by krisjpi** [comment]
Blog has been published, tweeted, included in our newsletter, and given a contextual video intro to share from @MrsBadgerface. I think we can move the content links into evergreen content @Ekeneodigwe and/or @iviangita, and then the issue can be closed.

Great work everyone!
