### ISSUE TITLE
Ekene Performance Review

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#975]
## 🎉   Subtasks

- [x] Ivy Review
- [x] Jess Review
- [x] Kris Review

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom @iviangita

**Comment by jessicazartler** [comment]
@krisjpi Hope you are having fun in Lisbon! Lmk when is a good time to go over this together to wrap up this last task - thanks!

**Comment by jessicazartler** [comment]
I made a folder and share it with @tamarandom @iviangita @GriffGreen with reviews by myself, KrisJ and Ivy - I have asked that we complete these by the end of the month. We have been working closest with Ekene - LMK if you would like to give feedback or think we should include anyone else in this process. Griff traditionally has given the review results one on one, but I will leave it to you all. LMK if you have any questions, happy to further support - and I will notify you when all reviews are finalized 🙏 

Also passing a self review questionnaire to Ekene

**Comment by jessicazartler** [comment]
Heard back from KrisJ who was on holiday - he will finish before Xmas - will send all to Griff when he's finished @iviangita

**Comment by GriffGreen** [comment]
Review call on the 11th

**Comment by jessicazartler** [comment]
Sent my review to @GriffGreen @tamarandom @iviangita and will poke @krisjpi to let him know of the meeting/deadline - he had said he is willing/wanted to give feedback - thank you and please let me know if you have any questions :D

**Comment by iviangita** [comment]
DONE! Filed the reviews in the Contributors Tracker spreadsheet
