### ISSUE TITLE
Only 11 articles on our medium page, is there some way to see more? 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#977]
## 📋   Anything to add?

I came to the Commons Stack medium page to look for articles to be included in a wishlist for translation and there is no way to scroll below these 11 articles. How does someone find the rest of them please? 

@krisjpi @jessicazartler @Ekeneodigwe 

![Screen Shot 2021-09-08 at 2.47.46 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b9131039-a248-4d37-9737-1abe97e3638d)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer
@

**Comment by Ekeneodigwe** [comment]
@tamarandom could you check this link https://medium.com/commonsstack/latest

**Comment by tamarandom** [comment]
That works, thank you! And now I even see the "latest stories" link on the footer of the page! Do you think it would be possible to have something in the navigation menu that would link to all stories (or even just Latest stories)? 

<img width="916" alt="Screen Shot 2021-09-08 at 4 19 07 PM" src="https://user-images.githubusercontent.com/703624/132526768-5d2fecf1-3b97-4cb8-bb6d-dc8d7e6fbd4c.png">

**Comment by jessicazartler** [comment]
@tamarandom fixed the Medium publication - I made the top features latest, and also extending the # of stories so all from history should be there now https://medium.com/commonsstack

Thanks for pointing that out!

@krisjpi handles the website so any requests for navigation menus is him :D Thanks guys!

**Comment by tamarandom** [comment]
@krisjpi - what do you think? Could we make navigation to the latest stories more prominent in the above fold navigation?

**Comment by tamarandom** [comment]
Closing. Cost of using Medium.

**Comment by jessicazartler** [comment]
@tamarandom you can customize the landing page on Medium and put as many stories as you want and arrange them in different layouts FYI - I could show you or @iviangita how to do it if you like :D

**Comment by tamarandom** [comment]
Thanks @jessicazartler!! It was increased - and the page now shows articles going back to 2019! ![Screen Shot 2022-03-09 at 4.30.36 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/652ee983-c036-4170-9afe-b1e8ed0d865a)

**Comment by jessicazartler** [comment]
Oh okay cool! LMK if you ever need me to show you how to adjust that..
