### ISSUE TITLE
Do you think we should feature a diff article now? This one is from march.

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#978]
## 📋   Anything to add?

![Screen Shot 2021-09-08 at 2.52.34 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/f3796adf-bccc-43e6-9873-49539fc0f4c0)

@krisjpi @jessicazartler @Ekeneodigwe 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
@tamarandom fixed! I made the top features latest, and also extending the # of stories so all from history should be there now https://medium.com/commonsstack 

Thanks for pointing that out!
