### ISSUE TITLE
Document: TS Dashboard project

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#984]
## 📋   Anything to add?

Why are we building a dashboard, and for whom? Why is it important and why should anyone care? The project description describe purpose, goals and vision - what are we trying to accomplish and when will it be done. 

## 🎉   Subtasks

- [X] Write the document based on the input from the ideation work and goals workshop 

## 🤼‍♂️   Reviewers

All of CS core team.

## 🔗   Work doc 

Project doc on HackMD: https://hackmd.io/@kristoferlund/SJ5XsEbuF

**Comment by kristoferlund** [comment]
New project doc lives over at HackMD: https://hackmd.io/@kristoferlund/SJ5XsEbuF

**Comment by tamarandom** [comment]
Closing.... working document.
