### ISSUE TITLE
Document: v1.0 component requirements

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#987]
## 📋   Anything to add?

Document detailing requirements for components included in v1.0.

## 🤼‍♂️   Reviewer

@knobsdao 
@tamarandom 
@YineisyM 
@mafer-cordovas 

## 🔗   Work doc - inspirational links

Functional specs: https://docs.google.com/document/d/1M6ojof65O2qOSmPIG9kDhKGlmZcY0renrVH1W6z30eY/edit#

**Comment by tamarandom** [comment]
Nice. I dropped a few comments in the doc.
