### ISSUE TITLE
Workshop: Sprint 1 planning

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#988]
## 📋   Anything to add?

Draft and assign issues for the first prototyping sprint, beginning Oct 4.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Exciting!

**Comment by kristoferlund** [comment]
Closing. We'll start sprint planning for project when there is more of a development team. The prototyping phase moves on without sprint planning.
