### ISSUE TITLE
support case studies development 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#995]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Push! Support Nate and Carole to get things ready. goal would be to get Nate's ready for a draft for review.

**Comment by liviade1** [comment]
https://docs.google.com/document/d/1DcyBt9rG5DBiqzLzyr0C88lh8TqYdl7l-5e-KPXDcjc/edit
