### ISSUE TITLE
give feedback to cultural onboarding from Heather 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#999]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
https://docs.google.com/document/d/1F1M9HGiSd55IZRdMcj_rREzfjglIn2WiLyBPKplo84Y/edit# 
@tamarandom

**Comment by tamarandom** [comment]
this is beautiful &  it almost reads like a manifesto as a "published declaration of the intentions, motives, or views".
